// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2_1/1143609 Production Release
//  HLS Date:       Wed Nov 13 18:57:31 PST 2024
// 
//  Generated by:   code@iron-05
//  Generated date: Wed Mar 18 17:29:14 2026
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    ACC_17i31_1o31_35d03a7c76a8394e7c510c9fae810dcdee
// ------------------------------------------------------------------


module ACC_17i31_1o31_35d03a7c76a8394e7c510c9fae810dcdee (
  I_1, I_2, I_3, I_4, I_5, I_6, I_7, I_8, I_9, I_10, I_11, I_12, I_13, I_14, I_15,
      I_16, I_17, O_1
);
  input [15:0] I_1;
  input [15:0] I_2;
  input [15:0] I_3;
  input [15:0] I_4;
  input [15:0] I_5;
  input [15:0] I_6;
  input [15:0] I_7;
  input [15:0] I_8;
  input [15:0] I_9;
  input [15:0] I_10;
  input [15:0] I_11;
  input [15:0] I_12;
  input [15:0] I_13;
  input [15:0] I_14;
  input [15:0] I_15;
  input [15:0] I_16;
  input [30:0] I_17;
  output [30:0] O_1;
  wire [34:0] nl_O_1;


  wire[30:0] ProductSum_for_acc_9_nl;
  wire[33:0] nl_ProductSum_for_acc_9_nl;
  wire[30:0] ProductSum_for_acc_10_nl;
  wire[31:0] nl_ProductSum_for_acc_10_nl;

  // Interconnect Declarations for Component Instantiations 
  assign nl_ProductSum_for_acc_10_nl = I_17 + conv_s2s_16_31(I_9);
  assign ProductSum_for_acc_10_nl = nl_ProductSum_for_acc_10_nl[30:0];
  assign nl_ProductSum_for_acc_9_nl = ProductSum_for_acc_10_nl + conv_s2s_16_31(I_3)
      + conv_s2s_16_31(I_4) + conv_s2s_16_31(I_5) + conv_s2s_16_31(I_6) + conv_s2s_16_31(I_7)
      + conv_s2s_16_31(I_8);
  assign ProductSum_for_acc_9_nl = nl_ProductSum_for_acc_9_nl[30:0];
  assign nl_O_1 = ProductSum_for_acc_9_nl + conv_s2s_16_31(I_10) + conv_s2s_16_31(I_11)
      + conv_s2s_16_31(I_16) + conv_s2s_16_31(I_12) + conv_s2s_16_31(I_13) + conv_s2s_16_31(I_14)
      + conv_s2s_16_31(I_1) + conv_s2s_16_31(I_2) + conv_s2s_16_31(I_15);
  assign O_1 = nl_O_1[30:0];

  function automatic [30:0] conv_s2s_16_31 ;
    input [15:0]  vector ;
  begin
    conv_s2s_16_31 = {{15{vector[15]}}, vector};
  end
  endfunction

endmodule



