// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2024.2_1/1143609 Production Release
//       HLS date: Wed Nov 13 18:57:31 PST 2024
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: code@iron-05
// Generated date: Wed Mar 18 19:10:11 PDT 2026
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model NMP
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Constructor: sysc_sim_wrapper

CCS_RTL::sysc_sim_wrapper::sysc_sim_wrapper(
   const sc_module_name& nm
)
   : ccs_rtl(
      "ccs_rtl",
      "ccs_wrapper"
   )
   , clk("clk")
   , rst("rst")
   , rva_in("rva_in")
   , rva_out("rva_out")
   , start("start")
   , done("done")
   , large_req("large_req")
   , large_rsp("large_rsp")
   , ccs_rtl_SIG_clk("ccs_rtl_SIG_clk")
   , ccs_rtl_SIG_rst("ccs_rtl_SIG_rst")
   , ccs_rtl_SIG_rva_in_vld("ccs_rtl_SIG_rva_in_vld")
   , ccs_rtl_SIG_rva_in_rdy("ccs_rtl_SIG_rva_in_rdy")
   , ccs_rtl_SIG_rva_in_dat("ccs_rtl_SIG_rva_in_dat")
   , ccs_rtl_SIG_rva_out_vld("ccs_rtl_SIG_rva_out_vld")
   , ccs_rtl_SIG_rva_out_rdy("ccs_rtl_SIG_rva_out_rdy")
   , ccs_rtl_SIG_rva_out_dat("ccs_rtl_SIG_rva_out_dat")
   , ccs_rtl_SIG_start_vld("ccs_rtl_SIG_start_vld")
   , ccs_rtl_SIG_start_rdy("ccs_rtl_SIG_start_rdy")
   , ccs_rtl_SIG_start_dat("ccs_rtl_SIG_start_dat")
   , ccs_rtl_SIG_done_vld("ccs_rtl_SIG_done_vld")
   , ccs_rtl_SIG_done_rdy("ccs_rtl_SIG_done_rdy")
   , ccs_rtl_SIG_done_dat("ccs_rtl_SIG_done_dat")
   , ccs_rtl_SIG_large_req_vld("ccs_rtl_SIG_large_req_vld")
   , ccs_rtl_SIG_large_req_rdy("ccs_rtl_SIG_large_req_rdy")
   , ccs_rtl_SIG_large_req_dat("ccs_rtl_SIG_large_req_dat")
   , ccs_rtl_SIG_large_rsp_vld("ccs_rtl_SIG_large_rsp_vld")
   , ccs_rtl_SIG_large_rsp_rdy("ccs_rtl_SIG_large_rsp_rdy")
   , ccs_rtl_SIG_large_rsp_dat("ccs_rtl_SIG_large_rsp_dat")
   , SIG_SC_LOGIC_0("SIG_SC_LOGIC_0")
   , SIG_SC_LOGIC_1("SIG_SC_LOGIC_1")
{
   // Instantiate other modules
   ccs_rtl.clk(ccs_rtl_SIG_clk);
   ccs_rtl.rst(ccs_rtl_SIG_rst);
   ccs_rtl.rva_in_vld(ccs_rtl_SIG_rva_in_vld);
   ccs_rtl.rva_in_rdy(ccs_rtl_SIG_rva_in_rdy);
   ccs_rtl.rva_in_dat(ccs_rtl_SIG_rva_in_dat);
   ccs_rtl.rva_out_vld(ccs_rtl_SIG_rva_out_vld);
   ccs_rtl.rva_out_rdy(ccs_rtl_SIG_rva_out_rdy);
   ccs_rtl.rva_out_dat(ccs_rtl_SIG_rva_out_dat);
   ccs_rtl.start_vld(ccs_rtl_SIG_start_vld);
   ccs_rtl.start_rdy(ccs_rtl_SIG_start_rdy);
   ccs_rtl.start_dat(ccs_rtl_SIG_start_dat);
   ccs_rtl.done_vld(ccs_rtl_SIG_done_vld);
   ccs_rtl.done_rdy(ccs_rtl_SIG_done_rdy);
   ccs_rtl.done_dat(ccs_rtl_SIG_done_dat);
   ccs_rtl.large_req_vld(ccs_rtl_SIG_large_req_vld);
   ccs_rtl.large_req_rdy(ccs_rtl_SIG_large_req_rdy);
   ccs_rtl.large_req_dat(ccs_rtl_SIG_large_req_dat);
   ccs_rtl.large_rsp_vld(ccs_rtl_SIG_large_rsp_vld);
   ccs_rtl.large_rsp_rdy(ccs_rtl_SIG_large_rsp_rdy);
   ccs_rtl.large_rsp_dat(ccs_rtl_SIG_large_rsp_dat);
   
   // Register processes
   SC_METHOD(update_proc);
   sensitive  << clk << rst << rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::vld << ccs_rtl_SIG_rva_in_rdy << rva_in.Connections::InBlocking<RVSink<spec::Axi::rvaCfg >::Write, Connections::SYN_PORT >::dat << ccs_rtl_SIG_rva_out_vld << rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::rdy << ccs_rtl_SIG_rva_out_dat << start.Connections::InBlocking_Ports_abs<bool >::vld << ccs_rtl_SIG_start_rdy << start.Connections::InBlocking<bool, Connections::SYN_PORT >::dat << ccs_rtl_SIG_done_vld << done.Connections::OutBlocking_Ports_abs<bool >::rdy << ccs_rtl_SIG_done_dat << ccs_rtl_SIG_large_req_vld << large_req.Connections::OutBlocking_Ports_abs<spec::GB::Large::DataReq >::rdy << ccs_rtl_SIG_large_req_dat << large_rsp.Connections::InBlocking_Ports_abs<spec::GB::Large::DataRsp<1U > >::vld << ccs_rtl_SIG_large_rsp_rdy << large_rsp.Connections::InBlocking<spec::GB::Large::DataRsp<1U >, Connections::SYN_PORT >::dat;
   // Other constructor statements
   SIG_SC_LOGIC_0.write(SC_LOGIC_0);
   SIG_SC_LOGIC_1.write(SC_LOGIC_1);
}

// ---------------------------------------------------------------
// Process: SC_METHOD update_proc

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   
   // none.sc_in field_key=clk:9c996015-d019-44e6-adbd-e943d4f6c9eb-2256:clk:9c996015-d019-44e6-adbd-e943d4f6c9eb-2256
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2256; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:9c996015-d019-44e6-adbd-e943d4f6c9eb-2257:rst:9c996015-d019-44e6-adbd-e943d4f6c9eb-2257
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2257; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2257); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2257); // then write to RTL port
   
   // none.sc_in field_key=rva_in:9c996015-d019-44e6-adbd-e943d4f6c9eb-2263:vld:9c996015-d019-44e6-adbd-e943d4f6c9eb-2274
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2274; // NPS - LV to hold field
   type_to_vector(rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::vld.read(),1,t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2274); // read orig port and type convert
   ccs_rtl_SIG_rva_in_vld.write(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2274); // then write to RTL port
   
   // none.sc_out field_key=rva_in:9c996015-d019-44e6-adbd-e943d4f6c9eb-2263:rdy:9c996015-d019-44e6-adbd-e943d4f6c9eb-2275
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2275;
   bool d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2275;
   t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2275 = ccs_rtl_SIG_rva_in_rdy.read();
   vector_to_type(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2275, 1, &d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2275);
   rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::rdy.write(d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2275);
   
   // none.sc_in field_key=rva_in:9c996015-d019-44e6-adbd-e943d4f6c9eb-2263:dat:9c996015-d019-44e6-adbd-e943d4f6c9eb-2276
   sc_lv< 169 > t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2276; // NPS - LV to hold field
   type_to_vector(rva_in.Connections::InBlocking<RVSink<spec::Axi::rvaCfg >::Write, Connections::SYN_PORT >::dat.read(),169,t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2276); // read orig port and type convert
   ccs_rtl_SIG_rva_in_dat.write(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2276); // then write to RTL port
   
   // none.sc_out field_key=rva_out:9c996015-d019-44e6-adbd-e943d4f6c9eb-2277:vld:9c996015-d019-44e6-adbd-e943d4f6c9eb-2286
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2286;
   bool d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2286;
   t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2286 = ccs_rtl_SIG_rva_out_vld.read();
   vector_to_type(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2286, 1, &d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2286);
   rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::vld.write(d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2286);
   
   // none.sc_in field_key=rva_out:9c996015-d019-44e6-adbd-e943d4f6c9eb-2277:rdy:9c996015-d019-44e6-adbd-e943d4f6c9eb-2287
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2287; // NPS - LV to hold field
   type_to_vector(rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::rdy.read(),1,t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2287); // read orig port and type convert
   ccs_rtl_SIG_rva_out_rdy.write(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2287); // then write to RTL port
   
   // none.sc_out field_key=rva_out:9c996015-d019-44e6-adbd-e943d4f6c9eb-2277:dat:9c996015-d019-44e6-adbd-e943d4f6c9eb-2288
   sc_lv< 128 > t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2288;
   sc_dt::sc_lv<128 > d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2288;
   t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2288 = ccs_rtl_SIG_rva_out_dat.read();
   vector_to_type(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2288, 128, &d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2288);
   rva_out.Connections::OutBlocking<RVSink<spec::Axi::rvaCfg >::Read, Connections::SYN_PORT >::dat.write(d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2288);
   
   // none.sc_in field_key=start:9c996015-d019-44e6-adbd-e943d4f6c9eb-2289:vld:9c996015-d019-44e6-adbd-e943d4f6c9eb-2298
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2298; // NPS - LV to hold field
   type_to_vector(start.Connections::InBlocking_Ports_abs<bool >::vld.read(),1,t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2298); // read orig port and type convert
   ccs_rtl_SIG_start_vld.write(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2298); // then write to RTL port
   
   // none.sc_out field_key=start:9c996015-d019-44e6-adbd-e943d4f6c9eb-2289:rdy:9c996015-d019-44e6-adbd-e943d4f6c9eb-2299
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2299;
   bool d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2299;
   t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2299 = ccs_rtl_SIG_start_rdy.read();
   vector_to_type(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2299, 1, &d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2299);
   start.Connections::InBlocking_Ports_abs<bool >::rdy.write(d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2299);
   
   // none.sc_in field_key=start:9c996015-d019-44e6-adbd-e943d4f6c9eb-2289:dat:9c996015-d019-44e6-adbd-e943d4f6c9eb-2300
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2300; // NPS - LV to hold field
   type_to_vector(start.Connections::InBlocking<bool, Connections::SYN_PORT >::dat.read(),1,t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2300); // read orig port and type convert
   ccs_rtl_SIG_start_dat.write(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2300); // then write to RTL port
   
   // none.sc_out field_key=done:9c996015-d019-44e6-adbd-e943d4f6c9eb-2301:vld:9c996015-d019-44e6-adbd-e943d4f6c9eb-2310
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2310;
   bool d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2310;
   t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2310 = ccs_rtl_SIG_done_vld.read();
   vector_to_type(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2310, 1, &d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2310);
   done.Connections::OutBlocking_Ports_abs<bool >::vld.write(d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2310);
   
   // none.sc_in field_key=done:9c996015-d019-44e6-adbd-e943d4f6c9eb-2301:rdy:9c996015-d019-44e6-adbd-e943d4f6c9eb-2311
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2311; // NPS - LV to hold field
   type_to_vector(done.Connections::OutBlocking_Ports_abs<bool >::rdy.read(),1,t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2311); // read orig port and type convert
   ccs_rtl_SIG_done_rdy.write(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2311); // then write to RTL port
   
   // none.sc_out field_key=done:9c996015-d019-44e6-adbd-e943d4f6c9eb-2301:dat:9c996015-d019-44e6-adbd-e943d4f6c9eb-2312
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2312;
   sc_dt::sc_lv<1 > d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2312;
   t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2312 = ccs_rtl_SIG_done_dat.read();
   vector_to_type(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2312, 1, &d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2312);
   done.Connections::OutBlocking<bool, Connections::SYN_PORT >::dat.write(d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2312);
   
   // none.sc_out field_key=large_req:9c996015-d019-44e6-adbd-e943d4f6c9eb-2313:vld:9c996015-d019-44e6-adbd-e943d4f6c9eb-2322
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2322;
   bool d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2322;
   t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2322 = ccs_rtl_SIG_large_req_vld.read();
   vector_to_type(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2322, 1, &d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2322);
   large_req.Connections::OutBlocking_Ports_abs<spec::GB::Large::DataReq >::vld.write(d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2322);
   
   // none.sc_in field_key=large_req:9c996015-d019-44e6-adbd-e943d4f6c9eb-2313:rdy:9c996015-d019-44e6-adbd-e943d4f6c9eb-2323
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2323; // NPS - LV to hold field
   type_to_vector(large_req.Connections::OutBlocking_Ports_abs<spec::GB::Large::DataReq >::rdy.read(),1,t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2323); // read orig port and type convert
   ccs_rtl_SIG_large_req_rdy.write(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2323); // then write to RTL port
   
   // none.sc_out field_key=large_req:9c996015-d019-44e6-adbd-e943d4f6c9eb-2313:dat:9c996015-d019-44e6-adbd-e943d4f6c9eb-2324
   sc_lv< 155 > t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2324;
   sc_dt::sc_lv<155 > d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2324;
   t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2324 = ccs_rtl_SIG_large_req_dat.read();
   vector_to_type(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2324, 155, &d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2324);
   large_req.Connections::OutBlocking<spec::GB::Large::DataReq, Connections::SYN_PORT >::dat.write(d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2324);
   
   // none.sc_in field_key=large_rsp:9c996015-d019-44e6-adbd-e943d4f6c9eb-2325:vld:9c996015-d019-44e6-adbd-e943d4f6c9eb-2334
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2334; // NPS - LV to hold field
   type_to_vector(large_rsp.Connections::InBlocking_Ports_abs<spec::GB::Large::DataRsp<1U > >::vld.read(),1,t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2334); // read orig port and type convert
   ccs_rtl_SIG_large_rsp_vld.write(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2334); // then write to RTL port
   
   // none.sc_out field_key=large_rsp:9c996015-d019-44e6-adbd-e943d4f6c9eb-2325:rdy:9c996015-d019-44e6-adbd-e943d4f6c9eb-2335
   sc_logic t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2335;
   bool d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2335;
   t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2335 = ccs_rtl_SIG_large_rsp_rdy.read();
   vector_to_type(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2335, 1, &d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2335);
   large_rsp.Connections::InBlocking_Ports_abs<spec::GB::Large::DataRsp<1U > >::rdy.write(d_9c996015_d019_44e6_adbd_e943d4f6c9eb_2335);
   
   // none.sc_in field_key=large_rsp:9c996015-d019-44e6-adbd-e943d4f6c9eb-2325:dat:9c996015-d019-44e6-adbd-e943d4f6c9eb-2336
   sc_lv< 128 > t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2336; // NPS - LV to hold field
   type_to_vector(large_rsp.Connections::InBlocking<spec::GB::Large::DataRsp<1U >, Connections::SYN_PORT >::dat.read(),128,t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2336); // read orig port and type convert
   ccs_rtl_SIG_large_rsp_dat.write(t_9c996015_d019_44e6_adbd_e943d4f6c9eb_2336); // then write to RTL port
}
