// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.h
//
//    HLS version: 2024.2_1/1143609 Production Release
//       HLS date: Wed Nov 13 18:57:31 PST 2024
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: code@iron-05
// Generated date: Wed Mar 18 17:18:23 PDT 2026
//
// ----------------------------------------------------------------------------
#ifndef INCLUDED_SYSC_SIM_WRAPPER_H
#define INCLUDED_SYSC_SIM_WRAPPER_H
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model ActUnit
// -------------------------------------
// 

#ifndef TO_QUOTED_STRING
#define TO_QUOTED_STRING(x) TO_QUOTED_STRING1(x)
#define TO_QUOTED_STRING1(x) #x
#endif
extern double __scv_hold_time;


#ifndef SC_USE_STD_STRING
#define SC_USE_STD_STRING
#endif

#include "../../../../../../../src/Top/PEPartition/PEModule/ActUnit/ActUnit.h"
#include <systemc.h>
#include <mc_stall_ctrl.h>
#include <mc_scv_trans.h>
#include "mc_dut_wrapper.h"


namespace CCS_RTL {
   class sysc_sim_wrapper : public sc_module
   {
   public:
      // Module instance pointers
      HDL::ccs_DUT_wrapper ccs_rtl;
      
      // Interface Ports
      sc_core::sc_in<bool > clk;
      sc_core::sc_in<bool > rst;
      Connections::In<bool, Connections::SYN_PORT > start;
      Connections::In<nvhls::nv_scvector<ac_int<16, true >, 16U >, Connections::SYN_PORT > act_port;
      Connections::In<RVSink<spec::Axi::rvaCfg >::Write, Connections::SYN_PORT > rva_in;
      Connections::Out<RVSink<spec::Axi::rvaCfg >::Read, Connections::SYN_PORT > rva_out;
      Connections::Out<spec::StreamType, Connections::SYN_PORT > output_port;
      Connections::Out<bool, Connections::SYN_PORT > done;
      
      // Named Objects
      
      // Data objects
      sc_signal< bool >                          ccs_rtl_SIG_clk;
      sc_signal< sc_logic >                      ccs_rtl_SIG_rst;
      sc_signal< sc_logic >                      ccs_rtl_SIG_start_vld;
      sc_signal< sc_logic >                      ccs_rtl_SIG_start_rdy;
      sc_signal< sc_logic >                      ccs_rtl_SIG_start_dat;
      sc_signal< sc_logic >                      ccs_rtl_SIG_act_port_vld;
      sc_signal< sc_logic >                      ccs_rtl_SIG_act_port_rdy;
      sc_signal< sc_lv<256> >                    ccs_rtl_SIG_act_port_dat;
      sc_signal< sc_logic >                      ccs_rtl_SIG_rva_in_vld;
      sc_signal< sc_logic >                      ccs_rtl_SIG_rva_in_rdy;
      sc_signal< sc_lv<169> >                    ccs_rtl_SIG_rva_in_dat;
      sc_signal< sc_logic >                      ccs_rtl_SIG_rva_out_vld;
      sc_signal< sc_logic >                      ccs_rtl_SIG_rva_out_rdy;
      sc_signal< sc_lv<128> >                    ccs_rtl_SIG_rva_out_dat;
      sc_signal< sc_logic >                      ccs_rtl_SIG_output_port_vld;
      sc_signal< sc_logic >                      ccs_rtl_SIG_output_port_rdy;
      sc_signal< sc_lv<138> >                    ccs_rtl_SIG_output_port_dat;
      sc_signal< sc_logic >                      ccs_rtl_SIG_done_vld;
      sc_signal< sc_logic >                      ccs_rtl_SIG_done_rdy;
      sc_signal< sc_logic >                      ccs_rtl_SIG_done_dat;
      sc_signal< sc_logic >                      SIG_SC_LOGIC_0;
      sc_signal< sc_logic >                      SIG_SC_LOGIC_1;
      
      // Declare processes (SC_METHOD and SC_THREAD)
      void update_proc();
      
      // Constructor
      SC_HAS_PROCESS(sysc_sim_wrapper);
      sysc_sim_wrapper(
         const sc_module_name& nm
      );
      ~sysc_sim_wrapper()
      {
      }
      
      // C++ class functions
   };
} // end namespace CCS_RTL
#endif //INCLUDED_SYSC_SIM_WRAPPER_H
