// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2024.2_1/1143609 Production Release
//       HLS date: Wed Nov 13 18:57:31 PST 2024
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: code@iron-05
// Generated date: Wed Mar 18 17:18:23 PDT 2026
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model ActUnit
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Constructor: sysc_sim_wrapper

CCS_RTL::sysc_sim_wrapper::sysc_sim_wrapper(
   const sc_module_name& nm
)
   : ccs_rtl(
      "ccs_rtl",
      "ccs_wrapper"
   )
   , clk("clk")
   , rst("rst")
   , start("start")
   , act_port("act_port")
   , rva_in("rva_in")
   , rva_out("rva_out")
   , output_port("output_port")
   , done("done")
   , ccs_rtl_SIG_clk("ccs_rtl_SIG_clk")
   , ccs_rtl_SIG_rst("ccs_rtl_SIG_rst")
   , ccs_rtl_SIG_start_vld("ccs_rtl_SIG_start_vld")
   , ccs_rtl_SIG_start_rdy("ccs_rtl_SIG_start_rdy")
   , ccs_rtl_SIG_start_dat("ccs_rtl_SIG_start_dat")
   , ccs_rtl_SIG_act_port_vld("ccs_rtl_SIG_act_port_vld")
   , ccs_rtl_SIG_act_port_rdy("ccs_rtl_SIG_act_port_rdy")
   , ccs_rtl_SIG_act_port_dat("ccs_rtl_SIG_act_port_dat")
   , ccs_rtl_SIG_rva_in_vld("ccs_rtl_SIG_rva_in_vld")
   , ccs_rtl_SIG_rva_in_rdy("ccs_rtl_SIG_rva_in_rdy")
   , ccs_rtl_SIG_rva_in_dat("ccs_rtl_SIG_rva_in_dat")
   , ccs_rtl_SIG_rva_out_vld("ccs_rtl_SIG_rva_out_vld")
   , ccs_rtl_SIG_rva_out_rdy("ccs_rtl_SIG_rva_out_rdy")
   , ccs_rtl_SIG_rva_out_dat("ccs_rtl_SIG_rva_out_dat")
   , ccs_rtl_SIG_output_port_vld("ccs_rtl_SIG_output_port_vld")
   , ccs_rtl_SIG_output_port_rdy("ccs_rtl_SIG_output_port_rdy")
   , ccs_rtl_SIG_output_port_dat("ccs_rtl_SIG_output_port_dat")
   , ccs_rtl_SIG_done_vld("ccs_rtl_SIG_done_vld")
   , ccs_rtl_SIG_done_rdy("ccs_rtl_SIG_done_rdy")
   , ccs_rtl_SIG_done_dat("ccs_rtl_SIG_done_dat")
   , SIG_SC_LOGIC_0("SIG_SC_LOGIC_0")
   , SIG_SC_LOGIC_1("SIG_SC_LOGIC_1")
{
   // Instantiate other modules
   ccs_rtl.clk(ccs_rtl_SIG_clk);
   ccs_rtl.rst(ccs_rtl_SIG_rst);
   ccs_rtl.start_vld(ccs_rtl_SIG_start_vld);
   ccs_rtl.start_rdy(ccs_rtl_SIG_start_rdy);
   ccs_rtl.start_dat(ccs_rtl_SIG_start_dat);
   ccs_rtl.act_port_vld(ccs_rtl_SIG_act_port_vld);
   ccs_rtl.act_port_rdy(ccs_rtl_SIG_act_port_rdy);
   ccs_rtl.act_port_dat(ccs_rtl_SIG_act_port_dat);
   ccs_rtl.rva_in_vld(ccs_rtl_SIG_rva_in_vld);
   ccs_rtl.rva_in_rdy(ccs_rtl_SIG_rva_in_rdy);
   ccs_rtl.rva_in_dat(ccs_rtl_SIG_rva_in_dat);
   ccs_rtl.rva_out_vld(ccs_rtl_SIG_rva_out_vld);
   ccs_rtl.rva_out_rdy(ccs_rtl_SIG_rva_out_rdy);
   ccs_rtl.rva_out_dat(ccs_rtl_SIG_rva_out_dat);
   ccs_rtl.output_port_vld(ccs_rtl_SIG_output_port_vld);
   ccs_rtl.output_port_rdy(ccs_rtl_SIG_output_port_rdy);
   ccs_rtl.output_port_dat(ccs_rtl_SIG_output_port_dat);
   ccs_rtl.done_vld(ccs_rtl_SIG_done_vld);
   ccs_rtl.done_rdy(ccs_rtl_SIG_done_rdy);
   ccs_rtl.done_dat(ccs_rtl_SIG_done_dat);
   
   // Register processes
   SC_METHOD(update_proc);
   sensitive  << clk << rst << start.Connections::InBlocking_Ports_abs<bool >::vld << ccs_rtl_SIG_start_rdy << start.Connections::InBlocking<bool, Connections::SYN_PORT >::dat << act_port.Connections::InBlocking_Ports_abs<nvhls::nv_scvector<ac_int<16, true >, 16U > >::vld << ccs_rtl_SIG_act_port_rdy << act_port.Connections::InBlocking<nvhls::nv_scvector<ac_int<16, true >, 16U >, Connections::SYN_PORT >::dat << rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::vld << ccs_rtl_SIG_rva_in_rdy << rva_in.Connections::InBlocking<RVSink<spec::Axi::rvaCfg >::Write, Connections::SYN_PORT >::dat << ccs_rtl_SIG_rva_out_vld << rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::rdy << ccs_rtl_SIG_rva_out_dat << ccs_rtl_SIG_output_port_vld << output_port.Connections::OutBlocking_Ports_abs<spec::StreamType >::rdy << ccs_rtl_SIG_output_port_dat << ccs_rtl_SIG_done_vld << done.Connections::OutBlocking_Ports_abs<bool >::rdy << ccs_rtl_SIG_done_dat;
   // Other constructor statements
   SIG_SC_LOGIC_0.write(SC_LOGIC_0);
   SIG_SC_LOGIC_1.write(SC_LOGIC_1);
}

// ---------------------------------------------------------------
// Process: SC_METHOD update_proc

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   
   // none.sc_in field_key=clk:57dbe8e5-de9e-42de-82c4-3ce406756520-2692:clk:57dbe8e5-de9e-42de-82c4-3ce406756520-2692
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2692; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:57dbe8e5-de9e-42de-82c4-3ce406756520-2693:rst:57dbe8e5-de9e-42de-82c4-3ce406756520-2693
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2693; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_57dbe8e5_de9e_42de_82c4_3ce406756520_2693); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2693); // then write to RTL port
   
   // none.sc_in field_key=start:57dbe8e5-de9e-42de-82c4-3ce406756520-2699:vld:57dbe8e5-de9e-42de-82c4-3ce406756520-2710
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2710; // NPS - LV to hold field
   type_to_vector(start.Connections::InBlocking_Ports_abs<bool >::vld.read(),1,t_57dbe8e5_de9e_42de_82c4_3ce406756520_2710); // read orig port and type convert
   ccs_rtl_SIG_start_vld.write(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2710); // then write to RTL port
   
   // none.sc_out field_key=start:57dbe8e5-de9e-42de-82c4-3ce406756520-2699:rdy:57dbe8e5-de9e-42de-82c4-3ce406756520-2711
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2711;
   bool d_57dbe8e5_de9e_42de_82c4_3ce406756520_2711;
   t_57dbe8e5_de9e_42de_82c4_3ce406756520_2711 = ccs_rtl_SIG_start_rdy.read();
   vector_to_type(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2711, 1, &d_57dbe8e5_de9e_42de_82c4_3ce406756520_2711);
   start.Connections::InBlocking_Ports_abs<bool >::rdy.write(d_57dbe8e5_de9e_42de_82c4_3ce406756520_2711);
   
   // none.sc_in field_key=start:57dbe8e5-de9e-42de-82c4-3ce406756520-2699:dat:57dbe8e5-de9e-42de-82c4-3ce406756520-2712
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2712; // NPS - LV to hold field
   type_to_vector(start.Connections::InBlocking<bool, Connections::SYN_PORT >::dat.read(),1,t_57dbe8e5_de9e_42de_82c4_3ce406756520_2712); // read orig port and type convert
   ccs_rtl_SIG_start_dat.write(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2712); // then write to RTL port
   
   // none.sc_in field_key=act_port:57dbe8e5-de9e-42de-82c4-3ce406756520-2713:vld:57dbe8e5-de9e-42de-82c4-3ce406756520-2722
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2722; // NPS - LV to hold field
   type_to_vector(act_port.Connections::InBlocking_Ports_abs<nvhls::nv_scvector<ac_int<16, true >, 16U > >::vld.read(),1,t_57dbe8e5_de9e_42de_82c4_3ce406756520_2722); // read orig port and type convert
   ccs_rtl_SIG_act_port_vld.write(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2722); // then write to RTL port
   
   // none.sc_out field_key=act_port:57dbe8e5-de9e-42de-82c4-3ce406756520-2713:rdy:57dbe8e5-de9e-42de-82c4-3ce406756520-2723
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2723;
   bool d_57dbe8e5_de9e_42de_82c4_3ce406756520_2723;
   t_57dbe8e5_de9e_42de_82c4_3ce406756520_2723 = ccs_rtl_SIG_act_port_rdy.read();
   vector_to_type(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2723, 1, &d_57dbe8e5_de9e_42de_82c4_3ce406756520_2723);
   act_port.Connections::InBlocking_Ports_abs<nvhls::nv_scvector<ac_int<16, true >, 16U > >::rdy.write(d_57dbe8e5_de9e_42de_82c4_3ce406756520_2723);
   
   // none.sc_in field_key=act_port:57dbe8e5-de9e-42de-82c4-3ce406756520-2713:dat:57dbe8e5-de9e-42de-82c4-3ce406756520-2724
   sc_lv< 256 > t_57dbe8e5_de9e_42de_82c4_3ce406756520_2724; // NPS - LV to hold field
   type_to_vector(act_port.Connections::InBlocking<nvhls::nv_scvector<ac_int<16, true >, 16U >, Connections::SYN_PORT >::dat.read(),256,t_57dbe8e5_de9e_42de_82c4_3ce406756520_2724); // read orig port and type convert
   ccs_rtl_SIG_act_port_dat.write(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2724); // then write to RTL port
   
   // none.sc_in field_key=rva_in:57dbe8e5-de9e-42de-82c4-3ce406756520-2725:vld:57dbe8e5-de9e-42de-82c4-3ce406756520-2734
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2734; // NPS - LV to hold field
   type_to_vector(rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::vld.read(),1,t_57dbe8e5_de9e_42de_82c4_3ce406756520_2734); // read orig port and type convert
   ccs_rtl_SIG_rva_in_vld.write(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2734); // then write to RTL port
   
   // none.sc_out field_key=rva_in:57dbe8e5-de9e-42de-82c4-3ce406756520-2725:rdy:57dbe8e5-de9e-42de-82c4-3ce406756520-2735
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2735;
   bool d_57dbe8e5_de9e_42de_82c4_3ce406756520_2735;
   t_57dbe8e5_de9e_42de_82c4_3ce406756520_2735 = ccs_rtl_SIG_rva_in_rdy.read();
   vector_to_type(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2735, 1, &d_57dbe8e5_de9e_42de_82c4_3ce406756520_2735);
   rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::rdy.write(d_57dbe8e5_de9e_42de_82c4_3ce406756520_2735);
   
   // none.sc_in field_key=rva_in:57dbe8e5-de9e-42de-82c4-3ce406756520-2725:dat:57dbe8e5-de9e-42de-82c4-3ce406756520-2736
   sc_lv< 169 > t_57dbe8e5_de9e_42de_82c4_3ce406756520_2736; // NPS - LV to hold field
   type_to_vector(rva_in.Connections::InBlocking<RVSink<spec::Axi::rvaCfg >::Write, Connections::SYN_PORT >::dat.read(),169,t_57dbe8e5_de9e_42de_82c4_3ce406756520_2736); // read orig port and type convert
   ccs_rtl_SIG_rva_in_dat.write(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2736); // then write to RTL port
   
   // none.sc_out field_key=rva_out:57dbe8e5-de9e-42de-82c4-3ce406756520-2737:vld:57dbe8e5-de9e-42de-82c4-3ce406756520-2746
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2746;
   bool d_57dbe8e5_de9e_42de_82c4_3ce406756520_2746;
   t_57dbe8e5_de9e_42de_82c4_3ce406756520_2746 = ccs_rtl_SIG_rva_out_vld.read();
   vector_to_type(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2746, 1, &d_57dbe8e5_de9e_42de_82c4_3ce406756520_2746);
   rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::vld.write(d_57dbe8e5_de9e_42de_82c4_3ce406756520_2746);
   
   // none.sc_in field_key=rva_out:57dbe8e5-de9e-42de-82c4-3ce406756520-2737:rdy:57dbe8e5-de9e-42de-82c4-3ce406756520-2747
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2747; // NPS - LV to hold field
   type_to_vector(rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::rdy.read(),1,t_57dbe8e5_de9e_42de_82c4_3ce406756520_2747); // read orig port and type convert
   ccs_rtl_SIG_rva_out_rdy.write(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2747); // then write to RTL port
   
   // none.sc_out field_key=rva_out:57dbe8e5-de9e-42de-82c4-3ce406756520-2737:dat:57dbe8e5-de9e-42de-82c4-3ce406756520-2748
   sc_lv< 128 > t_57dbe8e5_de9e_42de_82c4_3ce406756520_2748;
   sc_dt::sc_lv<128 > d_57dbe8e5_de9e_42de_82c4_3ce406756520_2748;
   t_57dbe8e5_de9e_42de_82c4_3ce406756520_2748 = ccs_rtl_SIG_rva_out_dat.read();
   vector_to_type(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2748, 128, &d_57dbe8e5_de9e_42de_82c4_3ce406756520_2748);
   rva_out.Connections::OutBlocking<RVSink<spec::Axi::rvaCfg >::Read, Connections::SYN_PORT >::dat.write(d_57dbe8e5_de9e_42de_82c4_3ce406756520_2748);
   
   // none.sc_out field_key=output_port:57dbe8e5-de9e-42de-82c4-3ce406756520-2749:vld:57dbe8e5-de9e-42de-82c4-3ce406756520-2758
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2758;
   bool d_57dbe8e5_de9e_42de_82c4_3ce406756520_2758;
   t_57dbe8e5_de9e_42de_82c4_3ce406756520_2758 = ccs_rtl_SIG_output_port_vld.read();
   vector_to_type(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2758, 1, &d_57dbe8e5_de9e_42de_82c4_3ce406756520_2758);
   output_port.Connections::OutBlocking_Ports_abs<spec::StreamType >::vld.write(d_57dbe8e5_de9e_42de_82c4_3ce406756520_2758);
   
   // none.sc_in field_key=output_port:57dbe8e5-de9e-42de-82c4-3ce406756520-2749:rdy:57dbe8e5-de9e-42de-82c4-3ce406756520-2759
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2759; // NPS - LV to hold field
   type_to_vector(output_port.Connections::OutBlocking_Ports_abs<spec::StreamType >::rdy.read(),1,t_57dbe8e5_de9e_42de_82c4_3ce406756520_2759); // read orig port and type convert
   ccs_rtl_SIG_output_port_rdy.write(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2759); // then write to RTL port
   
   // none.sc_out field_key=output_port:57dbe8e5-de9e-42de-82c4-3ce406756520-2749:dat:57dbe8e5-de9e-42de-82c4-3ce406756520-2760
   sc_lv< 138 > t_57dbe8e5_de9e_42de_82c4_3ce406756520_2760;
   sc_dt::sc_lv<138 > d_57dbe8e5_de9e_42de_82c4_3ce406756520_2760;
   t_57dbe8e5_de9e_42de_82c4_3ce406756520_2760 = ccs_rtl_SIG_output_port_dat.read();
   vector_to_type(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2760, 138, &d_57dbe8e5_de9e_42de_82c4_3ce406756520_2760);
   output_port.Connections::OutBlocking<spec::StreamType, Connections::SYN_PORT >::dat.write(d_57dbe8e5_de9e_42de_82c4_3ce406756520_2760);
   
   // none.sc_out field_key=done:57dbe8e5-de9e-42de-82c4-3ce406756520-2761:vld:57dbe8e5-de9e-42de-82c4-3ce406756520-2770
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2770;
   bool d_57dbe8e5_de9e_42de_82c4_3ce406756520_2770;
   t_57dbe8e5_de9e_42de_82c4_3ce406756520_2770 = ccs_rtl_SIG_done_vld.read();
   vector_to_type(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2770, 1, &d_57dbe8e5_de9e_42de_82c4_3ce406756520_2770);
   done.Connections::OutBlocking_Ports_abs<bool >::vld.write(d_57dbe8e5_de9e_42de_82c4_3ce406756520_2770);
   
   // none.sc_in field_key=done:57dbe8e5-de9e-42de-82c4-3ce406756520-2761:rdy:57dbe8e5-de9e-42de-82c4-3ce406756520-2771
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2771; // NPS - LV to hold field
   type_to_vector(done.Connections::OutBlocking_Ports_abs<bool >::rdy.read(),1,t_57dbe8e5_de9e_42de_82c4_3ce406756520_2771); // read orig port and type convert
   ccs_rtl_SIG_done_rdy.write(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2771); // then write to RTL port
   
   // none.sc_out field_key=done:57dbe8e5-de9e-42de-82c4-3ce406756520-2761:dat:57dbe8e5-de9e-42de-82c4-3ce406756520-2772
   sc_logic t_57dbe8e5_de9e_42de_82c4_3ce406756520_2772;
   sc_dt::sc_lv<1 > d_57dbe8e5_de9e_42de_82c4_3ce406756520_2772;
   t_57dbe8e5_de9e_42de_82c4_3ce406756520_2772 = ccs_rtl_SIG_done_dat.read();
   vector_to_type(t_57dbe8e5_de9e_42de_82c4_3ce406756520_2772, 1, &d_57dbe8e5_de9e_42de_82c4_3ce406756520_2772);
   done.Connections::OutBlocking<bool, Connections::SYN_PORT >::dat.write(d_57dbe8e5_de9e_42de_82c4_3ce406756520_2772);
}
