// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2_1/1143609 Production Release
//  HLS Date:       Wed Nov 13 18:57:31 PST 2024
//
//  Generated by:   code@iron-05
//  Generated date: Wed Mar 18 19:01:34 2026
// ----------------------------------------------------------------------

//
// ------------------------------------------------------------------
//  Design Unit:    Connections_OutBlockingless_axi_axi4less_spec_Axi_axiCfggreater_ReadPayloadcomma_Connections_SYN_PORTgreater_Push_Connections_OutBlocking_axi_axi4_spec_Axi_axiCfg_ReadPayload_Connections_SYN_PORT_Push_core
// ------------------------------------------------------------------


module PEPartition_Connections_OutBlockingless_axi_axi4less_spec_Axi_axiCfggreater_ReadPayloadcomma_Connections_SYN_PORTgreater_Push_Connections_OutBlocking_axi_axi4_spec_Axi_axiCfg_ReadPayload_Connections_SYN_PORT_Push_core
    (
  this_vld, this_rdy, this_dat, m_id_rsc_dat, m_data_rsc_dat, m_last_rsc_dat, ccs_ccore_start_rsc_dat,
      ccs_ccore_done_sync_vld, ccs_MIO_clk, ccs_MIO_arst
);
  output this_vld;
  reg this_vld;
  input this_rdy;
  output [140:0] this_dat;
  input [9:0] m_id_rsc_dat;
  input [127:0] m_data_rsc_dat;
  input m_last_rsc_dat;
  input ccs_ccore_start_rsc_dat;
  output ccs_ccore_done_sync_vld;
  input ccs_MIO_clk;
  input ccs_MIO_arst;


  // Interconnect Declarations
  wire [9:0] m_id_rsci_idat;
  wire [127:0] m_data_rsci_idat;
  wire m_last_rsci_idat;
  wire ccs_ccore_start_rsci_idat;
  reg m_last_buf_lpi_1_dfm;
  reg [127:0] m_data_buf_lpi_1_dfm;
  reg [9:0] m_id_buf_lpi_1_dfm;
  wire and_dcpl;
  wire or_dcpl_2;
  reg io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1;
  wire or_4_cse;
  wire this_vld_mx0c1;


  // Interconnect Declarations for Component Instantiations
  wire  nl_ccs_ccore_done_synci_ivld;
  assign nl_ccs_ccore_done_synci_ivld = io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1
      & this_rdy;
  PEPartition_Connections_OutBlockingless_axi_axi4less_spec_Axi_axiCfggreater_ReadPayloadcomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd235),
  .width(32'sd10)) m_id_rsci (
      .dat(m_id_rsc_dat),
      .idat(m_id_rsci_idat)
    );
  PEPartition_Connections_OutBlockingless_axi_axi4less_spec_Axi_axiCfggreater_ReadPayloadcomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd236),
  .width(32'sd128)) m_data_rsci (
      .dat(m_data_rsc_dat),
      .idat(m_data_rsci_idat)
    );
  PEPartition_Connections_OutBlockingless_axi_axi4less_spec_Axi_axiCfggreater_ReadPayloadcomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd238),
  .width(32'sd1)) m_last_rsci (
      .dat(m_last_rsc_dat),
      .idat(m_last_rsci_idat)
    );
  PEPartition_Connections_OutBlockingless_axi_axi4less_spec_Axi_axiCfggreater_ReadPayloadcomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd257),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  PEPartition_Connections_OutBlockingless_axi_axi4less_spec_Axi_axiCfggreater_ReadPayloadcomma_Connections_SYN_PORTgreater_Push_ccs_sync_out_vld_v1
      #(.rscid(32'sd262)) ccs_ccore_done_synci (
      .vld(ccs_ccore_done_sync_vld),
      .ivld(nl_ccs_ccore_done_synci_ivld)
    );
  assign this_dat = {m_last_buf_lpi_1_dfm , 2'b00 , m_data_buf_lpi_1_dfm , m_id_buf_lpi_1_dfm};
  assign or_4_cse = ccs_ccore_start_rsci_idat | and_dcpl;
  assign and_dcpl = io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 & (~ this_rdy);
  assign or_dcpl_2 = and_dcpl | (~ ccs_ccore_start_rsci_idat);
  assign this_vld_mx0c1 = io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 & this_rdy
      & (~ ccs_ccore_start_rsci_idat);
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      this_vld <= 1'b0;
    end
    else if ( or_4_cse | this_vld_mx0c1 ) begin
      this_vld <= ~ this_vld_mx0c1;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      m_last_buf_lpi_1_dfm <= 1'b0;
    end
    else if ( ~ or_dcpl_2 ) begin
      m_last_buf_lpi_1_dfm <= m_last_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      m_data_buf_lpi_1_dfm <= 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    end
    else if ( ~ or_dcpl_2 ) begin
      m_data_buf_lpi_1_dfm <= m_data_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      m_id_buf_lpi_1_dfm <= 10'b0000000000;
    end
    else if ( ~ or_dcpl_2 ) begin
      m_id_buf_lpi_1_dfm <= m_id_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 <= 1'b0;
    end
    else begin
      io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 <= or_4_cse;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    Connections_OutBlocking_axi_axi4_spec_Axi_axiCfg_ReadPayload_Connections_SYN_PORT_Push
// ------------------------------------------------------------------


module PEPartition_Connections_OutBlocking_axi_axi4_spec_Axi_axiCfg_ReadPayload_Connections_SYN_PORT_Push
    (
  this_vld, this_rdy, this_dat, m_id_rsc_dat, m_data_rsc_dat, m_last_rsc_dat, ccs_ccore_start_rsc_dat,
      ccs_ccore_done_sync_vld, ccs_MIO_clk, ccs_MIO_arst
);
  output this_vld;
  input this_rdy;
  output [140:0] this_dat;
  input [9:0] m_id_rsc_dat;
  input [127:0] m_data_rsc_dat;
  input m_last_rsc_dat;
  input ccs_ccore_start_rsc_dat;
  output ccs_ccore_done_sync_vld;
  input ccs_MIO_clk;
  input ccs_MIO_arst;



  // Interconnect Declarations for Component Instantiations
  PEPartition_Connections_OutBlockingless_axi_axi4less_spec_Axi_axiCfggreater_ReadPayloadcomma_Connections_SYN_PORTgreater_Push_Connections_OutBlocking_axi_axi4_spec_Axi_axiCfg_ReadPayload_Connections_SYN_PORT_Push_core
      Connections_OutBlocking_axi_axi4_spec_Axi_axiCfg_ReadPayload_Connections_SYN_PORT_Push_core_inst
      (
      .this_vld(this_vld),
      .this_rdy(this_rdy),
      .this_dat(this_dat),
      .m_id_rsc_dat(m_id_rsc_dat),
      .m_data_rsc_dat(m_data_rsc_dat),
      .m_last_rsc_dat(m_last_rsc_dat),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_ccore_done_sync_vld(ccs_ccore_done_sync_vld),
      .ccs_MIO_clk(ccs_MIO_clk),
      .ccs_MIO_arst(ccs_MIO_arst)
    );
endmodule



