// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2024.2_1/1143609 Production Release
//       HLS date: Wed Nov 13 18:57:31 PST 2024
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: code@iron-05
// Generated date: Wed Mar 18 19:14:06 PDT 2026
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model GBCore
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Constructor: sysc_sim_wrapper

CCS_RTL::sysc_sim_wrapper::sysc_sim_wrapper(
   const sc_module_name& nm
)
   : ccs_rtl(
      "ccs_rtl",
      "ccs_wrapper"
   )
   , clk("clk")
   , rst("rst")
   , rva_in_large("rva_in_large")
   , rva_out_large("rva_out_large")
   , nmp_large_req("nmp_large_req")
   , nmp_large_rsp("nmp_large_rsp")
   , gbcontrol_large_req("gbcontrol_large_req")
   , gbcontrol_large_rsp("gbcontrol_large_rsp")
   , SC_SRAM_CONFIG("SC_SRAM_CONFIG")
   , ccs_rtl_SIG_clk("ccs_rtl_SIG_clk")
   , ccs_rtl_SIG_rst("ccs_rtl_SIG_rst")
   , ccs_rtl_SIG_rva_in_large_vld("ccs_rtl_SIG_rva_in_large_vld")
   , ccs_rtl_SIG_rva_in_large_rdy("ccs_rtl_SIG_rva_in_large_rdy")
   , ccs_rtl_SIG_rva_in_large_dat("ccs_rtl_SIG_rva_in_large_dat")
   , ccs_rtl_SIG_rva_out_large_vld("ccs_rtl_SIG_rva_out_large_vld")
   , ccs_rtl_SIG_rva_out_large_rdy("ccs_rtl_SIG_rva_out_large_rdy")
   , ccs_rtl_SIG_rva_out_large_dat("ccs_rtl_SIG_rva_out_large_dat")
   , ccs_rtl_SIG_nmp_large_req_vld("ccs_rtl_SIG_nmp_large_req_vld")
   , ccs_rtl_SIG_nmp_large_req_rdy("ccs_rtl_SIG_nmp_large_req_rdy")
   , ccs_rtl_SIG_nmp_large_req_dat("ccs_rtl_SIG_nmp_large_req_dat")
   , ccs_rtl_SIG_nmp_large_rsp_vld("ccs_rtl_SIG_nmp_large_rsp_vld")
   , ccs_rtl_SIG_nmp_large_rsp_rdy("ccs_rtl_SIG_nmp_large_rsp_rdy")
   , ccs_rtl_SIG_nmp_large_rsp_dat("ccs_rtl_SIG_nmp_large_rsp_dat")
   , ccs_rtl_SIG_gbcontrol_large_req_vld("ccs_rtl_SIG_gbcontrol_large_req_vld")
   , ccs_rtl_SIG_gbcontrol_large_req_rdy("ccs_rtl_SIG_gbcontrol_large_req_rdy")
   , ccs_rtl_SIG_gbcontrol_large_req_dat("ccs_rtl_SIG_gbcontrol_large_req_dat")
   , ccs_rtl_SIG_gbcontrol_large_rsp_vld("ccs_rtl_SIG_gbcontrol_large_rsp_vld")
   , ccs_rtl_SIG_gbcontrol_large_rsp_rdy("ccs_rtl_SIG_gbcontrol_large_rsp_rdy")
   , ccs_rtl_SIG_gbcontrol_large_rsp_dat("ccs_rtl_SIG_gbcontrol_large_rsp_dat")
   , ccs_rtl_SIG_SC_SRAM_CONFIG("ccs_rtl_SIG_SC_SRAM_CONFIG")
   , SIG_SC_LOGIC_0("SIG_SC_LOGIC_0")
   , SIG_SC_LOGIC_1("SIG_SC_LOGIC_1")
{
   // Instantiate other modules
   ccs_rtl.clk(ccs_rtl_SIG_clk);
   ccs_rtl.rst(ccs_rtl_SIG_rst);
   ccs_rtl.rva_in_large_vld(ccs_rtl_SIG_rva_in_large_vld);
   ccs_rtl.rva_in_large_rdy(ccs_rtl_SIG_rva_in_large_rdy);
   ccs_rtl.rva_in_large_dat(ccs_rtl_SIG_rva_in_large_dat);
   ccs_rtl.rva_out_large_vld(ccs_rtl_SIG_rva_out_large_vld);
   ccs_rtl.rva_out_large_rdy(ccs_rtl_SIG_rva_out_large_rdy);
   ccs_rtl.rva_out_large_dat(ccs_rtl_SIG_rva_out_large_dat);
   ccs_rtl.nmp_large_req_vld(ccs_rtl_SIG_nmp_large_req_vld);
   ccs_rtl.nmp_large_req_rdy(ccs_rtl_SIG_nmp_large_req_rdy);
   ccs_rtl.nmp_large_req_dat(ccs_rtl_SIG_nmp_large_req_dat);
   ccs_rtl.nmp_large_rsp_vld(ccs_rtl_SIG_nmp_large_rsp_vld);
   ccs_rtl.nmp_large_rsp_rdy(ccs_rtl_SIG_nmp_large_rsp_rdy);
   ccs_rtl.nmp_large_rsp_dat(ccs_rtl_SIG_nmp_large_rsp_dat);
   ccs_rtl.gbcontrol_large_req_vld(ccs_rtl_SIG_gbcontrol_large_req_vld);
   ccs_rtl.gbcontrol_large_req_rdy(ccs_rtl_SIG_gbcontrol_large_req_rdy);
   ccs_rtl.gbcontrol_large_req_dat(ccs_rtl_SIG_gbcontrol_large_req_dat);
   ccs_rtl.gbcontrol_large_rsp_vld(ccs_rtl_SIG_gbcontrol_large_rsp_vld);
   ccs_rtl.gbcontrol_large_rsp_rdy(ccs_rtl_SIG_gbcontrol_large_rsp_rdy);
   ccs_rtl.gbcontrol_large_rsp_dat(ccs_rtl_SIG_gbcontrol_large_rsp_dat);
   ccs_rtl.SC_SRAM_CONFIG(ccs_rtl_SIG_SC_SRAM_CONFIG);
   
   // Register processes
   SC_METHOD(update_proc);
   sensitive  << clk << rst << rva_in_large.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::vld << ccs_rtl_SIG_rva_in_large_rdy << rva_in_large.Connections::InBlocking<RVSink<spec::Axi::rvaCfg >::Write, Connections::SYN_PORT >::dat << ccs_rtl_SIG_rva_out_large_vld << rva_out_large.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::rdy << ccs_rtl_SIG_rva_out_large_dat << nmp_large_req.Connections::InBlocking_Ports_abs<spec::GB::Large::DataReq >::vld << ccs_rtl_SIG_nmp_large_req_rdy << nmp_large_req.Connections::InBlocking<spec::GB::Large::DataReq, Connections::SYN_PORT >::dat << ccs_rtl_SIG_nmp_large_rsp_vld << nmp_large_rsp.Connections::OutBlocking_Ports_abs<spec::GB::Large::DataRsp<1U > >::rdy << ccs_rtl_SIG_nmp_large_rsp_dat << gbcontrol_large_req.Connections::InBlocking_Ports_abs<spec::GB::Large::DataReq >::vld << ccs_rtl_SIG_gbcontrol_large_req_rdy << gbcontrol_large_req.Connections::InBlocking<spec::GB::Large::DataReq, Connections::SYN_PORT >::dat << ccs_rtl_SIG_gbcontrol_large_rsp_vld << gbcontrol_large_rsp.Connections::OutBlocking_Ports_abs<spec::GB::Large::DataRsp<1U > >::rdy << ccs_rtl_SIG_gbcontrol_large_rsp_dat << SC_SRAM_CONFIG;
   // Other constructor statements
   SIG_SC_LOGIC_0.write(SC_LOGIC_0);
   SIG_SC_LOGIC_1.write(SC_LOGIC_1);
}

// ---------------------------------------------------------------
// Process: SC_METHOD update_proc

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   
   // none.sc_in field_key=clk:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1627:clk:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1627
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1627; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1628:rst:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1628
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1628; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1628); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1628); // then write to RTL port
   
   // none.sc_in field_key=rva_in_large:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1814:vld:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1825
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1825; // NPS - LV to hold field
   type_to_vector(rva_in_large.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::vld.read(),1,t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1825); // read orig port and type convert
   ccs_rtl_SIG_rva_in_large_vld.write(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1825); // then write to RTL port
   
   // none.sc_out field_key=rva_in_large:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1814:rdy:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1826
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1826;
   bool d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1826;
   t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1826 = ccs_rtl_SIG_rva_in_large_rdy.read();
   vector_to_type(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1826, 1, &d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1826);
   rva_in_large.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::rdy.write(d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1826);
   
   // none.sc_in field_key=rva_in_large:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1814:dat:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1827
   sc_lv< 169 > t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1827; // NPS - LV to hold field
   type_to_vector(rva_in_large.Connections::InBlocking<RVSink<spec::Axi::rvaCfg >::Write, Connections::SYN_PORT >::dat.read(),169,t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1827); // read orig port and type convert
   ccs_rtl_SIG_rva_in_large_dat.write(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1827); // then write to RTL port
   
   // none.sc_out field_key=rva_out_large:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1828:vld:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1837
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1837;
   bool d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1837;
   t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1837 = ccs_rtl_SIG_rva_out_large_vld.read();
   vector_to_type(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1837, 1, &d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1837);
   rva_out_large.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::vld.write(d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1837);
   
   // none.sc_in field_key=rva_out_large:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1828:rdy:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1838
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1838; // NPS - LV to hold field
   type_to_vector(rva_out_large.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::rdy.read(),1,t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1838); // read orig port and type convert
   ccs_rtl_SIG_rva_out_large_rdy.write(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1838); // then write to RTL port
   
   // none.sc_out field_key=rva_out_large:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1828:dat:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1839
   sc_lv< 128 > t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1839;
   sc_dt::sc_lv<128 > d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1839;
   t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1839 = ccs_rtl_SIG_rva_out_large_dat.read();
   vector_to_type(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1839, 128, &d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1839);
   rva_out_large.Connections::OutBlocking<RVSink<spec::Axi::rvaCfg >::Read, Connections::SYN_PORT >::dat.write(d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1839);
   
   // none.sc_in field_key=nmp_large_req:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1840:vld:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1849
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1849; // NPS - LV to hold field
   type_to_vector(nmp_large_req.Connections::InBlocking_Ports_abs<spec::GB::Large::DataReq >::vld.read(),1,t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1849); // read orig port and type convert
   ccs_rtl_SIG_nmp_large_req_vld.write(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1849); // then write to RTL port
   
   // none.sc_out field_key=nmp_large_req:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1840:rdy:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1850
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1850;
   bool d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1850;
   t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1850 = ccs_rtl_SIG_nmp_large_req_rdy.read();
   vector_to_type(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1850, 1, &d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1850);
   nmp_large_req.Connections::InBlocking_Ports_abs<spec::GB::Large::DataReq >::rdy.write(d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1850);
   
   // none.sc_in field_key=nmp_large_req:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1840:dat:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1851
   sc_lv< 155 > t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1851; // NPS - LV to hold field
   type_to_vector(nmp_large_req.Connections::InBlocking<spec::GB::Large::DataReq, Connections::SYN_PORT >::dat.read(),155,t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1851); // read orig port and type convert
   ccs_rtl_SIG_nmp_large_req_dat.write(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1851); // then write to RTL port
   
   // none.sc_out field_key=nmp_large_rsp:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1852:vld:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1861
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1861;
   bool d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1861;
   t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1861 = ccs_rtl_SIG_nmp_large_rsp_vld.read();
   vector_to_type(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1861, 1, &d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1861);
   nmp_large_rsp.Connections::OutBlocking_Ports_abs<spec::GB::Large::DataRsp<1U > >::vld.write(d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1861);
   
   // none.sc_in field_key=nmp_large_rsp:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1852:rdy:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1862
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1862; // NPS - LV to hold field
   type_to_vector(nmp_large_rsp.Connections::OutBlocking_Ports_abs<spec::GB::Large::DataRsp<1U > >::rdy.read(),1,t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1862); // read orig port and type convert
   ccs_rtl_SIG_nmp_large_rsp_rdy.write(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1862); // then write to RTL port
   
   // none.sc_out field_key=nmp_large_rsp:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1852:dat:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1863
   sc_lv< 128 > t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1863;
   sc_dt::sc_lv<128 > d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1863;
   if ( ccs_rtl_SIG_nmp_large_rsp_vld.read() == SC_LOGIC_1 ) {
      t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1863 = ccs_rtl_SIG_nmp_large_rsp_dat.read();
      vector_to_type(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1863, 128, &d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1863);
      nmp_large_rsp.Connections::OutBlocking<spec::GB::Large::DataRsp<1U >, Connections::SYN_PORT >::dat.write(d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1863);
   }
   
   // none.sc_in field_key=gbcontrol_large_req:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1864:vld:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1869
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1869; // NPS - LV to hold field
   type_to_vector(gbcontrol_large_req.Connections::InBlocking_Ports_abs<spec::GB::Large::DataReq >::vld.read(),1,t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1869); // read orig port and type convert
   ccs_rtl_SIG_gbcontrol_large_req_vld.write(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1869); // then write to RTL port
   
   // none.sc_out field_key=gbcontrol_large_req:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1864:rdy:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1870
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1870;
   bool d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1870;
   t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1870 = ccs_rtl_SIG_gbcontrol_large_req_rdy.read();
   vector_to_type(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1870, 1, &d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1870);
   gbcontrol_large_req.Connections::InBlocking_Ports_abs<spec::GB::Large::DataReq >::rdy.write(d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1870);
   
   // none.sc_in field_key=gbcontrol_large_req:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1864:dat:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1871
   sc_lv< 155 > t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1871; // NPS - LV to hold field
   type_to_vector(gbcontrol_large_req.Connections::InBlocking<spec::GB::Large::DataReq, Connections::SYN_PORT >::dat.read(),155,t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1871); // read orig port and type convert
   ccs_rtl_SIG_gbcontrol_large_req_dat.write(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1871); // then write to RTL port
   
   // none.sc_out field_key=gbcontrol_large_rsp:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1872:vld:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1877
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1877;
   bool d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1877;
   t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1877 = ccs_rtl_SIG_gbcontrol_large_rsp_vld.read();
   vector_to_type(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1877, 1, &d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1877);
   gbcontrol_large_rsp.Connections::OutBlocking_Ports_abs<spec::GB::Large::DataRsp<1U > >::vld.write(d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1877);
   
   // none.sc_in field_key=gbcontrol_large_rsp:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1872:rdy:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1878
   sc_logic t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1878; // NPS - LV to hold field
   type_to_vector(gbcontrol_large_rsp.Connections::OutBlocking_Ports_abs<spec::GB::Large::DataRsp<1U > >::rdy.read(),1,t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1878); // read orig port and type convert
   ccs_rtl_SIG_gbcontrol_large_rsp_rdy.write(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1878); // then write to RTL port
   
   // none.sc_out field_key=gbcontrol_large_rsp:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1872:dat:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1879
   sc_lv< 128 > t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1879;
   sc_dt::sc_lv<128 > d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1879;
   if ( ccs_rtl_SIG_gbcontrol_large_rsp_vld.read() == SC_LOGIC_1 ) {
      t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1879 = ccs_rtl_SIG_gbcontrol_large_rsp_dat.read();
      vector_to_type(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1879, 128, &d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1879);
      gbcontrol_large_rsp.Connections::OutBlocking<spec::GB::Large::DataRsp<1U >, Connections::SYN_PORT >::dat.write(d_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1879);
   }
   
   // none.sc_in field_key=SC_SRAM_CONFIG:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1880:SC_SRAM_CONFIG:1e850a6b-84af-4542-84e5-37b63dd6f1e6-1880
   sc_lv< 32 > t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1880; // NPS - LV to hold field
   type_to_vector(SC_SRAM_CONFIG.read(),32,t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1880); // read orig port and type convert
   ccs_rtl_SIG_SC_SRAM_CONFIG.write(t_1e850a6b_84af_4542_84e5_37b63dd6f1e6_1880); // then write to RTL port
}
