// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2_1/1143609 Production Release
//  HLS Date:       Wed Nov 13 18:57:31 PST 2024
// 
//  Generated by:   code@iron-05
//  Generated date: Wed Mar 18 18:52:20 2026
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun_RVAOutRun_fsm
//  FSM Module
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun_RVAOutRun_fsm (
  clk, rst, rva_out_Push_mioi_wen_comp, fsm_output
);
  input clk;
  input rst;
  input rva_out_Push_mioi_wen_comp;
  output fsm_output;
  reg fsm_output;


  // FSM State Type Declaration for PEModule_PERVA_RVAOutRun_RVAOutRun_fsm_1
  parameter
    RVAOutRun_rlp_C_0 = 1'd0,
    while_C_0 = 1'd1;

  reg  state_var;
  reg  state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : PEModule_PERVA_RVAOutRun_RVAOutRun_fsm_1
    case (state_var)
      while_C_0 : begin
        fsm_output = 1'b1;
        state_var_NS = while_C_0;
      end
      // RVAOutRun_rlp_C_0
      default : begin
        fsm_output = 1'b0;
        state_var_NS = while_C_0;
      end
    endcase
  end

  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      state_var <= RVAOutRun_rlp_C_0;
    end
    else if ( rva_out_Push_mioi_wen_comp ) begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun_staller_1
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun_staller_1 (
  clk, rst, RVAOutRun_wten, rva_out_Push_mioi_wen_comp, RVAOutRun_wten_pff
);
  input clk;
  input rst;
  output RVAOutRun_wten;
  input rva_out_Push_mioi_wen_comp;
  output RVAOutRun_wten_pff;


  // Interconnect Declarations
  reg RVAOutRun_wten_reg;


  // Interconnect Declarations for Component Instantiations 
  assign RVAOutRun_wten = RVAOutRun_wten_reg;
  assign RVAOutRun_wten_pff = ~ rva_out_Push_mioi_wen_comp;
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      RVAOutRun_wten_reg <= 1'b0;
    end
    else begin
      RVAOutRun_wten_reg <= ~ rva_out_Push_mioi_wen_comp;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun_rva_out_Push_mioi_rva_out_Push_mio_wait_dp
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun_rva_out_Push_mioi_rva_out_Push_mio_wait_dp (
  clk, rst, rva_out_Push_mioi_oswt, rva_out_Push_mioi_wen_comp, rva_out_Push_mioi_biwt,
      rva_out_Push_mioi_bdwt, rva_out_Push_mioi_bcwt
);
  input clk;
  input rst;
  input rva_out_Push_mioi_oswt;
  output rva_out_Push_mioi_wen_comp;
  input rva_out_Push_mioi_biwt;
  input rva_out_Push_mioi_bdwt;
  output rva_out_Push_mioi_bcwt;
  reg rva_out_Push_mioi_bcwt;



  // Interconnect Declarations for Component Instantiations 
  assign rva_out_Push_mioi_wen_comp = (~ rva_out_Push_mioi_oswt) | rva_out_Push_mioi_biwt
      | rva_out_Push_mioi_bcwt;
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      rva_out_Push_mioi_bcwt <= 1'b0;
    end
    else begin
      rva_out_Push_mioi_bcwt <= ~((~(rva_out_Push_mioi_bcwt | rva_out_Push_mioi_biwt))
          | rva_out_Push_mioi_bdwt);
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun_rva_out_Push_mioi_rva_out_Push_mio_wait_ctrl
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun_rva_out_Push_mioi_rva_out_Push_mio_wait_ctrl (
  RVAOutRun_wen, RVAOutRun_wten, rva_out_Push_mioi_oswt, rva_out_Push_mioi_biwt,
      rva_out_Push_mioi_bdwt, rva_out_Push_mioi_bcwt, rva_out_Push_mioi_ccs_ccore_start_rsc_dat_RVAOutRun_sct,
      rva_out_Push_mioi_ccs_ccore_done_sync_vld, rva_out_Push_mioi_oswt_pff
);
  input RVAOutRun_wen;
  input RVAOutRun_wten;
  input rva_out_Push_mioi_oswt;
  output rva_out_Push_mioi_biwt;
  output rva_out_Push_mioi_bdwt;
  input rva_out_Push_mioi_bcwt;
  output rva_out_Push_mioi_ccs_ccore_start_rsc_dat_RVAOutRun_sct;
  input rva_out_Push_mioi_ccs_ccore_done_sync_vld;
  input rva_out_Push_mioi_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign rva_out_Push_mioi_bdwt = rva_out_Push_mioi_oswt & RVAOutRun_wen;
  assign rva_out_Push_mioi_biwt = rva_out_Push_mioi_oswt & (~ rva_out_Push_mioi_bcwt)
      & rva_out_Push_mioi_ccs_ccore_done_sync_vld;
  assign rva_out_Push_mioi_ccs_ccore_start_rsc_dat_RVAOutRun_sct = (~ RVAOutRun_wten)
      & rva_out_Push_mioi_oswt_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun_act_rva_out_PopNB_mioi_act_rva_out_PopNB_mio_wait_dp
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun_act_rva_out_PopNB_mioi_act_rva_out_PopNB_mio_wait_dp
    (
  clk, rst, act_rva_out_PopNB_mioi_data_data_rsc_z_mxwt, act_rva_out_PopNB_mioi_return_rsc_z_mxwt,
      act_rva_out_PopNB_mioi_biwt, act_rva_out_PopNB_mioi_bdwt, act_rva_out_PopNB_mioi_data_data_rsc_z,
      act_rva_out_PopNB_mioi_return_rsc_z
);
  input clk;
  input rst;
  output [127:0] act_rva_out_PopNB_mioi_data_data_rsc_z_mxwt;
  output act_rva_out_PopNB_mioi_return_rsc_z_mxwt;
  input act_rva_out_PopNB_mioi_biwt;
  input act_rva_out_PopNB_mioi_bdwt;
  input [127:0] act_rva_out_PopNB_mioi_data_data_rsc_z;
  input act_rva_out_PopNB_mioi_return_rsc_z;


  // Interconnect Declarations
  reg act_rva_out_PopNB_mioi_bcwt;
  reg [127:0] act_rva_out_PopNB_mioi_data_data_rsc_z_bfwt;
  reg act_rva_out_PopNB_mioi_return_rsc_z_bfwt;


  // Interconnect Declarations for Component Instantiations 
  assign act_rva_out_PopNB_mioi_data_data_rsc_z_mxwt = MUX_v_128_2_2(act_rva_out_PopNB_mioi_data_data_rsc_z,
      act_rva_out_PopNB_mioi_data_data_rsc_z_bfwt, act_rva_out_PopNB_mioi_bcwt);
  assign act_rva_out_PopNB_mioi_return_rsc_z_mxwt = MUX_s_1_2_2(act_rva_out_PopNB_mioi_return_rsc_z,
      act_rva_out_PopNB_mioi_return_rsc_z_bfwt, act_rva_out_PopNB_mioi_bcwt);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      act_rva_out_PopNB_mioi_bcwt <= 1'b0;
    end
    else begin
      act_rva_out_PopNB_mioi_bcwt <= ~((~(act_rva_out_PopNB_mioi_bcwt | act_rva_out_PopNB_mioi_biwt))
          | act_rva_out_PopNB_mioi_bdwt);
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      act_rva_out_PopNB_mioi_data_data_rsc_z_bfwt <= 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
      act_rva_out_PopNB_mioi_return_rsc_z_bfwt <= 1'b0;
    end
    else if ( act_rva_out_PopNB_mioi_biwt ) begin
      act_rva_out_PopNB_mioi_data_data_rsc_z_bfwt <= act_rva_out_PopNB_mioi_data_data_rsc_z;
      act_rva_out_PopNB_mioi_return_rsc_z_bfwt <= act_rva_out_PopNB_mioi_return_rsc_z;
    end
  end

  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [127:0] MUX_v_128_2_2;
    input [127:0] input_0;
    input [127:0] input_1;
    input  sel;
    reg [127:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_128_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun_act_rva_out_PopNB_mioi_act_rva_out_PopNB_mio_wait_ctrl
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun_act_rva_out_PopNB_mioi_act_rva_out_PopNB_mio_wait_ctrl
    (
  RVAOutRun_wen, RVAOutRun_wten, act_rva_out_PopNB_mioi_oswt, act_rva_out_PopNB_mioi_biwt,
      act_rva_out_PopNB_mioi_bdwt, act_rva_out_PopNB_mioi_biwt_pff, RVAOutRun_wten_pff,
      act_rva_out_PopNB_mioi_oswt_pff
);
  input RVAOutRun_wen;
  input RVAOutRun_wten;
  input act_rva_out_PopNB_mioi_oswt;
  output act_rva_out_PopNB_mioi_biwt;
  output act_rva_out_PopNB_mioi_bdwt;
  output act_rva_out_PopNB_mioi_biwt_pff;
  input RVAOutRun_wten_pff;
  input act_rva_out_PopNB_mioi_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign act_rva_out_PopNB_mioi_bdwt = act_rva_out_PopNB_mioi_oswt & RVAOutRun_wen;
  assign act_rva_out_PopNB_mioi_biwt = (~ RVAOutRun_wten) & act_rva_out_PopNB_mioi_oswt;
  assign act_rva_out_PopNB_mioi_biwt_pff = (~ RVAOutRun_wten_pff) & act_rva_out_PopNB_mioi_oswt_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun_pe_rva_out_PopNB_mioi_pe_rva_out_PopNB_mio_wait_dp
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun_pe_rva_out_PopNB_mioi_pe_rva_out_PopNB_mio_wait_dp
    (
  clk, rst, pe_rva_out_PopNB_mioi_data_data_rsc_z_mxwt, pe_rva_out_PopNB_mioi_return_rsc_z_mxwt,
      pe_rva_out_PopNB_mioi_biwt, pe_rva_out_PopNB_mioi_bdwt, pe_rva_out_PopNB_mioi_data_data_rsc_z,
      pe_rva_out_PopNB_mioi_return_rsc_z
);
  input clk;
  input rst;
  output [127:0] pe_rva_out_PopNB_mioi_data_data_rsc_z_mxwt;
  output pe_rva_out_PopNB_mioi_return_rsc_z_mxwt;
  input pe_rva_out_PopNB_mioi_biwt;
  input pe_rva_out_PopNB_mioi_bdwt;
  input [127:0] pe_rva_out_PopNB_mioi_data_data_rsc_z;
  input pe_rva_out_PopNB_mioi_return_rsc_z;


  // Interconnect Declarations
  reg pe_rva_out_PopNB_mioi_bcwt;
  reg [127:0] pe_rva_out_PopNB_mioi_data_data_rsc_z_bfwt;
  reg pe_rva_out_PopNB_mioi_return_rsc_z_bfwt;


  // Interconnect Declarations for Component Instantiations 
  assign pe_rva_out_PopNB_mioi_data_data_rsc_z_mxwt = MUX_v_128_2_2(pe_rva_out_PopNB_mioi_data_data_rsc_z,
      pe_rva_out_PopNB_mioi_data_data_rsc_z_bfwt, pe_rva_out_PopNB_mioi_bcwt);
  assign pe_rva_out_PopNB_mioi_return_rsc_z_mxwt = MUX_s_1_2_2(pe_rva_out_PopNB_mioi_return_rsc_z,
      pe_rva_out_PopNB_mioi_return_rsc_z_bfwt, pe_rva_out_PopNB_mioi_bcwt);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      pe_rva_out_PopNB_mioi_bcwt <= 1'b0;
    end
    else begin
      pe_rva_out_PopNB_mioi_bcwt <= ~((~(pe_rva_out_PopNB_mioi_bcwt | pe_rva_out_PopNB_mioi_biwt))
          | pe_rva_out_PopNB_mioi_bdwt);
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      pe_rva_out_PopNB_mioi_data_data_rsc_z_bfwt <= 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
      pe_rva_out_PopNB_mioi_return_rsc_z_bfwt <= 1'b0;
    end
    else if ( pe_rva_out_PopNB_mioi_biwt ) begin
      pe_rva_out_PopNB_mioi_data_data_rsc_z_bfwt <= pe_rva_out_PopNB_mioi_data_data_rsc_z;
      pe_rva_out_PopNB_mioi_return_rsc_z_bfwt <= pe_rva_out_PopNB_mioi_return_rsc_z;
    end
  end

  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [127:0] MUX_v_128_2_2;
    input [127:0] input_0;
    input [127:0] input_1;
    input  sel;
    reg [127:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_128_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun_pe_rva_out_PopNB_mioi_pe_rva_out_PopNB_mio_wait_ctrl
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun_pe_rva_out_PopNB_mioi_pe_rva_out_PopNB_mio_wait_ctrl
    (
  RVAOutRun_wen, RVAOutRun_wten, pe_rva_out_PopNB_mioi_oswt, pe_rva_out_PopNB_mioi_biwt,
      pe_rva_out_PopNB_mioi_bdwt, pe_rva_out_PopNB_mioi_biwt_pff, RVAOutRun_wten_pff,
      pe_rva_out_PopNB_mioi_oswt_pff
);
  input RVAOutRun_wen;
  input RVAOutRun_wten;
  input pe_rva_out_PopNB_mioi_oswt;
  output pe_rva_out_PopNB_mioi_biwt;
  output pe_rva_out_PopNB_mioi_bdwt;
  output pe_rva_out_PopNB_mioi_biwt_pff;
  input RVAOutRun_wten_pff;
  input pe_rva_out_PopNB_mioi_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign pe_rva_out_PopNB_mioi_bdwt = pe_rva_out_PopNB_mioi_oswt & RVAOutRun_wen;
  assign pe_rva_out_PopNB_mioi_biwt = (~ RVAOutRun_wten) & pe_rva_out_PopNB_mioi_oswt;
  assign pe_rva_out_PopNB_mioi_biwt_pff = (~ RVAOutRun_wten_pff) & pe_rva_out_PopNB_mioi_oswt_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_RVAInRun_fsm
//  FSM Module
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_RVAInRun_fsm (
  clk, rst, RVAInRun_wen, fsm_output
);
  input clk;
  input rst;
  input RVAInRun_wen;
  output fsm_output;
  reg fsm_output;


  // FSM State Type Declaration for PEModule_PERVA_RVAInRun_RVAInRun_fsm_1
  parameter
    RVAInRun_rlp_C_0 = 1'd0,
    while_C_0 = 1'd1;

  reg  state_var;
  reg  state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : PEModule_PERVA_RVAInRun_RVAInRun_fsm_1
    case (state_var)
      while_C_0 : begin
        fsm_output = 1'b1;
        state_var_NS = while_C_0;
      end
      // RVAInRun_rlp_C_0
      default : begin
        fsm_output = 1'b0;
        state_var_NS = while_C_0;
      end
    endcase
  end

  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      state_var <= RVAInRun_rlp_C_0;
    end
    else if ( RVAInRun_wen ) begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_staller
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_staller (
  clk, rst, RVAInRun_wen, RVAInRun_wten, pe_rva_in_Push_mioi_wen_comp, act_rva_in_Push_mioi_wen_comp,
      pe_start_Push_mioi_wen_comp, act_start_Push_mioi_wen_comp
);
  input clk;
  input rst;
  output RVAInRun_wen;
  output RVAInRun_wten;
  input pe_rva_in_Push_mioi_wen_comp;
  input act_rva_in_Push_mioi_wen_comp;
  input pe_start_Push_mioi_wen_comp;
  input act_start_Push_mioi_wen_comp;


  // Interconnect Declarations
  reg RVAInRun_wten_reg;


  // Interconnect Declarations for Component Instantiations 
  assign RVAInRun_wen = pe_rva_in_Push_mioi_wen_comp & act_rva_in_Push_mioi_wen_comp
      & pe_start_Push_mioi_wen_comp & act_start_Push_mioi_wen_comp;
  assign RVAInRun_wten = RVAInRun_wten_reg;
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      RVAInRun_wten_reg <= 1'b0;
    end
    else begin
      RVAInRun_wten_reg <= ~ RVAInRun_wen;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_act_start_Push_mioi_act_start_Push_mio_wait_dp
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_act_start_Push_mioi_act_start_Push_mio_wait_dp (
  clk, rst, act_start_Push_mioi_oswt, act_start_Push_mioi_wen_comp, act_start_Push_mioi_biwt,
      act_start_Push_mioi_bdwt, act_start_Push_mioi_bcwt
);
  input clk;
  input rst;
  input act_start_Push_mioi_oswt;
  output act_start_Push_mioi_wen_comp;
  input act_start_Push_mioi_biwt;
  input act_start_Push_mioi_bdwt;
  output act_start_Push_mioi_bcwt;
  reg act_start_Push_mioi_bcwt;



  // Interconnect Declarations for Component Instantiations 
  assign act_start_Push_mioi_wen_comp = (~ act_start_Push_mioi_oswt) | act_start_Push_mioi_biwt
      | act_start_Push_mioi_bcwt;
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      act_start_Push_mioi_bcwt <= 1'b0;
    end
    else begin
      act_start_Push_mioi_bcwt <= ~((~(act_start_Push_mioi_bcwt | act_start_Push_mioi_biwt))
          | act_start_Push_mioi_bdwt);
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_act_start_Push_mioi_act_start_Push_mio_wait_ctrl
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_act_start_Push_mioi_act_start_Push_mio_wait_ctrl (
  RVAInRun_wen, act_start_Push_mioi_oswt, act_start_Push_mioi_biwt, act_start_Push_mioi_bdwt,
      act_start_Push_mioi_bcwt, act_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct,
      act_start_Push_mioi_ccs_ccore_done_sync_vld, act_start_Push_mioi_oswt_pff
);
  input RVAInRun_wen;
  input act_start_Push_mioi_oswt;
  output act_start_Push_mioi_biwt;
  output act_start_Push_mioi_bdwt;
  input act_start_Push_mioi_bcwt;
  output act_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct;
  input act_start_Push_mioi_ccs_ccore_done_sync_vld;
  input act_start_Push_mioi_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign act_start_Push_mioi_bdwt = act_start_Push_mioi_oswt & RVAInRun_wen;
  assign act_start_Push_mioi_biwt = act_start_Push_mioi_oswt & (~ act_start_Push_mioi_bcwt)
      & act_start_Push_mioi_ccs_ccore_done_sync_vld;
  assign act_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct = RVAInRun_wen
      & act_start_Push_mioi_oswt_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_pe_start_Push_mioi_pe_start_Push_mio_wait_dp
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_pe_start_Push_mioi_pe_start_Push_mio_wait_dp (
  clk, rst, pe_start_Push_mioi_oswt, pe_start_Push_mioi_wen_comp, pe_start_Push_mioi_biwt,
      pe_start_Push_mioi_bdwt, pe_start_Push_mioi_bcwt
);
  input clk;
  input rst;
  input pe_start_Push_mioi_oswt;
  output pe_start_Push_mioi_wen_comp;
  input pe_start_Push_mioi_biwt;
  input pe_start_Push_mioi_bdwt;
  output pe_start_Push_mioi_bcwt;
  reg pe_start_Push_mioi_bcwt;



  // Interconnect Declarations for Component Instantiations 
  assign pe_start_Push_mioi_wen_comp = (~ pe_start_Push_mioi_oswt) | pe_start_Push_mioi_biwt
      | pe_start_Push_mioi_bcwt;
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      pe_start_Push_mioi_bcwt <= 1'b0;
    end
    else begin
      pe_start_Push_mioi_bcwt <= ~((~(pe_start_Push_mioi_bcwt | pe_start_Push_mioi_biwt))
          | pe_start_Push_mioi_bdwt);
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_pe_start_Push_mioi_pe_start_Push_mio_wait_ctrl
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_pe_start_Push_mioi_pe_start_Push_mio_wait_ctrl (
  RVAInRun_wen, pe_start_Push_mioi_oswt, pe_start_Push_mioi_biwt, pe_start_Push_mioi_bdwt,
      pe_start_Push_mioi_bcwt, pe_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct,
      pe_start_Push_mioi_ccs_ccore_done_sync_vld, pe_start_Push_mioi_oswt_pff
);
  input RVAInRun_wen;
  input pe_start_Push_mioi_oswt;
  output pe_start_Push_mioi_biwt;
  output pe_start_Push_mioi_bdwt;
  input pe_start_Push_mioi_bcwt;
  output pe_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct;
  input pe_start_Push_mioi_ccs_ccore_done_sync_vld;
  input pe_start_Push_mioi_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign pe_start_Push_mioi_bdwt = pe_start_Push_mioi_oswt & RVAInRun_wen;
  assign pe_start_Push_mioi_biwt = pe_start_Push_mioi_oswt & (~ pe_start_Push_mioi_bcwt)
      & pe_start_Push_mioi_ccs_ccore_done_sync_vld;
  assign pe_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct = RVAInRun_wen &
      pe_start_Push_mioi_oswt_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_start_PopNB_mioi_start_PopNB_mio_wait_dp
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_start_PopNB_mioi_start_PopNB_mio_wait_dp (
  clk, rst, start_PopNB_mioi_return_rsc_z_mxwt, start_PopNB_mioi_biwt, start_PopNB_mioi_bdwt,
      start_PopNB_mioi_return_rsc_z
);
  input clk;
  input rst;
  output start_PopNB_mioi_return_rsc_z_mxwt;
  input start_PopNB_mioi_biwt;
  input start_PopNB_mioi_bdwt;
  input start_PopNB_mioi_return_rsc_z;


  // Interconnect Declarations
  reg start_PopNB_mioi_bcwt;
  reg start_PopNB_mioi_return_rsc_z_bfwt;


  // Interconnect Declarations for Component Instantiations 
  assign start_PopNB_mioi_return_rsc_z_mxwt = MUX_s_1_2_2(start_PopNB_mioi_return_rsc_z,
      start_PopNB_mioi_return_rsc_z_bfwt, start_PopNB_mioi_bcwt);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      start_PopNB_mioi_bcwt <= 1'b0;
    end
    else begin
      start_PopNB_mioi_bcwt <= ~((~(start_PopNB_mioi_bcwt | start_PopNB_mioi_biwt))
          | start_PopNB_mioi_bdwt);
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      start_PopNB_mioi_return_rsc_z_bfwt <= 1'b0;
    end
    else if ( start_PopNB_mioi_biwt ) begin
      start_PopNB_mioi_return_rsc_z_bfwt <= start_PopNB_mioi_return_rsc_z;
    end
  end

  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_start_PopNB_mioi_start_PopNB_mio_wait_ctrl
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_start_PopNB_mioi_start_PopNB_mio_wait_ctrl (
  RVAInRun_wen, RVAInRun_wten, start_PopNB_mioi_oswt, start_PopNB_mioi_biwt, start_PopNB_mioi_bdwt,
      start_PopNB_mioi_biwt_pff, start_PopNB_mioi_oswt_pff
);
  input RVAInRun_wen;
  input RVAInRun_wten;
  input start_PopNB_mioi_oswt;
  output start_PopNB_mioi_biwt;
  output start_PopNB_mioi_bdwt;
  output start_PopNB_mioi_biwt_pff;
  input start_PopNB_mioi_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign start_PopNB_mioi_bdwt = start_PopNB_mioi_oswt & RVAInRun_wen;
  assign start_PopNB_mioi_biwt = (~ RVAInRun_wten) & start_PopNB_mioi_oswt;
  assign start_PopNB_mioi_biwt_pff = RVAInRun_wen & start_PopNB_mioi_oswt_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_act_rva_in_Push_mioi_act_rva_in_Push_mio_wait_dp
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_act_rva_in_Push_mioi_act_rva_in_Push_mio_wait_dp (
  clk, rst, act_rva_in_Push_mioi_oswt, act_rva_in_Push_mioi_wen_comp, act_rva_in_Push_mioi_biwt,
      act_rva_in_Push_mioi_bdwt, act_rva_in_Push_mioi_bcwt
);
  input clk;
  input rst;
  input act_rva_in_Push_mioi_oswt;
  output act_rva_in_Push_mioi_wen_comp;
  input act_rva_in_Push_mioi_biwt;
  input act_rva_in_Push_mioi_bdwt;
  output act_rva_in_Push_mioi_bcwt;
  reg act_rva_in_Push_mioi_bcwt;



  // Interconnect Declarations for Component Instantiations 
  assign act_rva_in_Push_mioi_wen_comp = (~ act_rva_in_Push_mioi_oswt) | act_rva_in_Push_mioi_biwt
      | act_rva_in_Push_mioi_bcwt;
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      act_rva_in_Push_mioi_bcwt <= 1'b0;
    end
    else begin
      act_rva_in_Push_mioi_bcwt <= ~((~(act_rva_in_Push_mioi_bcwt | act_rva_in_Push_mioi_biwt))
          | act_rva_in_Push_mioi_bdwt);
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_act_rva_in_Push_mioi_act_rva_in_Push_mio_wait_ctrl
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_act_rva_in_Push_mioi_act_rva_in_Push_mio_wait_ctrl
    (
  RVAInRun_wen, act_rva_in_Push_mioi_oswt, act_rva_in_Push_mioi_biwt, act_rva_in_Push_mioi_bdwt,
      act_rva_in_Push_mioi_bcwt, act_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct,
      act_rva_in_Push_mioi_ccs_ccore_done_sync_vld, act_rva_in_Push_mioi_oswt_pff
);
  input RVAInRun_wen;
  input act_rva_in_Push_mioi_oswt;
  output act_rva_in_Push_mioi_biwt;
  output act_rva_in_Push_mioi_bdwt;
  input act_rva_in_Push_mioi_bcwt;
  output act_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct;
  input act_rva_in_Push_mioi_ccs_ccore_done_sync_vld;
  input act_rva_in_Push_mioi_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign act_rva_in_Push_mioi_bdwt = act_rva_in_Push_mioi_oswt & RVAInRun_wen;
  assign act_rva_in_Push_mioi_biwt = act_rva_in_Push_mioi_oswt & (~ act_rva_in_Push_mioi_bcwt)
      & act_rva_in_Push_mioi_ccs_ccore_done_sync_vld;
  assign act_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct = RVAInRun_wen & act_rva_in_Push_mioi_oswt_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_pe_rva_in_Push_mioi_pe_rva_in_Push_mio_wait_dp
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_pe_rva_in_Push_mioi_pe_rva_in_Push_mio_wait_dp (
  clk, rst, pe_rva_in_Push_mioi_oswt, pe_rva_in_Push_mioi_wen_comp, pe_rva_in_Push_mioi_biwt,
      pe_rva_in_Push_mioi_bdwt, pe_rva_in_Push_mioi_bcwt
);
  input clk;
  input rst;
  input pe_rva_in_Push_mioi_oswt;
  output pe_rva_in_Push_mioi_wen_comp;
  input pe_rva_in_Push_mioi_biwt;
  input pe_rva_in_Push_mioi_bdwt;
  output pe_rva_in_Push_mioi_bcwt;
  reg pe_rva_in_Push_mioi_bcwt;



  // Interconnect Declarations for Component Instantiations 
  assign pe_rva_in_Push_mioi_wen_comp = (~ pe_rva_in_Push_mioi_oswt) | pe_rva_in_Push_mioi_biwt
      | pe_rva_in_Push_mioi_bcwt;
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      pe_rva_in_Push_mioi_bcwt <= 1'b0;
    end
    else begin
      pe_rva_in_Push_mioi_bcwt <= ~((~(pe_rva_in_Push_mioi_bcwt | pe_rva_in_Push_mioi_biwt))
          | pe_rva_in_Push_mioi_bdwt);
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_pe_rva_in_Push_mioi_pe_rva_in_Push_mio_wait_ctrl
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_pe_rva_in_Push_mioi_pe_rva_in_Push_mio_wait_ctrl (
  RVAInRun_wen, pe_rva_in_Push_mioi_oswt, pe_rva_in_Push_mioi_biwt, pe_rva_in_Push_mioi_bdwt,
      pe_rva_in_Push_mioi_bcwt, pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct, pe_rva_in_Push_mioi_ccs_ccore_done_sync_vld,
      pe_rva_in_Push_mioi_oswt_pff
);
  input RVAInRun_wen;
  input pe_rva_in_Push_mioi_oswt;
  output pe_rva_in_Push_mioi_biwt;
  output pe_rva_in_Push_mioi_bdwt;
  input pe_rva_in_Push_mioi_bcwt;
  output pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct;
  input pe_rva_in_Push_mioi_ccs_ccore_done_sync_vld;
  input pe_rva_in_Push_mioi_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign pe_rva_in_Push_mioi_bdwt = pe_rva_in_Push_mioi_oswt & RVAInRun_wen;
  assign pe_rva_in_Push_mioi_biwt = pe_rva_in_Push_mioi_oswt & (~ pe_rva_in_Push_mioi_bcwt)
      & pe_rva_in_Push_mioi_ccs_ccore_done_sync_vld;
  assign pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct = RVAInRun_wen & pe_rva_in_Push_mioi_oswt_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_rva_in_PopNB_mioi_rva_in_PopNB_mio_wait_dp
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_rva_in_PopNB_mioi_rva_in_PopNB_mio_wait_dp (
  clk, rst, rva_in_PopNB_mioi_data_data_rsc_z_mxwt, rva_in_PopNB_mioi_data_addr_rsc_z_mxwt,
      rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt, rva_in_PopNB_mioi_data_rw_rsc_z_mxwt,
      rva_in_PopNB_mioi_return_rsc_z_mxwt, rva_in_PopNB_mioi_biwt, rva_in_PopNB_mioi_bdwt,
      rva_in_PopNB_mioi_data_data_rsc_z, rva_in_PopNB_mioi_data_addr_rsc_z, rva_in_PopNB_mioi_data_wstrb_rsc_z,
      rva_in_PopNB_mioi_data_rw_rsc_z, rva_in_PopNB_mioi_return_rsc_z
);
  input clk;
  input rst;
  output [127:0] rva_in_PopNB_mioi_data_data_rsc_z_mxwt;
  output [23:0] rva_in_PopNB_mioi_data_addr_rsc_z_mxwt;
  output [15:0] rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt;
  output rva_in_PopNB_mioi_data_rw_rsc_z_mxwt;
  output rva_in_PopNB_mioi_return_rsc_z_mxwt;
  input rva_in_PopNB_mioi_biwt;
  input rva_in_PopNB_mioi_bdwt;
  input [127:0] rva_in_PopNB_mioi_data_data_rsc_z;
  input [23:0] rva_in_PopNB_mioi_data_addr_rsc_z;
  input [15:0] rva_in_PopNB_mioi_data_wstrb_rsc_z;
  input rva_in_PopNB_mioi_data_rw_rsc_z;
  input rva_in_PopNB_mioi_return_rsc_z;


  // Interconnect Declarations
  reg rva_in_PopNB_mioi_bcwt;
  reg [127:0] rva_in_PopNB_mioi_data_data_rsc_z_bfwt;
  reg [23:0] rva_in_PopNB_mioi_data_addr_rsc_z_bfwt;
  reg [15:0] rva_in_PopNB_mioi_data_wstrb_rsc_z_bfwt;
  reg rva_in_PopNB_mioi_data_rw_rsc_z_bfwt;
  reg rva_in_PopNB_mioi_return_rsc_z_bfwt;


  // Interconnect Declarations for Component Instantiations 
  assign rva_in_PopNB_mioi_data_data_rsc_z_mxwt = MUX_v_128_2_2(rva_in_PopNB_mioi_data_data_rsc_z,
      rva_in_PopNB_mioi_data_data_rsc_z_bfwt, rva_in_PopNB_mioi_bcwt);
  assign rva_in_PopNB_mioi_data_addr_rsc_z_mxwt = MUX_v_24_2_2(rva_in_PopNB_mioi_data_addr_rsc_z,
      rva_in_PopNB_mioi_data_addr_rsc_z_bfwt, rva_in_PopNB_mioi_bcwt);
  assign rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt = MUX_v_16_2_2(rva_in_PopNB_mioi_data_wstrb_rsc_z,
      rva_in_PopNB_mioi_data_wstrb_rsc_z_bfwt, rva_in_PopNB_mioi_bcwt);
  assign rva_in_PopNB_mioi_data_rw_rsc_z_mxwt = MUX_s_1_2_2(rva_in_PopNB_mioi_data_rw_rsc_z,
      rva_in_PopNB_mioi_data_rw_rsc_z_bfwt, rva_in_PopNB_mioi_bcwt);
  assign rva_in_PopNB_mioi_return_rsc_z_mxwt = MUX_s_1_2_2(rva_in_PopNB_mioi_return_rsc_z,
      rva_in_PopNB_mioi_return_rsc_z_bfwt, rva_in_PopNB_mioi_bcwt);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      rva_in_PopNB_mioi_bcwt <= 1'b0;
    end
    else begin
      rva_in_PopNB_mioi_bcwt <= ~((~(rva_in_PopNB_mioi_bcwt | rva_in_PopNB_mioi_biwt))
          | rva_in_PopNB_mioi_bdwt);
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      rva_in_PopNB_mioi_data_data_rsc_z_bfwt <= 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
      rva_in_PopNB_mioi_data_addr_rsc_z_bfwt <= 24'b000000000000000000000000;
      rva_in_PopNB_mioi_data_wstrb_rsc_z_bfwt <= 16'b0000000000000000;
      rva_in_PopNB_mioi_data_rw_rsc_z_bfwt <= 1'b0;
      rva_in_PopNB_mioi_return_rsc_z_bfwt <= 1'b0;
    end
    else if ( rva_in_PopNB_mioi_biwt ) begin
      rva_in_PopNB_mioi_data_data_rsc_z_bfwt <= rva_in_PopNB_mioi_data_data_rsc_z;
      rva_in_PopNB_mioi_data_addr_rsc_z_bfwt <= rva_in_PopNB_mioi_data_addr_rsc_z;
      rva_in_PopNB_mioi_data_wstrb_rsc_z_bfwt <= rva_in_PopNB_mioi_data_wstrb_rsc_z;
      rva_in_PopNB_mioi_data_rw_rsc_z_bfwt <= rva_in_PopNB_mioi_data_rw_rsc_z;
      rva_in_PopNB_mioi_return_rsc_z_bfwt <= rva_in_PopNB_mioi_return_rsc_z;
    end
  end

  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [127:0] MUX_v_128_2_2;
    input [127:0] input_0;
    input [127:0] input_1;
    input  sel;
    reg [127:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_128_2_2 = result;
  end
  endfunction


  function automatic [15:0] MUX_v_16_2_2;
    input [15:0] input_0;
    input [15:0] input_1;
    input  sel;
    reg [15:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_16_2_2 = result;
  end
  endfunction


  function automatic [23:0] MUX_v_24_2_2;
    input [23:0] input_0;
    input [23:0] input_1;
    input  sel;
    reg [23:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_24_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_rva_in_PopNB_mioi_rva_in_PopNB_mio_wait_ctrl
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_rva_in_PopNB_mioi_rva_in_PopNB_mio_wait_ctrl (
  RVAInRun_wen, RVAInRun_wten, rva_in_PopNB_mioi_oswt, rva_in_PopNB_mioi_biwt, rva_in_PopNB_mioi_bdwt,
      rva_in_PopNB_mioi_biwt_pff, rva_in_PopNB_mioi_oswt_pff
);
  input RVAInRun_wen;
  input RVAInRun_wten;
  input rva_in_PopNB_mioi_oswt;
  output rva_in_PopNB_mioi_biwt;
  output rva_in_PopNB_mioi_bdwt;
  output rva_in_PopNB_mioi_biwt_pff;
  input rva_in_PopNB_mioi_oswt_pff;



  // Interconnect Declarations for Component Instantiations 
  assign rva_in_PopNB_mioi_bdwt = rva_in_PopNB_mioi_oswt & RVAInRun_wen;
  assign rva_in_PopNB_mioi_biwt = (~ RVAInRun_wten) & rva_in_PopNB_mioi_oswt;
  assign rva_in_PopNB_mioi_biwt_pff = RVAInRun_wen & rva_in_PopNB_mioi_oswt_pff;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun_rva_out_Push_mioi
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun_rva_out_Push_mioi (
  clk, rst, rva_out_vld, rva_out_rdy, rva_out_dat, RVAOutRun_wen, RVAOutRun_wten,
      rva_out_Push_mioi_oswt, rva_out_Push_mioi_wen_comp, rva_out_Push_mioi_m_data_rsc_dat_RVAOutRun,
      rva_out_Push_mioi_oswt_pff
);
  input clk;
  input rst;
  output rva_out_vld;
  input rva_out_rdy;
  output [127:0] rva_out_dat;
  input RVAOutRun_wen;
  input RVAOutRun_wten;
  input rva_out_Push_mioi_oswt;
  output rva_out_Push_mioi_wen_comp;
  input [127:0] rva_out_Push_mioi_m_data_rsc_dat_RVAOutRun;
  input rva_out_Push_mioi_oswt_pff;


  // Interconnect Declarations
  wire rva_out_Push_mioi_biwt;
  wire rva_out_Push_mioi_bdwt;
  wire rva_out_Push_mioi_bcwt;
  wire rva_out_Push_mioi_ccs_ccore_start_rsc_dat_RVAOutRun_sct;
  wire rva_out_Push_mioi_ccs_ccore_done_sync_vld;


  // Interconnect Declarations for Component Instantiations 
  PEModule_Connections_OutBlocking_RVSink_spec_Axi_rvaCfg_Read_Connections_SYN_PORT_Push
      rva_out_Push_mioi (
      .this_vld(rva_out_vld),
      .this_rdy(rva_out_rdy),
      .this_dat(rva_out_dat),
      .m_data_rsc_dat(rva_out_Push_mioi_m_data_rsc_dat_RVAOutRun),
      .ccs_ccore_start_rsc_dat(rva_out_Push_mioi_ccs_ccore_start_rsc_dat_RVAOutRun_sct),
      .ccs_ccore_done_sync_vld(rva_out_Push_mioi_ccs_ccore_done_sync_vld),
      .ccs_MIO_clk(clk),
      .ccs_MIO_arst(rst)
    );
  PEModule_PERVA_RVAOutRun_rva_out_Push_mioi_rva_out_Push_mio_wait_ctrl PERVA_RVAOutRun_rva_out_Push_mioi_rva_out_Push_mio_wait_ctrl_inst
      (
      .RVAOutRun_wen(RVAOutRun_wen),
      .RVAOutRun_wten(RVAOutRun_wten),
      .rva_out_Push_mioi_oswt(rva_out_Push_mioi_oswt),
      .rva_out_Push_mioi_biwt(rva_out_Push_mioi_biwt),
      .rva_out_Push_mioi_bdwt(rva_out_Push_mioi_bdwt),
      .rva_out_Push_mioi_bcwt(rva_out_Push_mioi_bcwt),
      .rva_out_Push_mioi_ccs_ccore_start_rsc_dat_RVAOutRun_sct(rva_out_Push_mioi_ccs_ccore_start_rsc_dat_RVAOutRun_sct),
      .rva_out_Push_mioi_ccs_ccore_done_sync_vld(rva_out_Push_mioi_ccs_ccore_done_sync_vld),
      .rva_out_Push_mioi_oswt_pff(rva_out_Push_mioi_oswt_pff)
    );
  PEModule_PERVA_RVAOutRun_rva_out_Push_mioi_rva_out_Push_mio_wait_dp PERVA_RVAOutRun_rva_out_Push_mioi_rva_out_Push_mio_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .rva_out_Push_mioi_oswt(rva_out_Push_mioi_oswt),
      .rva_out_Push_mioi_wen_comp(rva_out_Push_mioi_wen_comp),
      .rva_out_Push_mioi_biwt(rva_out_Push_mioi_biwt),
      .rva_out_Push_mioi_bdwt(rva_out_Push_mioi_bdwt),
      .rva_out_Push_mioi_bcwt(rva_out_Push_mioi_bcwt)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun_act_rva_out_PopNB_mioi
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun_act_rva_out_PopNB_mioi (
  clk, rst, act_rva_out_vld, act_rva_out_rdy, act_rva_out_dat, RVAOutRun_wen, RVAOutRun_wten,
      act_rva_out_PopNB_mioi_oswt, act_rva_out_PopNB_mioi_data_data_rsc_z_mxwt, act_rva_out_PopNB_mioi_return_rsc_z_mxwt,
      RVAOutRun_wten_pff, act_rva_out_PopNB_mioi_oswt_pff
);
  input clk;
  input rst;
  input act_rva_out_vld;
  output act_rva_out_rdy;
  input [127:0] act_rva_out_dat;
  input RVAOutRun_wen;
  input RVAOutRun_wten;
  input act_rva_out_PopNB_mioi_oswt;
  output [127:0] act_rva_out_PopNB_mioi_data_data_rsc_z_mxwt;
  output act_rva_out_PopNB_mioi_return_rsc_z_mxwt;
  input RVAOutRun_wten_pff;
  input act_rva_out_PopNB_mioi_oswt_pff;


  // Interconnect Declarations
  wire act_rva_out_PopNB_mioi_biwt;
  wire act_rva_out_PopNB_mioi_bdwt;
  wire [127:0] act_rva_out_PopNB_mioi_data_data_rsc_z;
  wire act_rva_out_PopNB_mioi_return_rsc_z;
  wire act_rva_out_PopNB_mioi_biwt_iff;


  // Interconnect Declarations for Component Instantiations 
  PEModule_Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Read_Connections_SYN_PORT_PopNB
      act_rva_out_PopNB_mioi (
      .this_vld(act_rva_out_vld),
      .this_rdy(act_rva_out_rdy),
      .this_dat(act_rva_out_dat),
      .data_data_rsc_z(act_rva_out_PopNB_mioi_data_data_rsc_z),
      .return_rsc_z(act_rva_out_PopNB_mioi_return_rsc_z),
      .ccs_ccore_start_rsc_dat(act_rva_out_PopNB_mioi_biwt_iff),
      .ccs_MIO_clk(clk),
      .ccs_MIO_arst(rst)
    );
  PEModule_PERVA_RVAOutRun_act_rva_out_PopNB_mioi_act_rva_out_PopNB_mio_wait_ctrl
      PERVA_RVAOutRun_act_rva_out_PopNB_mioi_act_rva_out_PopNB_mio_wait_ctrl_inst
      (
      .RVAOutRun_wen(RVAOutRun_wen),
      .RVAOutRun_wten(RVAOutRun_wten),
      .act_rva_out_PopNB_mioi_oswt(act_rva_out_PopNB_mioi_oswt),
      .act_rva_out_PopNB_mioi_biwt(act_rva_out_PopNB_mioi_biwt),
      .act_rva_out_PopNB_mioi_bdwt(act_rva_out_PopNB_mioi_bdwt),
      .act_rva_out_PopNB_mioi_biwt_pff(act_rva_out_PopNB_mioi_biwt_iff),
      .RVAOutRun_wten_pff(RVAOutRun_wten_pff),
      .act_rva_out_PopNB_mioi_oswt_pff(act_rva_out_PopNB_mioi_oswt_pff)
    );
  PEModule_PERVA_RVAOutRun_act_rva_out_PopNB_mioi_act_rva_out_PopNB_mio_wait_dp PERVA_RVAOutRun_act_rva_out_PopNB_mioi_act_rva_out_PopNB_mio_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .act_rva_out_PopNB_mioi_data_data_rsc_z_mxwt(act_rva_out_PopNB_mioi_data_data_rsc_z_mxwt),
      .act_rva_out_PopNB_mioi_return_rsc_z_mxwt(act_rva_out_PopNB_mioi_return_rsc_z_mxwt),
      .act_rva_out_PopNB_mioi_biwt(act_rva_out_PopNB_mioi_biwt),
      .act_rva_out_PopNB_mioi_bdwt(act_rva_out_PopNB_mioi_bdwt),
      .act_rva_out_PopNB_mioi_data_data_rsc_z(act_rva_out_PopNB_mioi_data_data_rsc_z),
      .act_rva_out_PopNB_mioi_return_rsc_z(act_rva_out_PopNB_mioi_return_rsc_z)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun_pe_rva_out_PopNB_mioi
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun_pe_rva_out_PopNB_mioi (
  clk, rst, pe_rva_out_vld, pe_rva_out_rdy, pe_rva_out_dat, RVAOutRun_wen, RVAOutRun_wten,
      pe_rva_out_PopNB_mioi_oswt, pe_rva_out_PopNB_mioi_data_data_rsc_z_mxwt, pe_rva_out_PopNB_mioi_return_rsc_z_mxwt,
      RVAOutRun_wten_pff, pe_rva_out_PopNB_mioi_oswt_pff
);
  input clk;
  input rst;
  input pe_rva_out_vld;
  output pe_rva_out_rdy;
  input [127:0] pe_rva_out_dat;
  input RVAOutRun_wen;
  input RVAOutRun_wten;
  input pe_rva_out_PopNB_mioi_oswt;
  output [127:0] pe_rva_out_PopNB_mioi_data_data_rsc_z_mxwt;
  output pe_rva_out_PopNB_mioi_return_rsc_z_mxwt;
  input RVAOutRun_wten_pff;
  input pe_rva_out_PopNB_mioi_oswt_pff;


  // Interconnect Declarations
  wire pe_rva_out_PopNB_mioi_biwt;
  wire pe_rva_out_PopNB_mioi_bdwt;
  wire [127:0] pe_rva_out_PopNB_mioi_data_data_rsc_z;
  wire pe_rva_out_PopNB_mioi_return_rsc_z;
  wire pe_rva_out_PopNB_mioi_biwt_iff;


  // Interconnect Declarations for Component Instantiations 
  PEModule_Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Read_Connections_SYN_PORT_PopNB
      pe_rva_out_PopNB_mioi (
      .this_vld(pe_rva_out_vld),
      .this_rdy(pe_rva_out_rdy),
      .this_dat(pe_rva_out_dat),
      .data_data_rsc_z(pe_rva_out_PopNB_mioi_data_data_rsc_z),
      .return_rsc_z(pe_rva_out_PopNB_mioi_return_rsc_z),
      .ccs_ccore_start_rsc_dat(pe_rva_out_PopNB_mioi_biwt_iff),
      .ccs_MIO_clk(clk),
      .ccs_MIO_arst(rst)
    );
  PEModule_PERVA_RVAOutRun_pe_rva_out_PopNB_mioi_pe_rva_out_PopNB_mio_wait_ctrl PERVA_RVAOutRun_pe_rva_out_PopNB_mioi_pe_rva_out_PopNB_mio_wait_ctrl_inst
      (
      .RVAOutRun_wen(RVAOutRun_wen),
      .RVAOutRun_wten(RVAOutRun_wten),
      .pe_rva_out_PopNB_mioi_oswt(pe_rva_out_PopNB_mioi_oswt),
      .pe_rva_out_PopNB_mioi_biwt(pe_rva_out_PopNB_mioi_biwt),
      .pe_rva_out_PopNB_mioi_bdwt(pe_rva_out_PopNB_mioi_bdwt),
      .pe_rva_out_PopNB_mioi_biwt_pff(pe_rva_out_PopNB_mioi_biwt_iff),
      .RVAOutRun_wten_pff(RVAOutRun_wten_pff),
      .pe_rva_out_PopNB_mioi_oswt_pff(pe_rva_out_PopNB_mioi_oswt_pff)
    );
  PEModule_PERVA_RVAOutRun_pe_rva_out_PopNB_mioi_pe_rva_out_PopNB_mio_wait_dp PERVA_RVAOutRun_pe_rva_out_PopNB_mioi_pe_rva_out_PopNB_mio_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .pe_rva_out_PopNB_mioi_data_data_rsc_z_mxwt(pe_rva_out_PopNB_mioi_data_data_rsc_z_mxwt),
      .pe_rva_out_PopNB_mioi_return_rsc_z_mxwt(pe_rva_out_PopNB_mioi_return_rsc_z_mxwt),
      .pe_rva_out_PopNB_mioi_biwt(pe_rva_out_PopNB_mioi_biwt),
      .pe_rva_out_PopNB_mioi_bdwt(pe_rva_out_PopNB_mioi_bdwt),
      .pe_rva_out_PopNB_mioi_data_data_rsc_z(pe_rva_out_PopNB_mioi_data_data_rsc_z),
      .pe_rva_out_PopNB_mioi_return_rsc_z(pe_rva_out_PopNB_mioi_return_rsc_z)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_act_start_Push_mioi
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_act_start_Push_mioi (
  clk, rst, act_start_vld, act_start_rdy, act_start_dat, RVAInRun_wen, act_start_Push_mioi_oswt,
      act_start_Push_mioi_wen_comp, act_start_Push_mioi_oswt_pff
);
  input clk;
  input rst;
  output act_start_vld;
  input act_start_rdy;
  output act_start_dat;
  input RVAInRun_wen;
  input act_start_Push_mioi_oswt;
  output act_start_Push_mioi_wen_comp;
  input act_start_Push_mioi_oswt_pff;


  // Interconnect Declarations
  wire act_start_Push_mioi_biwt;
  wire act_start_Push_mioi_bdwt;
  wire act_start_Push_mioi_bcwt;
  wire act_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct;
  wire act_start_Push_mioi_ccs_ccore_done_sync_vld;


  // Interconnect Declarations for Component Instantiations 
  PEModule_Connections_OutBlocking_bool_Connections_SYN_PORT_Push  act_start_Push_mioi
      (
      .this_vld(act_start_vld),
      .this_rdy(act_start_rdy),
      .this_dat(act_start_dat),
      .ccs_ccore_start_rsc_dat(act_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct),
      .ccs_ccore_done_sync_vld(act_start_Push_mioi_ccs_ccore_done_sync_vld),
      .ccs_MIO_clk(clk),
      .ccs_MIO_arst(rst)
    );
  PEModule_PERVA_RVAInRun_act_start_Push_mioi_act_start_Push_mio_wait_ctrl PERVA_RVAInRun_act_start_Push_mioi_act_start_Push_mio_wait_ctrl_inst
      (
      .RVAInRun_wen(RVAInRun_wen),
      .act_start_Push_mioi_oswt(act_start_Push_mioi_oswt),
      .act_start_Push_mioi_biwt(act_start_Push_mioi_biwt),
      .act_start_Push_mioi_bdwt(act_start_Push_mioi_bdwt),
      .act_start_Push_mioi_bcwt(act_start_Push_mioi_bcwt),
      .act_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct(act_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct),
      .act_start_Push_mioi_ccs_ccore_done_sync_vld(act_start_Push_mioi_ccs_ccore_done_sync_vld),
      .act_start_Push_mioi_oswt_pff(act_start_Push_mioi_oswt_pff)
    );
  PEModule_PERVA_RVAInRun_act_start_Push_mioi_act_start_Push_mio_wait_dp PERVA_RVAInRun_act_start_Push_mioi_act_start_Push_mio_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .act_start_Push_mioi_oswt(act_start_Push_mioi_oswt),
      .act_start_Push_mioi_wen_comp(act_start_Push_mioi_wen_comp),
      .act_start_Push_mioi_biwt(act_start_Push_mioi_biwt),
      .act_start_Push_mioi_bdwt(act_start_Push_mioi_bdwt),
      .act_start_Push_mioi_bcwt(act_start_Push_mioi_bcwt)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_pe_start_Push_mioi
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_pe_start_Push_mioi (
  clk, rst, pe_start_vld, pe_start_rdy, pe_start_dat, RVAInRun_wen, pe_start_Push_mioi_oswt,
      pe_start_Push_mioi_wen_comp, pe_start_Push_mioi_oswt_pff
);
  input clk;
  input rst;
  output pe_start_vld;
  input pe_start_rdy;
  output pe_start_dat;
  input RVAInRun_wen;
  input pe_start_Push_mioi_oswt;
  output pe_start_Push_mioi_wen_comp;
  input pe_start_Push_mioi_oswt_pff;


  // Interconnect Declarations
  wire pe_start_Push_mioi_biwt;
  wire pe_start_Push_mioi_bdwt;
  wire pe_start_Push_mioi_bcwt;
  wire pe_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct;
  wire pe_start_Push_mioi_ccs_ccore_done_sync_vld;


  // Interconnect Declarations for Component Instantiations 
  PEModule_Connections_OutBlocking_bool_Connections_SYN_PORT_Push  pe_start_Push_mioi
      (
      .this_vld(pe_start_vld),
      .this_rdy(pe_start_rdy),
      .this_dat(pe_start_dat),
      .ccs_ccore_start_rsc_dat(pe_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct),
      .ccs_ccore_done_sync_vld(pe_start_Push_mioi_ccs_ccore_done_sync_vld),
      .ccs_MIO_clk(clk),
      .ccs_MIO_arst(rst)
    );
  PEModule_PERVA_RVAInRun_pe_start_Push_mioi_pe_start_Push_mio_wait_ctrl PERVA_RVAInRun_pe_start_Push_mioi_pe_start_Push_mio_wait_ctrl_inst
      (
      .RVAInRun_wen(RVAInRun_wen),
      .pe_start_Push_mioi_oswt(pe_start_Push_mioi_oswt),
      .pe_start_Push_mioi_biwt(pe_start_Push_mioi_biwt),
      .pe_start_Push_mioi_bdwt(pe_start_Push_mioi_bdwt),
      .pe_start_Push_mioi_bcwt(pe_start_Push_mioi_bcwt),
      .pe_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct(pe_start_Push_mioi_ccs_ccore_start_rsc_dat_RVAInRun_sct),
      .pe_start_Push_mioi_ccs_ccore_done_sync_vld(pe_start_Push_mioi_ccs_ccore_done_sync_vld),
      .pe_start_Push_mioi_oswt_pff(pe_start_Push_mioi_oswt_pff)
    );
  PEModule_PERVA_RVAInRun_pe_start_Push_mioi_pe_start_Push_mio_wait_dp PERVA_RVAInRun_pe_start_Push_mioi_pe_start_Push_mio_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .pe_start_Push_mioi_oswt(pe_start_Push_mioi_oswt),
      .pe_start_Push_mioi_wen_comp(pe_start_Push_mioi_wen_comp),
      .pe_start_Push_mioi_biwt(pe_start_Push_mioi_biwt),
      .pe_start_Push_mioi_bdwt(pe_start_Push_mioi_bdwt),
      .pe_start_Push_mioi_bcwt(pe_start_Push_mioi_bcwt)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_start_PopNB_mioi
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_start_PopNB_mioi (
  clk, rst, start_vld, start_rdy, RVAInRun_wen, RVAInRun_wten, start_PopNB_mioi_oswt,
      start_PopNB_mioi_return_rsc_z_mxwt, start_PopNB_mioi_oswt_pff
);
  input clk;
  input rst;
  input start_vld;
  output start_rdy;
  input RVAInRun_wen;
  input RVAInRun_wten;
  input start_PopNB_mioi_oswt;
  output start_PopNB_mioi_return_rsc_z_mxwt;
  input start_PopNB_mioi_oswt_pff;


  // Interconnect Declarations
  wire start_PopNB_mioi_biwt;
  wire start_PopNB_mioi_bdwt;
  wire start_PopNB_mioi_return_rsc_z;
  wire start_PopNB_mioi_biwt_iff;


  // Interconnect Declarations for Component Instantiations 
  PEModule_Connections_InBlocking_bool_Connections_SYN_PORT_PopNB  start_PopNB_mioi
      (
      .this_vld(start_vld),
      .this_rdy(start_rdy),
      .this_dat(1'b0),
      .return_rsc_z(start_PopNB_mioi_return_rsc_z),
      .ccs_ccore_start_rsc_dat(start_PopNB_mioi_biwt_iff),
      .ccs_MIO_clk(clk),
      .ccs_MIO_arst(rst)
    );
  PEModule_PERVA_RVAInRun_start_PopNB_mioi_start_PopNB_mio_wait_ctrl PERVA_RVAInRun_start_PopNB_mioi_start_PopNB_mio_wait_ctrl_inst
      (
      .RVAInRun_wen(RVAInRun_wen),
      .RVAInRun_wten(RVAInRun_wten),
      .start_PopNB_mioi_oswt(start_PopNB_mioi_oswt),
      .start_PopNB_mioi_biwt(start_PopNB_mioi_biwt),
      .start_PopNB_mioi_bdwt(start_PopNB_mioi_bdwt),
      .start_PopNB_mioi_biwt_pff(start_PopNB_mioi_biwt_iff),
      .start_PopNB_mioi_oswt_pff(start_PopNB_mioi_oswt_pff)
    );
  PEModule_PERVA_RVAInRun_start_PopNB_mioi_start_PopNB_mio_wait_dp PERVA_RVAInRun_start_PopNB_mioi_start_PopNB_mio_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .start_PopNB_mioi_return_rsc_z_mxwt(start_PopNB_mioi_return_rsc_z_mxwt),
      .start_PopNB_mioi_biwt(start_PopNB_mioi_biwt),
      .start_PopNB_mioi_bdwt(start_PopNB_mioi_bdwt),
      .start_PopNB_mioi_return_rsc_z(start_PopNB_mioi_return_rsc_z)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_act_rva_in_Push_mioi
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_act_rva_in_Push_mioi (
  clk, rst, act_rva_in_vld, act_rva_in_rdy, act_rva_in_dat, RVAInRun_wen, act_rva_in_Push_mioi_oswt,
      act_rva_in_Push_mioi_wen_comp, act_rva_in_Push_mioi_m_data_rsc_dat_RVAInRun,
      act_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun, act_rva_in_Push_mioi_m_wstrb_rsc_dat_RVAInRun,
      act_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun, act_rva_in_Push_mioi_oswt_pff
);
  input clk;
  input rst;
  output act_rva_in_vld;
  input act_rva_in_rdy;
  output [168:0] act_rva_in_dat;
  input RVAInRun_wen;
  input act_rva_in_Push_mioi_oswt;
  output act_rva_in_Push_mioi_wen_comp;
  input [127:0] act_rva_in_Push_mioi_m_data_rsc_dat_RVAInRun;
  input [23:0] act_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun;
  input [15:0] act_rva_in_Push_mioi_m_wstrb_rsc_dat_RVAInRun;
  input act_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun;
  input act_rva_in_Push_mioi_oswt_pff;


  // Interconnect Declarations
  wire act_rva_in_Push_mioi_biwt;
  wire act_rva_in_Push_mioi_bdwt;
  wire act_rva_in_Push_mioi_bcwt;
  wire act_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct;
  wire act_rva_in_Push_mioi_ccs_ccore_done_sync_vld;


  // Interconnect Declarations for Component Instantiations 
  PEModule_Connections_OutBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_Push
      act_rva_in_Push_mioi (
      .this_vld(act_rva_in_vld),
      .this_rdy(act_rva_in_rdy),
      .this_dat(act_rva_in_dat),
      .m_data_rsc_dat(act_rva_in_Push_mioi_m_data_rsc_dat_RVAInRun),
      .m_addr_rsc_dat(act_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun),
      .m_wstrb_rsc_dat(act_rva_in_Push_mioi_m_wstrb_rsc_dat_RVAInRun),
      .m_rw_rsc_dat(act_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun),
      .ccs_ccore_start_rsc_dat(act_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct),
      .ccs_ccore_done_sync_vld(act_rva_in_Push_mioi_ccs_ccore_done_sync_vld),
      .ccs_MIO_clk(clk),
      .ccs_MIO_arst(rst)
    );
  PEModule_PERVA_RVAInRun_act_rva_in_Push_mioi_act_rva_in_Push_mio_wait_ctrl PERVA_RVAInRun_act_rva_in_Push_mioi_act_rva_in_Push_mio_wait_ctrl_inst
      (
      .RVAInRun_wen(RVAInRun_wen),
      .act_rva_in_Push_mioi_oswt(act_rva_in_Push_mioi_oswt),
      .act_rva_in_Push_mioi_biwt(act_rva_in_Push_mioi_biwt),
      .act_rva_in_Push_mioi_bdwt(act_rva_in_Push_mioi_bdwt),
      .act_rva_in_Push_mioi_bcwt(act_rva_in_Push_mioi_bcwt),
      .act_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct(act_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct),
      .act_rva_in_Push_mioi_ccs_ccore_done_sync_vld(act_rva_in_Push_mioi_ccs_ccore_done_sync_vld),
      .act_rva_in_Push_mioi_oswt_pff(act_rva_in_Push_mioi_oswt_pff)
    );
  PEModule_PERVA_RVAInRun_act_rva_in_Push_mioi_act_rva_in_Push_mio_wait_dp PERVA_RVAInRun_act_rva_in_Push_mioi_act_rva_in_Push_mio_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .act_rva_in_Push_mioi_oswt(act_rva_in_Push_mioi_oswt),
      .act_rva_in_Push_mioi_wen_comp(act_rva_in_Push_mioi_wen_comp),
      .act_rva_in_Push_mioi_biwt(act_rva_in_Push_mioi_biwt),
      .act_rva_in_Push_mioi_bdwt(act_rva_in_Push_mioi_bdwt),
      .act_rva_in_Push_mioi_bcwt(act_rva_in_Push_mioi_bcwt)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_pe_rva_in_Push_mioi
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_pe_rva_in_Push_mioi (
  clk, rst, pe_rva_in_vld, pe_rva_in_rdy, pe_rva_in_dat, RVAInRun_wen, pe_rva_in_Push_mioi_oswt,
      pe_rva_in_Push_mioi_wen_comp, pe_rva_in_Push_mioi_m_data_rsc_dat_RVAInRun,
      pe_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun, pe_rva_in_Push_mioi_m_wstrb_rsc_dat_RVAInRun,
      pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun, pe_rva_in_Push_mioi_oswt_pff
);
  input clk;
  input rst;
  output pe_rva_in_vld;
  input pe_rva_in_rdy;
  output [168:0] pe_rva_in_dat;
  input RVAInRun_wen;
  input pe_rva_in_Push_mioi_oswt;
  output pe_rva_in_Push_mioi_wen_comp;
  input [127:0] pe_rva_in_Push_mioi_m_data_rsc_dat_RVAInRun;
  input [23:0] pe_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun;
  input [15:0] pe_rva_in_Push_mioi_m_wstrb_rsc_dat_RVAInRun;
  input pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun;
  input pe_rva_in_Push_mioi_oswt_pff;


  // Interconnect Declarations
  wire pe_rva_in_Push_mioi_biwt;
  wire pe_rva_in_Push_mioi_bdwt;
  wire pe_rva_in_Push_mioi_bcwt;
  wire pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct;
  wire pe_rva_in_Push_mioi_ccs_ccore_done_sync_vld;


  // Interconnect Declarations for Component Instantiations 
  PEModule_Connections_OutBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_Push
      pe_rva_in_Push_mioi (
      .this_vld(pe_rva_in_vld),
      .this_rdy(pe_rva_in_rdy),
      .this_dat(pe_rva_in_dat),
      .m_data_rsc_dat(pe_rva_in_Push_mioi_m_data_rsc_dat_RVAInRun),
      .m_addr_rsc_dat(pe_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun),
      .m_wstrb_rsc_dat(pe_rva_in_Push_mioi_m_wstrb_rsc_dat_RVAInRun),
      .m_rw_rsc_dat(pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun),
      .ccs_ccore_start_rsc_dat(pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct),
      .ccs_ccore_done_sync_vld(pe_rva_in_Push_mioi_ccs_ccore_done_sync_vld),
      .ccs_MIO_clk(clk),
      .ccs_MIO_arst(rst)
    );
  PEModule_PERVA_RVAInRun_pe_rva_in_Push_mioi_pe_rva_in_Push_mio_wait_ctrl PERVA_RVAInRun_pe_rva_in_Push_mioi_pe_rva_in_Push_mio_wait_ctrl_inst
      (
      .RVAInRun_wen(RVAInRun_wen),
      .pe_rva_in_Push_mioi_oswt(pe_rva_in_Push_mioi_oswt),
      .pe_rva_in_Push_mioi_biwt(pe_rva_in_Push_mioi_biwt),
      .pe_rva_in_Push_mioi_bdwt(pe_rva_in_Push_mioi_bdwt),
      .pe_rva_in_Push_mioi_bcwt(pe_rva_in_Push_mioi_bcwt),
      .pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct(pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun_sct),
      .pe_rva_in_Push_mioi_ccs_ccore_done_sync_vld(pe_rva_in_Push_mioi_ccs_ccore_done_sync_vld),
      .pe_rva_in_Push_mioi_oswt_pff(pe_rva_in_Push_mioi_oswt_pff)
    );
  PEModule_PERVA_RVAInRun_pe_rva_in_Push_mioi_pe_rva_in_Push_mio_wait_dp PERVA_RVAInRun_pe_rva_in_Push_mioi_pe_rva_in_Push_mio_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .pe_rva_in_Push_mioi_oswt(pe_rva_in_Push_mioi_oswt),
      .pe_rva_in_Push_mioi_wen_comp(pe_rva_in_Push_mioi_wen_comp),
      .pe_rva_in_Push_mioi_biwt(pe_rva_in_Push_mioi_biwt),
      .pe_rva_in_Push_mioi_bdwt(pe_rva_in_Push_mioi_bdwt),
      .pe_rva_in_Push_mioi_bcwt(pe_rva_in_Push_mioi_bcwt)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun_rva_in_PopNB_mioi
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun_rva_in_PopNB_mioi (
  clk, rst, rva_in_vld, rva_in_rdy, rva_in_dat, RVAInRun_wen, RVAInRun_wten, rva_in_PopNB_mioi_oswt,
      rva_in_PopNB_mioi_data_data_rsc_z_mxwt, rva_in_PopNB_mioi_data_addr_rsc_z_mxwt,
      rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt, rva_in_PopNB_mioi_data_rw_rsc_z_mxwt,
      rva_in_PopNB_mioi_return_rsc_z_mxwt, rva_in_PopNB_mioi_oswt_pff
);
  input clk;
  input rst;
  input rva_in_vld;
  output rva_in_rdy;
  input [168:0] rva_in_dat;
  input RVAInRun_wen;
  input RVAInRun_wten;
  input rva_in_PopNB_mioi_oswt;
  output [127:0] rva_in_PopNB_mioi_data_data_rsc_z_mxwt;
  output [23:0] rva_in_PopNB_mioi_data_addr_rsc_z_mxwt;
  output [15:0] rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt;
  output rva_in_PopNB_mioi_data_rw_rsc_z_mxwt;
  output rva_in_PopNB_mioi_return_rsc_z_mxwt;
  input rva_in_PopNB_mioi_oswt_pff;


  // Interconnect Declarations
  wire rva_in_PopNB_mioi_biwt;
  wire rva_in_PopNB_mioi_bdwt;
  wire [127:0] rva_in_PopNB_mioi_data_data_rsc_z;
  wire [23:0] rva_in_PopNB_mioi_data_addr_rsc_z;
  wire [15:0] rva_in_PopNB_mioi_data_wstrb_rsc_z;
  wire rva_in_PopNB_mioi_data_rw_rsc_z;
  wire rva_in_PopNB_mioi_return_rsc_z;
  wire rva_in_PopNB_mioi_biwt_iff;


  // Interconnect Declarations for Component Instantiations 
  PEModule_Connections_InBlocking_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_PopNB
      rva_in_PopNB_mioi (
      .this_vld(rva_in_vld),
      .this_rdy(rva_in_rdy),
      .this_dat(rva_in_dat),
      .data_data_rsc_z(rva_in_PopNB_mioi_data_data_rsc_z),
      .data_addr_rsc_z(rva_in_PopNB_mioi_data_addr_rsc_z),
      .data_wstrb_rsc_z(rva_in_PopNB_mioi_data_wstrb_rsc_z),
      .data_rw_rsc_z(rva_in_PopNB_mioi_data_rw_rsc_z),
      .return_rsc_z(rva_in_PopNB_mioi_return_rsc_z),
      .ccs_ccore_start_rsc_dat(rva_in_PopNB_mioi_biwt_iff),
      .ccs_MIO_clk(clk),
      .ccs_MIO_arst(rst)
    );
  PEModule_PERVA_RVAInRun_rva_in_PopNB_mioi_rva_in_PopNB_mio_wait_ctrl PERVA_RVAInRun_rva_in_PopNB_mioi_rva_in_PopNB_mio_wait_ctrl_inst
      (
      .RVAInRun_wen(RVAInRun_wen),
      .RVAInRun_wten(RVAInRun_wten),
      .rva_in_PopNB_mioi_oswt(rva_in_PopNB_mioi_oswt),
      .rva_in_PopNB_mioi_biwt(rva_in_PopNB_mioi_biwt),
      .rva_in_PopNB_mioi_bdwt(rva_in_PopNB_mioi_bdwt),
      .rva_in_PopNB_mioi_biwt_pff(rva_in_PopNB_mioi_biwt_iff),
      .rva_in_PopNB_mioi_oswt_pff(rva_in_PopNB_mioi_oswt_pff)
    );
  PEModule_PERVA_RVAInRun_rva_in_PopNB_mioi_rva_in_PopNB_mio_wait_dp PERVA_RVAInRun_rva_in_PopNB_mioi_rva_in_PopNB_mio_wait_dp_inst
      (
      .clk(clk),
      .rst(rst),
      .rva_in_PopNB_mioi_data_data_rsc_z_mxwt(rva_in_PopNB_mioi_data_data_rsc_z_mxwt),
      .rva_in_PopNB_mioi_data_addr_rsc_z_mxwt(rva_in_PopNB_mioi_data_addr_rsc_z_mxwt),
      .rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt(rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt),
      .rva_in_PopNB_mioi_data_rw_rsc_z_mxwt(rva_in_PopNB_mioi_data_rw_rsc_z_mxwt),
      .rva_in_PopNB_mioi_return_rsc_z_mxwt(rva_in_PopNB_mioi_return_rsc_z_mxwt),
      .rva_in_PopNB_mioi_biwt(rva_in_PopNB_mioi_biwt),
      .rva_in_PopNB_mioi_bdwt(rva_in_PopNB_mioi_bdwt),
      .rva_in_PopNB_mioi_data_data_rsc_z(rva_in_PopNB_mioi_data_data_rsc_z),
      .rva_in_PopNB_mioi_data_addr_rsc_z(rva_in_PopNB_mioi_data_addr_rsc_z),
      .rva_in_PopNB_mioi_data_wstrb_rsc_z(rva_in_PopNB_mioi_data_wstrb_rsc_z),
      .rva_in_PopNB_mioi_data_rw_rsc_z(rva_in_PopNB_mioi_data_rw_rsc_z),
      .rva_in_PopNB_mioi_return_rsc_z(rva_in_PopNB_mioi_return_rsc_z)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAOutRun
// ------------------------------------------------------------------


module PEModule_PERVA_RVAOutRun (
  clk, rst, rva_out_vld, rva_out_rdy, rva_out_dat, pe_rva_out_vld, pe_rva_out_rdy,
      pe_rva_out_dat, act_rva_out_vld, act_rva_out_rdy, act_rva_out_dat
);
  input clk;
  input rst;
  output rva_out_vld;
  input rva_out_rdy;
  output [127:0] rva_out_dat;
  input pe_rva_out_vld;
  output pe_rva_out_rdy;
  input [127:0] pe_rva_out_dat;
  input act_rva_out_vld;
  output act_rva_out_rdy;
  input [127:0] act_rva_out_dat;


  // Interconnect Declarations
  wire RVAOutRun_wten;
  wire [127:0] pe_rva_out_PopNB_mioi_data_data_rsc_z_mxwt;
  wire pe_rva_out_PopNB_mioi_return_rsc_z_mxwt;
  wire [127:0] act_rva_out_PopNB_mioi_data_data_rsc_z_mxwt;
  wire act_rva_out_PopNB_mioi_return_rsc_z_mxwt;
  wire rva_out_Push_mioi_wen_comp;
  wire fsm_output;
  reg while_Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Read_Connections_SYN_PORT_PopNB_return_sva_1;
  reg while_stage_0_3;
  reg reg_rva_out_Push_mioi_iswt0_cse;
  reg reg_act_rva_out_PopNB_mioi_iswt0_cse;
  reg reg_pe_rva_out_PopNB_mioi_iswt0_cse;
  wire RVAOutRun_wten_iff;
  wire and_3_rmff;
  wire and_2_rmff;
  reg [127:0] while_rva_out_reg_data_sva_1;


  // Interconnect Declarations for Component Instantiations 
  wire and_1_nl;
  wire [127:0] nl_PERVA_RVAOutRun_rva_out_Push_mioi_inst_rva_out_Push_mioi_m_data_rsc_dat_RVAOutRun;
  assign and_1_nl = fsm_output & (~ while_Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Read_Connections_SYN_PORT_PopNB_return_sva_1);
  assign nl_PERVA_RVAOutRun_rva_out_Push_mioi_inst_rva_out_Push_mioi_m_data_rsc_dat_RVAOutRun
      = MUX_v_128_2_2(while_rva_out_reg_data_sva_1, act_rva_out_PopNB_mioi_data_data_rsc_z_mxwt,
      and_1_nl);
  PEModule_PERVA_RVAOutRun_pe_rva_out_PopNB_mioi PERVA_RVAOutRun_pe_rva_out_PopNB_mioi_inst
      (
      .clk(clk),
      .rst(rst),
      .pe_rva_out_vld(pe_rva_out_vld),
      .pe_rva_out_rdy(pe_rva_out_rdy),
      .pe_rva_out_dat(pe_rva_out_dat),
      .RVAOutRun_wen(rva_out_Push_mioi_wen_comp),
      .RVAOutRun_wten(RVAOutRun_wten),
      .pe_rva_out_PopNB_mioi_oswt(reg_pe_rva_out_PopNB_mioi_iswt0_cse),
      .pe_rva_out_PopNB_mioi_data_data_rsc_z_mxwt(pe_rva_out_PopNB_mioi_data_data_rsc_z_mxwt),
      .pe_rva_out_PopNB_mioi_return_rsc_z_mxwt(pe_rva_out_PopNB_mioi_return_rsc_z_mxwt),
      .RVAOutRun_wten_pff(RVAOutRun_wten_iff),
      .pe_rva_out_PopNB_mioi_oswt_pff(fsm_output)
    );
  PEModule_PERVA_RVAOutRun_act_rva_out_PopNB_mioi PERVA_RVAOutRun_act_rva_out_PopNB_mioi_inst
      (
      .clk(clk),
      .rst(rst),
      .act_rva_out_vld(act_rva_out_vld),
      .act_rva_out_rdy(act_rva_out_rdy),
      .act_rva_out_dat(act_rva_out_dat),
      .RVAOutRun_wen(rva_out_Push_mioi_wen_comp),
      .RVAOutRun_wten(RVAOutRun_wten),
      .act_rva_out_PopNB_mioi_oswt(reg_act_rva_out_PopNB_mioi_iswt0_cse),
      .act_rva_out_PopNB_mioi_data_data_rsc_z_mxwt(act_rva_out_PopNB_mioi_data_data_rsc_z_mxwt),
      .act_rva_out_PopNB_mioi_return_rsc_z_mxwt(act_rva_out_PopNB_mioi_return_rsc_z_mxwt),
      .RVAOutRun_wten_pff(RVAOutRun_wten_iff),
      .act_rva_out_PopNB_mioi_oswt_pff(and_3_rmff)
    );
  PEModule_PERVA_RVAOutRun_rva_out_Push_mioi PERVA_RVAOutRun_rva_out_Push_mioi_inst
      (
      .clk(clk),
      .rst(rst),
      .rva_out_vld(rva_out_vld),
      .rva_out_rdy(rva_out_rdy),
      .rva_out_dat(rva_out_dat),
      .RVAOutRun_wen(rva_out_Push_mioi_wen_comp),
      .RVAOutRun_wten(RVAOutRun_wten_iff),
      .rva_out_Push_mioi_oswt(reg_rva_out_Push_mioi_iswt0_cse),
      .rva_out_Push_mioi_wen_comp(rva_out_Push_mioi_wen_comp),
      .rva_out_Push_mioi_m_data_rsc_dat_RVAOutRun(nl_PERVA_RVAOutRun_rva_out_Push_mioi_inst_rva_out_Push_mioi_m_data_rsc_dat_RVAOutRun[127:0]),
      .rva_out_Push_mioi_oswt_pff(and_2_rmff)
    );
  PEModule_PERVA_RVAOutRun_staller_1 PERVA_RVAOutRun_staller_1_inst (
      .clk(clk),
      .rst(rst),
      .RVAOutRun_wten(RVAOutRun_wten),
      .rva_out_Push_mioi_wen_comp(rva_out_Push_mioi_wen_comp),
      .RVAOutRun_wten_pff(RVAOutRun_wten_iff)
    );
  PEModule_PERVA_RVAOutRun_RVAOutRun_fsm PERVA_RVAOutRun_RVAOutRun_fsm_inst (
      .clk(clk),
      .rst(rst),
      .rva_out_Push_mioi_wen_comp(rva_out_Push_mioi_wen_comp),
      .fsm_output(fsm_output)
    );
  assign and_2_rmff = (act_rva_out_PopNB_mioi_return_rsc_z_mxwt | while_Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Read_Connections_SYN_PORT_PopNB_return_sva_1)
      & while_stage_0_3;
  assign and_3_rmff = reg_pe_rva_out_PopNB_mioi_iswt0_cse & (~ pe_rva_out_PopNB_mioi_return_rsc_z_mxwt);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      reg_rva_out_Push_mioi_iswt0_cse <= 1'b0;
      reg_act_rva_out_PopNB_mioi_iswt0_cse <= 1'b0;
      reg_pe_rva_out_PopNB_mioi_iswt0_cse <= 1'b0;
      while_stage_0_3 <= 1'b0;
    end
    else if ( rva_out_Push_mioi_wen_comp ) begin
      reg_rva_out_Push_mioi_iswt0_cse <= and_2_rmff;
      reg_act_rva_out_PopNB_mioi_iswt0_cse <= and_3_rmff;
      reg_pe_rva_out_PopNB_mioi_iswt0_cse <= fsm_output;
      while_stage_0_3 <= reg_pe_rva_out_PopNB_mioi_iswt0_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      while_Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Read_Connections_SYN_PORT_PopNB_return_sva_1
          <= 1'b0;
    end
    else if ( rva_out_Push_mioi_wen_comp & reg_pe_rva_out_PopNB_mioi_iswt0_cse )
        begin
      while_Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Read_Connections_SYN_PORT_PopNB_return_sva_1
          <= pe_rva_out_PopNB_mioi_return_rsc_z_mxwt;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      while_rva_out_reg_data_sva_1 <= 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    end
    else if ( rva_out_Push_mioi_wen_comp & reg_pe_rva_out_PopNB_mioi_iswt0_cse &
        pe_rva_out_PopNB_mioi_return_rsc_z_mxwt ) begin
      while_rva_out_reg_data_sva_1 <= pe_rva_out_PopNB_mioi_data_data_rsc_z_mxwt;
    end
  end

  function automatic [127:0] MUX_v_128_2_2;
    input [127:0] input_0;
    input [127:0] input_1;
    input  sel;
    reg [127:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_128_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA_RVAInRun
// ------------------------------------------------------------------


module PEModule_PERVA_RVAInRun (
  clk, rst, rva_in_vld, rva_in_rdy, rva_in_dat, start_vld, start_rdy, pe_start_vld,
      pe_start_rdy, pe_start_dat, act_start_vld, act_start_rdy, act_start_dat, pe_rva_in_vld,
      pe_rva_in_rdy, pe_rva_in_dat, act_rva_in_vld, act_rva_in_rdy, act_rva_in_dat,
      SC_SRAM_CONFIG
);
  input clk;
  input rst;
  input rva_in_vld;
  output rva_in_rdy;
  input [168:0] rva_in_dat;
  input start_vld;
  output start_rdy;
  output pe_start_vld;
  input pe_start_rdy;
  output pe_start_dat;
  output act_start_vld;
  input act_start_rdy;
  output act_start_dat;
  output pe_rva_in_vld;
  input pe_rva_in_rdy;
  output [168:0] pe_rva_in_dat;
  output act_rva_in_vld;
  input act_rva_in_rdy;
  output [168:0] act_rva_in_dat;
  output [31:0] SC_SRAM_CONFIG;
  reg [31:0] SC_SRAM_CONFIG;


  // Interconnect Declarations
  wire RVAInRun_wen;
  wire RVAInRun_wten;
  wire [127:0] rva_in_PopNB_mioi_data_data_rsc_z_mxwt;
  wire [23:0] rva_in_PopNB_mioi_data_addr_rsc_z_mxwt;
  wire [15:0] rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt;
  wire rva_in_PopNB_mioi_data_rw_rsc_z_mxwt;
  wire rva_in_PopNB_mioi_return_rsc_z_mxwt;
  wire pe_rva_in_Push_mioi_wen_comp;
  wire act_rva_in_Push_mioi_wen_comp;
  wire start_PopNB_mioi_return_rsc_z_mxwt;
  wire pe_start_Push_mioi_wen_comp;
  wire act_start_Push_mioi_wen_comp;
  wire fsm_output;
  wire and_dcpl_3;
  wire or_dcpl_1;
  wire nor_tmp;
  reg while_if_switch_lp_while_if_switch_lp_while_if_switch_lp_while_if_switch_lp_nor_itm_1;
  reg while_Connections_InBlocking_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_PopNB_return_sva_1;
  reg while_stage_0_3;
  reg [3:0] while_if_tmp_slc_while_rva_in_reg_addr_23_20_itm_1;
  reg while_rva_in_reg_rw_sva_st_1;
  reg reg_act_start_Push_mioi_iswt0_cse;
  reg reg_start_PopNB_mioi_iswt0_cse;
  reg reg_act_rva_in_Push_mioi_iswt0_cse;
  reg reg_pe_rva_in_Push_mioi_iswt0_cse;
  reg reg_rva_in_PopNB_mioi_iswt0_cse;
  wire and_18_rmff;
  wire and_17_rmff;
  wire and_14_rmff;
  wire and_13_rmff;
  reg [31:0] while_if_case_3_if_slc_while_rva_in_reg_data_31_0_itm_1;
  wire while_if_tmp_and_cse;
  reg reg_while_if_case_3_if_slc_while_rva_in_reg_data_31_0_itm_1_enexo;
  wire SC_SRAM_CONFIG_and_enex5;
  wire while_if_case_3_if_and_tmp;

  wire mux_nl;
  wire mux_1_nl;
  wire mux_3_nl;
  wire mux_2_nl;
  wire or_4_nl;
  wire or_3_nl;

  // Interconnect Declarations for Component Instantiations 
  wire[3:0] while_if_case_3_else_mux1h_nl;
  wire and_10_nl;
  wire and_11_nl;
  wire and_12_nl;
  wire [23:0] nl_PERVA_RVAInRun_pe_rva_in_Push_mioi_inst_pe_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun;
  assign and_10_nl = ((rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[21]) | (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[23]))
      & (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[20]);
  assign and_11_nl = or_dcpl_1 & (~ (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[23]));
  assign and_12_nl = (~ (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[20])) & (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[23]);
  assign while_if_case_3_else_mux1h_nl = MUX1HOT_v_4_3_2(4'b0011, (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[23:20]),
      4'b1110, {and_10_nl , and_11_nl , and_12_nl});
  assign nl_PERVA_RVAInRun_pe_rva_in_Push_mioi_inst_pe_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun
      = {while_if_case_3_else_mux1h_nl , (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[19:0])};
  wire  nl_PERVA_RVAInRun_pe_rva_in_Push_mioi_inst_pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun;
  assign nl_PERVA_RVAInRun_pe_rva_in_Push_mioi_inst_pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun
      = rva_in_PopNB_mioi_data_rw_rsc_z_mxwt & or_dcpl_1;
  wire[3:0] while_if_case_3_else_while_if_case_3_else_or_nl;
  wire [23:0] nl_PERVA_RVAInRun_act_rva_in_Push_mioi_inst_act_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun;
  assign while_if_case_3_else_while_if_case_3_else_or_nl = MUX_v_4_2_2((rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[23:20]),
      4'b1111, (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[21]));
  assign nl_PERVA_RVAInRun_act_rva_in_Push_mioi_inst_act_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun
      = {while_if_case_3_else_while_if_case_3_else_or_nl , (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[19:0])};
  PEModule_PERVA_RVAInRun_rva_in_PopNB_mioi PERVA_RVAInRun_rva_in_PopNB_mioi_inst
      (
      .clk(clk),
      .rst(rst),
      .rva_in_vld(rva_in_vld),
      .rva_in_rdy(rva_in_rdy),
      .rva_in_dat(rva_in_dat),
      .RVAInRun_wen(RVAInRun_wen),
      .RVAInRun_wten(RVAInRun_wten),
      .rva_in_PopNB_mioi_oswt(reg_rva_in_PopNB_mioi_iswt0_cse),
      .rva_in_PopNB_mioi_data_data_rsc_z_mxwt(rva_in_PopNB_mioi_data_data_rsc_z_mxwt),
      .rva_in_PopNB_mioi_data_addr_rsc_z_mxwt(rva_in_PopNB_mioi_data_addr_rsc_z_mxwt),
      .rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt(rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt),
      .rva_in_PopNB_mioi_data_rw_rsc_z_mxwt(rva_in_PopNB_mioi_data_rw_rsc_z_mxwt),
      .rva_in_PopNB_mioi_return_rsc_z_mxwt(rva_in_PopNB_mioi_return_rsc_z_mxwt),
      .rva_in_PopNB_mioi_oswt_pff(fsm_output)
    );
  PEModule_PERVA_RVAInRun_pe_rva_in_Push_mioi PERVA_RVAInRun_pe_rva_in_Push_mioi_inst
      (
      .clk(clk),
      .rst(rst),
      .pe_rva_in_vld(pe_rva_in_vld),
      .pe_rva_in_rdy(pe_rva_in_rdy),
      .pe_rva_in_dat(pe_rva_in_dat),
      .RVAInRun_wen(RVAInRun_wen),
      .pe_rva_in_Push_mioi_oswt(reg_pe_rva_in_Push_mioi_iswt0_cse),
      .pe_rva_in_Push_mioi_wen_comp(pe_rva_in_Push_mioi_wen_comp),
      .pe_rva_in_Push_mioi_m_data_rsc_dat_RVAInRun(rva_in_PopNB_mioi_data_data_rsc_z_mxwt),
      .pe_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun(nl_PERVA_RVAInRun_pe_rva_in_Push_mioi_inst_pe_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun[23:0]),
      .pe_rva_in_Push_mioi_m_wstrb_rsc_dat_RVAInRun(rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt),
      .pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun(nl_PERVA_RVAInRun_pe_rva_in_Push_mioi_inst_pe_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun),
      .pe_rva_in_Push_mioi_oswt_pff(and_18_rmff)
    );
  PEModule_PERVA_RVAInRun_act_rva_in_Push_mioi PERVA_RVAInRun_act_rva_in_Push_mioi_inst
      (
      .clk(clk),
      .rst(rst),
      .act_rva_in_vld(act_rva_in_vld),
      .act_rva_in_rdy(act_rva_in_rdy),
      .act_rva_in_dat(act_rva_in_dat),
      .RVAInRun_wen(RVAInRun_wen),
      .act_rva_in_Push_mioi_oswt(reg_act_rva_in_Push_mioi_iswt0_cse),
      .act_rva_in_Push_mioi_wen_comp(act_rva_in_Push_mioi_wen_comp),
      .act_rva_in_Push_mioi_m_data_rsc_dat_RVAInRun(rva_in_PopNB_mioi_data_data_rsc_z_mxwt),
      .act_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun(nl_PERVA_RVAInRun_act_rva_in_Push_mioi_inst_act_rva_in_Push_mioi_m_addr_rsc_dat_RVAInRun[23:0]),
      .act_rva_in_Push_mioi_m_wstrb_rsc_dat_RVAInRun(rva_in_PopNB_mioi_data_wstrb_rsc_z_mxwt),
      .act_rva_in_Push_mioi_m_rw_rsc_dat_RVAInRun(rva_in_PopNB_mioi_data_rw_rsc_z_mxwt),
      .act_rva_in_Push_mioi_oswt_pff(and_17_rmff)
    );
  PEModule_PERVA_RVAInRun_start_PopNB_mioi PERVA_RVAInRun_start_PopNB_mioi_inst (
      .clk(clk),
      .rst(rst),
      .start_vld(start_vld),
      .start_rdy(start_rdy),
      .RVAInRun_wen(RVAInRun_wen),
      .RVAInRun_wten(RVAInRun_wten),
      .start_PopNB_mioi_oswt(reg_start_PopNB_mioi_iswt0_cse),
      .start_PopNB_mioi_return_rsc_z_mxwt(start_PopNB_mioi_return_rsc_z_mxwt),
      .start_PopNB_mioi_oswt_pff(and_14_rmff)
    );
  PEModule_PERVA_RVAInRun_pe_start_Push_mioi PERVA_RVAInRun_pe_start_Push_mioi_inst
      (
      .clk(clk),
      .rst(rst),
      .pe_start_vld(pe_start_vld),
      .pe_start_rdy(pe_start_rdy),
      .pe_start_dat(pe_start_dat),
      .RVAInRun_wen(RVAInRun_wen),
      .pe_start_Push_mioi_oswt(reg_act_start_Push_mioi_iswt0_cse),
      .pe_start_Push_mioi_wen_comp(pe_start_Push_mioi_wen_comp),
      .pe_start_Push_mioi_oswt_pff(and_13_rmff)
    );
  PEModule_PERVA_RVAInRun_act_start_Push_mioi PERVA_RVAInRun_act_start_Push_mioi_inst
      (
      .clk(clk),
      .rst(rst),
      .act_start_vld(act_start_vld),
      .act_start_rdy(act_start_rdy),
      .act_start_dat(act_start_dat),
      .RVAInRun_wen(RVAInRun_wen),
      .act_start_Push_mioi_oswt(reg_act_start_Push_mioi_iswt0_cse),
      .act_start_Push_mioi_wen_comp(act_start_Push_mioi_wen_comp),
      .act_start_Push_mioi_oswt_pff(and_13_rmff)
    );
  PEModule_PERVA_RVAInRun_staller PERVA_RVAInRun_staller_inst (
      .clk(clk),
      .rst(rst),
      .RVAInRun_wen(RVAInRun_wen),
      .RVAInRun_wten(RVAInRun_wten),
      .pe_rva_in_Push_mioi_wen_comp(pe_rva_in_Push_mioi_wen_comp),
      .act_rva_in_Push_mioi_wen_comp(act_rva_in_Push_mioi_wen_comp),
      .pe_start_Push_mioi_wen_comp(pe_start_Push_mioi_wen_comp),
      .act_start_Push_mioi_wen_comp(act_start_Push_mioi_wen_comp)
    );
  PEModule_PERVA_RVAInRun_RVAInRun_fsm PERVA_RVAInRun_RVAInRun_fsm_inst (
      .clk(clk),
      .rst(rst),
      .RVAInRun_wen(RVAInRun_wen),
      .fsm_output(fsm_output)
    );
  assign mux_nl = MUX_s_1_2_2(start_PopNB_mioi_return_rsc_z_mxwt, while_if_switch_lp_while_if_switch_lp_while_if_switch_lp_while_if_switch_lp_nor_itm_1,
      while_Connections_InBlocking_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_PopNB_return_sva_1);
  assign and_13_rmff = mux_nl & while_stage_0_3;
  assign and_14_rmff = reg_rva_in_PopNB_mioi_iswt0_cse & (~ rva_in_PopNB_mioi_return_rsc_z_mxwt);
  assign mux_1_nl = MUX_s_1_2_2((~ (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[21])),
      nor_tmp, rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[22]);
  assign and_17_rmff = mux_1_nl & and_dcpl_3 & (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[23]);
  assign or_4_nl = rva_in_PopNB_mioi_data_rw_rsc_z_mxwt | or_dcpl_1;
  assign mux_2_nl = MUX_s_1_2_2(or_4_nl, nor_tmp, rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[22]);
  assign or_3_nl = (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[22:20]!=3'b110);
  assign mux_3_nl = MUX_s_1_2_2(mux_2_nl, or_3_nl, rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[23]);
  assign and_18_rmff = (~ mux_3_nl) & and_dcpl_3;
  assign SC_SRAM_CONFIG_and_enex5 = RVAInRun_wen & (~((~(while_stage_0_3 & while_Connections_InBlocking_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_PopNB_return_sva_1))
      | (~ while_rva_in_reg_rw_sva_st_1) | (while_if_tmp_slc_while_rva_in_reg_addr_23_20_itm_1!=4'b0011)))
      & reg_while_if_case_3_if_slc_while_rva_in_reg_data_31_0_itm_1_enexo;
  assign while_if_tmp_and_cse = RVAInRun_wen & and_dcpl_3;
  assign and_dcpl_3 = reg_rva_in_PopNB_mioi_iswt0_cse & rva_in_PopNB_mioi_return_rsc_z_mxwt;
  assign or_dcpl_1 = ~((rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[21:20]==2'b11));
  assign nor_tmp = (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[21:20]==2'b11);
  assign while_if_case_3_if_and_tmp = RVAInRun_wen & and_dcpl_3 & (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[21:20]==2'b11)
      & rva_in_PopNB_mioi_data_rw_rsc_z_mxwt & (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[23:22]==2'b00);
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      reg_act_start_Push_mioi_iswt0_cse <= 1'b0;
      reg_start_PopNB_mioi_iswt0_cse <= 1'b0;
      reg_act_rva_in_Push_mioi_iswt0_cse <= 1'b0;
      reg_pe_rva_in_Push_mioi_iswt0_cse <= 1'b0;
      reg_rva_in_PopNB_mioi_iswt0_cse <= 1'b0;
      while_stage_0_3 <= 1'b0;
    end
    else if ( RVAInRun_wen ) begin
      reg_act_start_Push_mioi_iswt0_cse <= and_13_rmff;
      reg_start_PopNB_mioi_iswt0_cse <= and_14_rmff;
      reg_act_rva_in_Push_mioi_iswt0_cse <= and_17_rmff;
      reg_pe_rva_in_Push_mioi_iswt0_cse <= and_18_rmff;
      reg_rva_in_PopNB_mioi_iswt0_cse <= fsm_output;
      while_stage_0_3 <= reg_rva_in_PopNB_mioi_iswt0_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      SC_SRAM_CONFIG <= 32'b00000000000000000000000000000000;
    end
    else if ( SC_SRAM_CONFIG_and_enex5 ) begin
      SC_SRAM_CONFIG <= while_if_case_3_if_slc_while_rva_in_reg_data_31_0_itm_1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      while_if_case_3_if_slc_while_rva_in_reg_data_31_0_itm_1 <= 32'b00000000000000000000000000000000;
    end
    else if ( while_if_case_3_if_and_tmp ) begin
      while_if_case_3_if_slc_while_rva_in_reg_data_31_0_itm_1 <= rva_in_PopNB_mioi_data_data_rsc_z_mxwt[31:0];
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      while_rva_in_reg_rw_sva_st_1 <= 1'b0;
    end
    else if ( RVAInRun_wen & and_dcpl_3 & (rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[23:20]==4'b0011)
        ) begin
      while_rva_in_reg_rw_sva_st_1 <= rva_in_PopNB_mioi_data_rw_rsc_z_mxwt;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      while_if_tmp_slc_while_rva_in_reg_addr_23_20_itm_1 <= 4'b0000;
      while_if_switch_lp_while_if_switch_lp_while_if_switch_lp_while_if_switch_lp_nor_itm_1
          <= 1'b0;
    end
    else if ( while_if_tmp_and_cse ) begin
      while_if_tmp_slc_while_rva_in_reg_addr_23_20_itm_1 <= rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[23:20];
      while_if_switch_lp_while_if_switch_lp_while_if_switch_lp_while_if_switch_lp_nor_itm_1
          <= ~((rva_in_PopNB_mioi_data_addr_rsc_z_mxwt[23:20]!=4'b0000));
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      while_Connections_InBlocking_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_PopNB_return_sva_1
          <= 1'b0;
    end
    else if ( RVAInRun_wen & reg_rva_in_PopNB_mioi_iswt0_cse ) begin
      while_Connections_InBlocking_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_PopNB_return_sva_1
          <= rva_in_PopNB_mioi_return_rsc_z_mxwt;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      reg_while_if_case_3_if_slc_while_rva_in_reg_data_31_0_itm_1_enexo <= 1'b1;
    end
    else if ( while_if_case_3_if_and_tmp | SC_SRAM_CONFIG_and_enex5 ) begin
      reg_while_if_case_3_if_slc_while_rva_in_reg_data_31_0_itm_1_enexo <= while_if_case_3_if_and_tmp;
    end
  end

  function automatic [3:0] MUX1HOT_v_4_3_2;
    input [3:0] input_2;
    input [3:0] input_1;
    input [3:0] input_0;
    input [2:0] sel;
    reg [3:0] result;
  begin
    result = input_0 & {4{sel[0]}};
    result = result | (input_1 & {4{sel[1]}});
    result = result | (input_2 & {4{sel[2]}});
    MUX1HOT_v_4_3_2 = result;
  end
  endfunction


  function automatic  MUX_s_1_2_2;
    input  input_0;
    input  input_1;
    input  sel;
    reg  result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function automatic [3:0] MUX_v_4_2_2;
    input [3:0] input_0;
    input [3:0] input_1;
    input  sel;
    reg [3:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_4_2_2 = result;
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule_PERVA
// ------------------------------------------------------------------


module PEModule_PERVA (
  clk, rst, rva_in_vld, rva_in_rdy, rva_in_dat, rva_out_vld, rva_out_rdy, rva_out_dat,
      start_vld, start_rdy, start_dat, pe_start_vld, pe_start_rdy, pe_start_dat,
      act_start_vld, act_start_rdy, act_start_dat, pe_rva_in_vld, pe_rva_in_rdy,
      pe_rva_in_dat, pe_rva_out_vld, pe_rva_out_rdy, pe_rva_out_dat, act_rva_in_vld,
      act_rva_in_rdy, act_rva_in_dat, act_rva_out_vld, act_rva_out_rdy, act_rva_out_dat,
      SC_SRAM_CONFIG
);
  input clk;
  input rst;
  input rva_in_vld;
  output rva_in_rdy;
  input [168:0] rva_in_dat;
  output rva_out_vld;
  input rva_out_rdy;
  output [127:0] rva_out_dat;
  input start_vld;
  output start_rdy;
  input start_dat;
  output pe_start_vld;
  input pe_start_rdy;
  output pe_start_dat;
  output act_start_vld;
  input act_start_rdy;
  output act_start_dat;
  output pe_rva_in_vld;
  input pe_rva_in_rdy;
  output [168:0] pe_rva_in_dat;
  input pe_rva_out_vld;
  output pe_rva_out_rdy;
  input [127:0] pe_rva_out_dat;
  output act_rva_in_vld;
  input act_rva_in_rdy;
  output [168:0] act_rva_in_dat;
  input act_rva_out_vld;
  output act_rva_out_rdy;
  input [127:0] act_rva_out_dat;
  output [31:0] SC_SRAM_CONFIG;



  // Interconnect Declarations for Component Instantiations 
  PEModule_PERVA_RVAInRun PERVA_RVAInRun_inst (
      .clk(clk),
      .rst(rst),
      .rva_in_vld(rva_in_vld),
      .rva_in_rdy(rva_in_rdy),
      .rva_in_dat(rva_in_dat),
      .start_vld(start_vld),
      .start_rdy(start_rdy),
      .pe_start_vld(pe_start_vld),
      .pe_start_rdy(pe_start_rdy),
      .pe_start_dat(pe_start_dat),
      .act_start_vld(act_start_vld),
      .act_start_rdy(act_start_rdy),
      .act_start_dat(act_start_dat),
      .pe_rva_in_vld(pe_rva_in_vld),
      .pe_rva_in_rdy(pe_rva_in_rdy),
      .pe_rva_in_dat(pe_rva_in_dat),
      .act_rva_in_vld(act_rva_in_vld),
      .act_rva_in_rdy(act_rva_in_rdy),
      .act_rva_in_dat(act_rva_in_dat),
      .SC_SRAM_CONFIG(SC_SRAM_CONFIG)
    );
  PEModule_PERVA_RVAOutRun PERVA_RVAOutRun_inst (
      .clk(clk),
      .rst(rst),
      .rva_out_vld(rva_out_vld),
      .rva_out_rdy(rva_out_rdy),
      .rva_out_dat(rva_out_dat),
      .pe_rva_out_vld(pe_rva_out_vld),
      .pe_rva_out_rdy(pe_rva_out_rdy),
      .pe_rva_out_dat(pe_rva_out_dat),
      .act_rva_out_vld(act_rva_out_vld),
      .act_rva_out_rdy(act_rva_out_rdy),
      .act_rva_out_dat(act_rva_out_dat)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    PEModule
// ------------------------------------------------------------------


module PEModule (
  clk, rst, start_vld, start_rdy, start_dat, done_vld, done_rdy, done_dat, rva_in_vld,
      rva_in_rdy, rva_in_dat, rva_out_vld, rva_out_rdy, rva_out_dat, input_port_vld,
      input_port_rdy, input_port_dat, output_port_vld, output_port_rdy, output_port_dat
);
  input clk;
  input rst;
  input start_vld;
  output start_rdy;
  input start_dat;
  output done_vld;
  input done_rdy;
  output done_dat;
  input rva_in_vld;
  output rva_in_rdy;
  input [168:0] rva_in_dat;
  output rva_out_vld;
  input rva_out_rdy;
  output [127:0] rva_out_dat;
  input input_port_vld;
  output input_port_rdy;
  input [137:0] input_port_dat;
  output output_port_vld;
  input output_port_rdy;
  output [137:0] output_port_dat;


  // Interconnect Declarations
  wire pe_start_vld;
  wire pe_start_rdy;
  wire pe_start_dat;
  wire pe_rva_in_vld;
  wire pe_rva_in_rdy;
  wire [168:0] pe_rva_in_dat;
  wire pe_rva_out_vld;
  wire pe_rva_out_rdy;
  wire [127:0] pe_rva_out_dat;
  wire act_start_vld;
  wire act_start_rdy;
  wire act_start_dat;
  wire act_rva_in_vld;
  wire act_rva_in_rdy;
  wire [168:0] act_rva_in_dat;
  wire act_rva_out_vld;
  wire act_rva_out_rdy;
  wire [127:0] act_rva_out_dat;
  wire act_port_vld;
  wire act_port_rdy;
  wire [255:0] act_port_dat;
  wire [31:0] SC_SRAM_CONFIG;


  // Interconnect Declarations for Component Instantiations 
  PEModule_PERVA perva_inst (
      .clk(clk),
      .rst(rst),
      .rva_in_vld(rva_in_vld),
      .rva_in_rdy(rva_in_rdy),
      .rva_in_dat(rva_in_dat),
      .rva_out_vld(rva_out_vld),
      .rva_out_rdy(rva_out_rdy),
      .rva_out_dat(rva_out_dat),
      .start_vld(start_vld),
      .start_rdy(start_rdy),
      .start_dat(1'b0),
      .pe_start_vld(pe_start_vld),
      .pe_start_rdy(pe_start_rdy),
      .pe_start_dat(pe_start_dat),
      .act_start_vld(act_start_vld),
      .act_start_rdy(act_start_rdy),
      .act_start_dat(act_start_dat),
      .pe_rva_in_vld(pe_rva_in_vld),
      .pe_rva_in_rdy(pe_rva_in_rdy),
      .pe_rva_in_dat(pe_rva_in_dat),
      .pe_rva_out_vld(pe_rva_out_vld),
      .pe_rva_out_rdy(pe_rva_out_rdy),
      .pe_rva_out_dat(pe_rva_out_dat),
      .act_rva_in_vld(act_rva_in_vld),
      .act_rva_in_rdy(act_rva_in_rdy),
      .act_rva_in_dat(act_rva_in_dat),
      .act_rva_out_vld(act_rva_out_vld),
      .act_rva_out_rdy(act_rva_out_rdy),
      .act_rva_out_dat(act_rva_out_dat),
      .SC_SRAM_CONFIG(SC_SRAM_CONFIG)
    );
  PEModule_PECore pecore_inst (
      .clk(clk),
      .rst(rst),
      .start_vld(pe_start_vld),
      .start_rdy(pe_start_rdy),
      .start_dat(pe_start_dat),
      .input_port_vld(input_port_vld),
      .input_port_rdy(input_port_rdy),
      .input_port_dat(input_port_dat),
      .rva_in_vld(pe_rva_in_vld),
      .rva_in_rdy(pe_rva_in_rdy),
      .rva_in_dat(pe_rva_in_dat),
      .rva_out_vld(pe_rva_out_vld),
      .rva_out_rdy(pe_rva_out_rdy),
      .rva_out_dat(pe_rva_out_dat),
      .act_port_vld(act_port_vld),
      .act_port_rdy(act_port_rdy),
      .act_port_dat(act_port_dat),
      .SC_SRAM_CONFIG(SC_SRAM_CONFIG)
    );
  PEModule_ActUnit act_inst (
      .clk(clk),
      .rst(rst),
      .start_vld(act_start_vld),
      .start_rdy(act_start_rdy),
      .start_dat(act_start_dat),
      .act_port_vld(act_port_vld),
      .act_port_rdy(act_port_rdy),
      .act_port_dat(act_port_dat),
      .rva_in_vld(act_rva_in_vld),
      .rva_in_rdy(act_rva_in_rdy),
      .rva_in_dat(act_rva_in_dat),
      .rva_out_vld(act_rva_out_vld),
      .rva_out_rdy(act_rva_out_rdy),
      .rva_out_dat(act_rva_out_dat),
      .output_port_vld(output_port_vld),
      .output_port_rdy(output_port_rdy),
      .output_port_dat(output_port_dat),
      .done_vld(done_vld),
      .done_rdy(done_rdy),
      .done_dat(done_dat)
    );
endmodule



