// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2_1/1143609 Production Release
//  HLS Date:       Wed Nov 13 18:57:31 PST 2024
//
//  Generated by:   code@iron-05
//  Generated date: Wed Mar 18 19:16:02 2026
// ----------------------------------------------------------------------

//
// ------------------------------------------------------------------
//  Design Unit:    Connections_InBlockingless_spec_GB_Large_DataRspless_1Ugreater_comma_Connections_SYN_PORTgreater_Pop_Connections_InBlocking_spec_GB_Large_DataRsp_1U_Connections_SYN_PORT_Pop_core
// ------------------------------------------------------------------


module Top_GBPartition_GBModule_GBControl_Connections_InBlockingless_spec_GB_Large_DataRspless_1Ugreater_comma_Connections_SYN_PORTgreater_Pop_Connections_InBlocking_spec_GB_Large_DataRsp_1U_Connections_SYN_PORT_Pop_core
    (
  this_vld, this_rdy, this_dat, return_read_vector_data_data_rsc_z, ccs_ccore_start_rsc_dat,
      ccs_ccore_done_sync_vld, ccs_MIO_clk, ccs_MIO_arst
);
  input this_vld;
  output this_rdy;
  reg this_rdy;
  input [127:0] this_dat;
  output [127:0] return_read_vector_data_data_rsc_z;
  input ccs_ccore_start_rsc_dat;
  output ccs_ccore_done_sync_vld;
  input ccs_MIO_clk;
  input ccs_MIO_arst;


  // Interconnect Declarations
  wire ccs_ccore_start_rsci_idat;
  reg io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1;
  wire or_3_cse;
  wire this_rdy_mx0c1;


  // Interconnect Declarations for Component Instantiations
  wire  nl_ccs_ccore_done_synci_ivld;
  assign nl_ccs_ccore_done_synci_ivld = io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1
      & this_vld;
  Top_GBPartition_GBModule_GBControl_Connections_InBlockingless_spec_GB_Large_DataRspless_1Ugreater_comma_Connections_SYN_PORTgreater_Pop_mgc_out_dreg_v2
      #(.rscid(32'sd7),
  .width(32'sd128)) return_read_vector_data_data_rsci (
      .d(this_dat),
      .z(return_read_vector_data_data_rsc_z)
    );
  Top_GBPartition_GBModule_GBControl_Connections_InBlockingless_spec_GB_Large_DataRspless_1Ugreater_comma_Connections_SYN_PORTgreater_Pop_ccs_in_v1
      #(.rscid(32'sd54),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  Top_GBPartition_GBModule_GBControl_Connections_InBlockingless_spec_GB_Large_DataRspless_1Ugreater_comma_Connections_SYN_PORTgreater_Pop_ccs_sync_out_vld_v1
      #(.rscid(32'sd59)) ccs_ccore_done_synci (
      .vld(ccs_ccore_done_sync_vld),
      .ivld(nl_ccs_ccore_done_synci_ivld)
    );
  assign or_3_cse = ccs_ccore_start_rsci_idat | (io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1
      & (~ this_vld));
  assign this_rdy_mx0c1 = io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 & this_vld
      & (~ ccs_ccore_start_rsci_idat);
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      this_rdy <= 1'b0;
    end
    else if ( or_3_cse | this_rdy_mx0c1 ) begin
      this_rdy <= ~ this_rdy_mx0c1;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 <= 1'b0;
    end
    else begin
      io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 <= or_3_cse;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    Connections_InBlocking_spec_GB_Large_DataRsp_1U_Connections_SYN_PORT_Pop
// ------------------------------------------------------------------


module Top_GBPartition_GBModule_GBControl_Connections_InBlocking_spec_GB_Large_DataRsp_1U_Connections_SYN_PORT_Pop (
  this_vld, this_rdy, this_dat, return_read_vector_data_data_rsc_z, ccs_ccore_start_rsc_dat,
      ccs_ccore_done_sync_vld, ccs_MIO_clk, ccs_MIO_arst
);
  input this_vld;
  output this_rdy;
  input [127:0] this_dat;
  output [127:0] return_read_vector_data_data_rsc_z;
  input ccs_ccore_start_rsc_dat;
  output ccs_ccore_done_sync_vld;
  input ccs_MIO_clk;
  input ccs_MIO_arst;



  // Interconnect Declarations for Component Instantiations
  Top_GBPartition_GBModule_GBControl_Connections_InBlockingless_spec_GB_Large_DataRspless_1Ugreater_comma_Connections_SYN_PORTgreater_Pop_Connections_InBlocking_spec_GB_Large_DataRsp_1U_Connections_SYN_PORT_Pop_core
      Connections_InBlocking_spec_GB_Large_DataRsp_1U_Connections_SYN_PORT_Pop_core_inst
      (
      .this_vld(this_vld),
      .this_rdy(this_rdy),
      .this_dat(this_dat),
      .return_read_vector_data_data_rsc_z(return_read_vector_data_data_rsc_z),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_ccore_done_sync_vld(ccs_ccore_done_sync_vld),
      .ccs_MIO_clk(ccs_MIO_clk),
      .ccs_MIO_arst(ccs_MIO_arst)
    );
endmodule



