// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2_1/1143609 Production Release
//  HLS Date:       Wed Nov 13 18:57:31 PST 2024
//
//  Generated by:   code@iron-05
//  Generated date: Wed Mar 18 19:16:00 2026
// ----------------------------------------------------------------------

//
// ------------------------------------------------------------------
//  Design Unit:    Connections_OutBlockingless_spec_StreamTypecomma_Connections_SYN_PORTgreater_Push_Connections_OutBlocking_spec_StreamType_Connections_SYN_PORT_Push_core
// ------------------------------------------------------------------


module Top_GBPartition_GBModule_GBControl_Connections_OutBlockingless_spec_StreamTypecomma_Connections_SYN_PORTgreater_Push_Connections_OutBlocking_spec_StreamType_Connections_SYN_PORT_Push_core
    (
  this_vld, this_rdy, this_dat, m_data_data_rsc_dat, m_index_rsc_dat, m_logical_addr_rsc_dat,
      ccs_ccore_start_rsc_dat, ccs_ccore_done_sync_vld, ccs_MIO_clk, ccs_MIO_arst
);
  output this_vld;
  reg this_vld;
  input this_rdy;
  output [137:0] this_dat;
  input [127:0] m_data_data_rsc_dat;
  input [1:0] m_index_rsc_dat;
  input [7:0] m_logical_addr_rsc_dat;
  input ccs_ccore_start_rsc_dat;
  output ccs_ccore_done_sync_vld;
  input ccs_MIO_clk;
  input ccs_MIO_arst;


  // Interconnect Declarations
  wire [127:0] m_data_data_rsci_idat;
  wire [1:0] m_index_rsci_idat;
  wire [7:0] m_logical_addr_rsci_idat;
  wire ccs_ccore_start_rsci_idat;
  reg [7:0] m_logical_addr_buf_lpi_1_dfm;
  reg m_index_slc_m_index_0_psp_lpi_1_dfm;
  reg [127:0] m_data_data_buf_lpi_1_dfm;
  wire and_dcpl;
  wire or_dcpl_2;
  reg io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1;
  wire or_4_cse;
  wire this_vld_mx0c1;


  // Interconnect Declarations for Component Instantiations
  wire  nl_ccs_ccore_done_synci_ivld;
  assign nl_ccs_ccore_done_synci_ivld = io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1
      & this_rdy;
  Top_GBPartition_GBModule_GBControl_Connections_OutBlockingless_spec_StreamTypecomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd9),
  .width(32'sd128)) m_data_data_rsci (
      .dat(m_data_data_rsc_dat),
      .idat(m_data_data_rsci_idat)
    );
  Top_GBPartition_GBModule_GBControl_Connections_OutBlockingless_spec_StreamTypecomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd10),
  .width(32'sd2)) m_index_rsci (
      .dat(m_index_rsc_dat),
      .idat(m_index_rsci_idat)
    );
  Top_GBPartition_GBModule_GBControl_Connections_OutBlockingless_spec_StreamTypecomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd11),
  .width(32'sd8)) m_logical_addr_rsci (
      .dat(m_logical_addr_rsc_dat),
      .idat(m_logical_addr_rsci_idat)
    );
  Top_GBPartition_GBModule_GBControl_Connections_OutBlockingless_spec_StreamTypecomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd53),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  Top_GBPartition_GBModule_GBControl_Connections_OutBlockingless_spec_StreamTypecomma_Connections_SYN_PORTgreater_Push_ccs_sync_out_vld_v1
      #(.rscid(32'sd58)) ccs_ccore_done_synci (
      .vld(ccs_ccore_done_sync_vld),
      .ivld(nl_ccs_ccore_done_synci_ivld)
    );
  assign this_dat = {m_logical_addr_buf_lpi_1_dfm , 1'b0 , m_index_slc_m_index_0_psp_lpi_1_dfm
      , m_data_data_buf_lpi_1_dfm};
  assign or_4_cse = ccs_ccore_start_rsci_idat | and_dcpl;
  assign and_dcpl = io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 & (~ this_rdy);
  assign or_dcpl_2 = and_dcpl | (~ ccs_ccore_start_rsci_idat);
  assign this_vld_mx0c1 = io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 & this_rdy
      & (~ ccs_ccore_start_rsci_idat);
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      this_vld <= 1'b0;
    end
    else if ( or_4_cse | this_vld_mx0c1 ) begin
      this_vld <= ~ this_vld_mx0c1;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      m_logical_addr_buf_lpi_1_dfm <= 8'b00000000;
    end
    else if ( ~ or_dcpl_2 ) begin
      m_logical_addr_buf_lpi_1_dfm <= m_logical_addr_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      m_index_slc_m_index_0_psp_lpi_1_dfm <= 1'b0;
    end
    else if ( ~ or_dcpl_2 ) begin
      m_index_slc_m_index_0_psp_lpi_1_dfm <= m_index_rsci_idat[0];
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      m_data_data_buf_lpi_1_dfm <= 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    end
    else if ( ~ or_dcpl_2 ) begin
      m_data_data_buf_lpi_1_dfm <= m_data_data_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 <= 1'b0;
    end
    else begin
      io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 <= or_4_cse;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    Connections_OutBlocking_spec_StreamType_Connections_SYN_PORT_Push
// ------------------------------------------------------------------


module Top_GBPartition_GBModule_GBControl_Connections_OutBlocking_spec_StreamType_Connections_SYN_PORT_Push (
  this_vld, this_rdy, this_dat, m_data_data_rsc_dat, m_index_rsc_dat, m_logical_addr_rsc_dat,
      ccs_ccore_start_rsc_dat, ccs_ccore_done_sync_vld, ccs_MIO_clk, ccs_MIO_arst
);
  output this_vld;
  input this_rdy;
  output [137:0] this_dat;
  input [127:0] m_data_data_rsc_dat;
  input [1:0] m_index_rsc_dat;
  input [7:0] m_logical_addr_rsc_dat;
  input ccs_ccore_start_rsc_dat;
  output ccs_ccore_done_sync_vld;
  input ccs_MIO_clk;
  input ccs_MIO_arst;



  // Interconnect Declarations for Component Instantiations
  Top_GBPartition_GBModule_GBControl_Connections_OutBlockingless_spec_StreamTypecomma_Connections_SYN_PORTgreater_Push_Connections_OutBlocking_spec_StreamType_Connections_SYN_PORT_Push_core
      Connections_OutBlocking_spec_StreamType_Connections_SYN_PORT_Push_core_inst
      (
      .this_vld(this_vld),
      .this_rdy(this_rdy),
      .this_dat(this_dat),
      .m_data_data_rsc_dat(m_data_data_rsc_dat),
      .m_index_rsc_dat(m_index_rsc_dat),
      .m_logical_addr_rsc_dat(m_logical_addr_rsc_dat),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_ccore_done_sync_vld(ccs_ccore_done_sync_vld),
      .ccs_MIO_clk(ccs_MIO_clk),
      .ccs_MIO_arst(ccs_MIO_arst)
    );
endmodule



