// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2024.2_1/1143609 Production Release
//       HLS date: Wed Nov 13 18:57:31 PST 2024
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: code@iron-05
// Generated date: Wed Mar 18 19:20:20 PDT 2026
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model GBModule
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Constructor: sysc_sim_wrapper

CCS_RTL::sysc_sim_wrapper::sysc_sim_wrapper(
   const sc_module_name& nm
)
   : ccs_rtl(
      "ccs_rtl",
      "ccs_wrapper"
   )
   , clk("clk")
   , rst("rst")
   , rva_in("rva_in")
   , rva_out("rva_out")
   , data_in("data_in")
   , data_out("data_out")
   , pe_start("pe_start")
   , pe_done("pe_done")
   , gb_done("gb_done")
   , ccs_rtl_SIG_clk("ccs_rtl_SIG_clk")
   , ccs_rtl_SIG_rst("ccs_rtl_SIG_rst")
   , ccs_rtl_SIG_rva_in_vld("ccs_rtl_SIG_rva_in_vld")
   , ccs_rtl_SIG_rva_in_rdy("ccs_rtl_SIG_rva_in_rdy")
   , ccs_rtl_SIG_rva_in_dat("ccs_rtl_SIG_rva_in_dat")
   , ccs_rtl_SIG_rva_out_vld("ccs_rtl_SIG_rva_out_vld")
   , ccs_rtl_SIG_rva_out_rdy("ccs_rtl_SIG_rva_out_rdy")
   , ccs_rtl_SIG_rva_out_dat("ccs_rtl_SIG_rva_out_dat")
   , ccs_rtl_SIG_data_in_vld("ccs_rtl_SIG_data_in_vld")
   , ccs_rtl_SIG_data_in_rdy("ccs_rtl_SIG_data_in_rdy")
   , ccs_rtl_SIG_data_in_dat("ccs_rtl_SIG_data_in_dat")
   , ccs_rtl_SIG_data_out_vld("ccs_rtl_SIG_data_out_vld")
   , ccs_rtl_SIG_data_out_rdy("ccs_rtl_SIG_data_out_rdy")
   , ccs_rtl_SIG_data_out_dat("ccs_rtl_SIG_data_out_dat")
   , ccs_rtl_SIG_pe_start_vld("ccs_rtl_SIG_pe_start_vld")
   , ccs_rtl_SIG_pe_start_rdy("ccs_rtl_SIG_pe_start_rdy")
   , ccs_rtl_SIG_pe_start_dat("ccs_rtl_SIG_pe_start_dat")
   , ccs_rtl_SIG_pe_done_vld("ccs_rtl_SIG_pe_done_vld")
   , ccs_rtl_SIG_pe_done_rdy("ccs_rtl_SIG_pe_done_rdy")
   , ccs_rtl_SIG_pe_done_dat("ccs_rtl_SIG_pe_done_dat")
   , ccs_rtl_SIG_gb_done_vld("ccs_rtl_SIG_gb_done_vld")
   , ccs_rtl_SIG_gb_done_rdy("ccs_rtl_SIG_gb_done_rdy")
   , ccs_rtl_SIG_gb_done_dat("ccs_rtl_SIG_gb_done_dat")
   , SIG_SC_LOGIC_0("SIG_SC_LOGIC_0")
   , SIG_SC_LOGIC_1("SIG_SC_LOGIC_1")
{
   // Instantiate other modules
   ccs_rtl.clk(ccs_rtl_SIG_clk);
   ccs_rtl.rst(ccs_rtl_SIG_rst);
   ccs_rtl.rva_in_vld(ccs_rtl_SIG_rva_in_vld);
   ccs_rtl.rva_in_rdy(ccs_rtl_SIG_rva_in_rdy);
   ccs_rtl.rva_in_dat(ccs_rtl_SIG_rva_in_dat);
   ccs_rtl.rva_out_vld(ccs_rtl_SIG_rva_out_vld);
   ccs_rtl.rva_out_rdy(ccs_rtl_SIG_rva_out_rdy);
   ccs_rtl.rva_out_dat(ccs_rtl_SIG_rva_out_dat);
   ccs_rtl.data_in_vld(ccs_rtl_SIG_data_in_vld);
   ccs_rtl.data_in_rdy(ccs_rtl_SIG_data_in_rdy);
   ccs_rtl.data_in_dat(ccs_rtl_SIG_data_in_dat);
   ccs_rtl.data_out_vld(ccs_rtl_SIG_data_out_vld);
   ccs_rtl.data_out_rdy(ccs_rtl_SIG_data_out_rdy);
   ccs_rtl.data_out_dat(ccs_rtl_SIG_data_out_dat);
   ccs_rtl.pe_start_vld(ccs_rtl_SIG_pe_start_vld);
   ccs_rtl.pe_start_rdy(ccs_rtl_SIG_pe_start_rdy);
   ccs_rtl.pe_start_dat(ccs_rtl_SIG_pe_start_dat);
   ccs_rtl.pe_done_vld(ccs_rtl_SIG_pe_done_vld);
   ccs_rtl.pe_done_rdy(ccs_rtl_SIG_pe_done_rdy);
   ccs_rtl.pe_done_dat(ccs_rtl_SIG_pe_done_dat);
   ccs_rtl.gb_done_vld(ccs_rtl_SIG_gb_done_vld);
   ccs_rtl.gb_done_rdy(ccs_rtl_SIG_gb_done_rdy);
   ccs_rtl.gb_done_dat(ccs_rtl_SIG_gb_done_dat);
   
   // Register processes
   SC_METHOD(update_proc);
   sensitive  << clk << rst << rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::vld << ccs_rtl_SIG_rva_in_rdy << rva_in.Connections::InBlocking<RVSink<spec::Axi::rvaCfg >::Write, Connections::SYN_PORT >::dat << ccs_rtl_SIG_rva_out_vld << rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::rdy << ccs_rtl_SIG_rva_out_dat << data_in.Connections::InBlocking_Ports_abs<spec::StreamType >::vld << ccs_rtl_SIG_data_in_rdy << data_in.Connections::InBlocking<spec::StreamType, Connections::SYN_PORT >::dat << ccs_rtl_SIG_data_out_vld << data_out.Connections::OutBlocking_Ports_abs<spec::StreamType >::rdy << ccs_rtl_SIG_data_out_dat << ccs_rtl_SIG_pe_start_vld << pe_start.Connections::OutBlocking_Ports_abs<bool >::rdy << ccs_rtl_SIG_pe_start_dat << pe_done.Connections::InBlocking_Ports_abs<bool >::vld << ccs_rtl_SIG_pe_done_rdy << pe_done.Connections::InBlocking<bool, Connections::SYN_PORT >::dat << ccs_rtl_SIG_gb_done_vld << gb_done.Connections::OutBlocking_Ports_abs<bool >::rdy << ccs_rtl_SIG_gb_done_dat;
   // Other constructor statements
   SIG_SC_LOGIC_0.write(SC_LOGIC_0);
   SIG_SC_LOGIC_1.write(SC_LOGIC_1);
}

// ---------------------------------------------------------------
// Process: SC_METHOD update_proc

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   
   // none.sc_in field_key=clk:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2977:clk:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2977
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2977; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2978:rst:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2978
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2978; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2978); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2978); // then write to RTL port
   
   // none.sc_in field_key=rva_in:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2984:vld:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2995
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2995; // NPS - LV to hold field
   type_to_vector(rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::vld.read(),1,t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2995); // read orig port and type convert
   ccs_rtl_SIG_rva_in_vld.write(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2995); // then write to RTL port
   
   // none.sc_out field_key=rva_in:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2984:rdy:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2996
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2996;
   bool d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2996;
   t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2996 = ccs_rtl_SIG_rva_in_rdy.read();
   vector_to_type(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2996, 1, &d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2996);
   rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::rdy.write(d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2996);
   
   // none.sc_in field_key=rva_in:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2984:dat:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2997
   sc_lv< 169 > t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2997; // NPS - LV to hold field
   type_to_vector(rva_in.Connections::InBlocking<RVSink<spec::Axi::rvaCfg >::Write, Connections::SYN_PORT >::dat.read(),169,t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2997); // read orig port and type convert
   ccs_rtl_SIG_rva_in_dat.write(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_2997); // then write to RTL port
   
   // none.sc_out field_key=rva_out:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2998:vld:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3007
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3007;
   bool d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3007;
   t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3007 = ccs_rtl_SIG_rva_out_vld.read();
   vector_to_type(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3007, 1, &d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3007);
   rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::vld.write(d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3007);
   
   // none.sc_in field_key=rva_out:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2998:rdy:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3008
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3008; // NPS - LV to hold field
   type_to_vector(rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::rdy.read(),1,t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3008); // read orig port and type convert
   ccs_rtl_SIG_rva_out_rdy.write(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3008); // then write to RTL port
   
   // none.sc_out field_key=rva_out:4df7a90c-69e8-47f4-bbf4-932613fd7c20-2998:dat:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3009
   sc_lv< 128 > t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3009;
   sc_dt::sc_lv<128 > d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3009;
   t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3009 = ccs_rtl_SIG_rva_out_dat.read();
   vector_to_type(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3009, 128, &d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3009);
   rva_out.Connections::OutBlocking<RVSink<spec::Axi::rvaCfg >::Read, Connections::SYN_PORT >::dat.write(d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3009);
   
   // none.sc_in field_key=data_in:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3010:vld:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3019
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3019; // NPS - LV to hold field
   type_to_vector(data_in.Connections::InBlocking_Ports_abs<spec::StreamType >::vld.read(),1,t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3019); // read orig port and type convert
   ccs_rtl_SIG_data_in_vld.write(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3019); // then write to RTL port
   
   // none.sc_out field_key=data_in:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3010:rdy:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3020
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3020;
   bool d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3020;
   t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3020 = ccs_rtl_SIG_data_in_rdy.read();
   vector_to_type(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3020, 1, &d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3020);
   data_in.Connections::InBlocking_Ports_abs<spec::StreamType >::rdy.write(d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3020);
   
   // none.sc_in field_key=data_in:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3010:dat:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3021
   sc_lv< 138 > t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3021; // NPS - LV to hold field
   type_to_vector(data_in.Connections::InBlocking<spec::StreamType, Connections::SYN_PORT >::dat.read(),138,t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3021); // read orig port and type convert
   ccs_rtl_SIG_data_in_dat.write(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3021); // then write to RTL port
   
   // none.sc_out field_key=data_out:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3022:vld:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3031
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3031;
   bool d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3031;
   t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3031 = ccs_rtl_SIG_data_out_vld.read();
   vector_to_type(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3031, 1, &d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3031);
   data_out.Connections::OutBlocking_Ports_abs<spec::StreamType >::vld.write(d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3031);
   
   // none.sc_in field_key=data_out:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3022:rdy:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3032
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3032; // NPS - LV to hold field
   type_to_vector(data_out.Connections::OutBlocking_Ports_abs<spec::StreamType >::rdy.read(),1,t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3032); // read orig port and type convert
   ccs_rtl_SIG_data_out_rdy.write(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3032); // then write to RTL port
   
   // none.sc_out field_key=data_out:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3022:dat:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3033
   sc_lv< 138 > t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3033;
   sc_dt::sc_lv<138 > d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3033;
   t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3033 = ccs_rtl_SIG_data_out_dat.read();
   vector_to_type(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3033, 138, &d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3033);
   data_out.Connections::OutBlocking<spec::StreamType, Connections::SYN_PORT >::dat.write(d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3033);
   
   // none.sc_out field_key=pe_start:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3034:vld:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3043
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3043;
   bool d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3043;
   t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3043 = ccs_rtl_SIG_pe_start_vld.read();
   vector_to_type(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3043, 1, &d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3043);
   pe_start.Connections::OutBlocking_Ports_abs<bool >::vld.write(d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3043);
   
   // none.sc_in field_key=pe_start:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3034:rdy:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3044
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3044; // NPS - LV to hold field
   type_to_vector(pe_start.Connections::OutBlocking_Ports_abs<bool >::rdy.read(),1,t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3044); // read orig port and type convert
   ccs_rtl_SIG_pe_start_rdy.write(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3044); // then write to RTL port
   
   // none.sc_out field_key=pe_start:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3034:dat:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3045
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3045;
   sc_dt::sc_lv<1 > d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3045;
   t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3045 = ccs_rtl_SIG_pe_start_dat.read();
   vector_to_type(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3045, 1, &d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3045);
   pe_start.Connections::OutBlocking<bool, Connections::SYN_PORT >::dat.write(d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3045);
   
   // none.sc_in field_key=pe_done:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3046:vld:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3055
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3055; // NPS - LV to hold field
   type_to_vector(pe_done.Connections::InBlocking_Ports_abs<bool >::vld.read(),1,t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3055); // read orig port and type convert
   ccs_rtl_SIG_pe_done_vld.write(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3055); // then write to RTL port
   
   // none.sc_out field_key=pe_done:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3046:rdy:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3056
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3056;
   bool d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3056;
   t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3056 = ccs_rtl_SIG_pe_done_rdy.read();
   vector_to_type(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3056, 1, &d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3056);
   pe_done.Connections::InBlocking_Ports_abs<bool >::rdy.write(d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3056);
   
   // none.sc_in field_key=pe_done:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3046:dat:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3057
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3057; // NPS - LV to hold field
   type_to_vector(pe_done.Connections::InBlocking<bool, Connections::SYN_PORT >::dat.read(),1,t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3057); // read orig port and type convert
   ccs_rtl_SIG_pe_done_dat.write(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3057); // then write to RTL port
   
   // none.sc_out field_key=gb_done:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3058:vld:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3063
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3063;
   bool d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3063;
   t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3063 = ccs_rtl_SIG_gb_done_vld.read();
   vector_to_type(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3063, 1, &d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3063);
   gb_done.Connections::OutBlocking_Ports_abs<bool >::vld.write(d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3063);
   
   // none.sc_in field_key=gb_done:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3058:rdy:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3064
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3064; // NPS - LV to hold field
   type_to_vector(gb_done.Connections::OutBlocking_Ports_abs<bool >::rdy.read(),1,t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3064); // read orig port and type convert
   ccs_rtl_SIG_gb_done_rdy.write(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3064); // then write to RTL port
   
   // none.sc_out field_key=gb_done:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3058:dat:4df7a90c-69e8-47f4-bbf4-932613fd7c20-3065
   sc_logic t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3065;
   sc_dt::sc_lv<1 > d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3065;
   t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3065 = ccs_rtl_SIG_gb_done_dat.read();
   vector_to_type(t_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3065, 1, &d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3065);
   gb_done.Connections::OutBlocking<bool, Connections::SYN_PORT >::dat.write(d_4df7a90c_69e8_47f4_bbf4_932613fd7c20_3065);
}
