// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2_1/1143609 Production Release
//  HLS Date:       Wed Nov 13 18:57:31 PST 2024
//
//  Generated by:   code@iron-06
//  Generated date: Sun Feb 22 18:58:47 2026
// ----------------------------------------------------------------------

//
// ------------------------------------------------------------------
//  Design Unit:    leading_sign_40_0
// ------------------------------------------------------------------


module NMP_leading_sign_40_0 (
  mantissa, rtn
);
  input [39:0] mantissa;
  output [5:0] rtn;


  // Interconnect Declarations
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_6_2_sdt_2;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_18_3_sdt_3;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_26_2_sdt_2;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_42_4_sdt_4;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_50_2_sdt_2;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_62_3_sdt_3;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_70_2_sdt_2;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_90_5_sdt_5;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_98_2_sdt_2;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_6_2_sdt_1;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_14_2_sdt_1;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_26_2_sdt_1;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_34_2_sdt_1;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_50_2_sdt_1;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_58_2_sdt_1;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_70_2_sdt_1;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_78_2_sdt_1;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_98_2_sdt_1;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_106_2_sdt_1;
  wire c_h_1_2;
  wire c_h_1_5;
  wire c_h_1_6;
  wire c_h_1_9;
  wire c_h_1_12;
  wire c_h_1_13;
  wire c_h_1_14;
  wire c_h_1_17;
  wire c_h_1_18;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_and_155_ssc;

  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_and_nl;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_or_1_nl;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_and_2_nl;
  wire[1:0] ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leadi000000;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_nand_nl;
  wire ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_nand_10_nl;

  // Interconnect Declarations for Component Instantiations
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_6_2_sdt_2
      = ~((mantissa[37:36]!=2'b00));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_6_2_sdt_1
      = ~((mantissa[39:38]!=2'b00));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_14_2_sdt_1
      = ~((mantissa[35:34]!=2'b00));
  assign c_h_1_2 = ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_6_2_sdt_1
      & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_6_2_sdt_2;
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_18_3_sdt_3
      = (mantissa[33:32]==2'b00) & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_14_2_sdt_1;
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_26_2_sdt_2
      = ~((mantissa[29:28]!=2'b00));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_26_2_sdt_1
      = ~((mantissa[31:30]!=2'b00));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_34_2_sdt_1
      = ~((mantissa[27:26]!=2'b00));
  assign c_h_1_5 = ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_26_2_sdt_1
      & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_26_2_sdt_2;
  assign c_h_1_6 = c_h_1_2 & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_18_3_sdt_3;
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_42_4_sdt_4
      = (mantissa[25:24]==2'b00) & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_34_2_sdt_1
      & c_h_1_5;
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_50_2_sdt_2
      = ~((mantissa[21:20]!=2'b00));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_50_2_sdt_1
      = ~((mantissa[23:22]!=2'b00));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_58_2_sdt_1
      = ~((mantissa[19:18]!=2'b00));
  assign c_h_1_9 = ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_50_2_sdt_1
      & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_50_2_sdt_2;
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_62_3_sdt_3
      = (mantissa[17:16]==2'b00) & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_58_2_sdt_1;
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_70_2_sdt_2
      = ~((mantissa[13:12]!=2'b00));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_70_2_sdt_1
      = ~((mantissa[15:14]!=2'b00));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_78_2_sdt_1
      = ~((mantissa[11:10]!=2'b00));
  assign c_h_1_12 = ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_70_2_sdt_1
      & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_70_2_sdt_2;
  assign c_h_1_13 = c_h_1_9 & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_62_3_sdt_3;
  assign c_h_1_14 = c_h_1_6 & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_42_4_sdt_4;
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_90_5_sdt_5
      = (mantissa[9:8]==2'b00) & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_78_2_sdt_1
      & c_h_1_12 & c_h_1_13;
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_98_2_sdt_2
      = ~((mantissa[5:4]!=2'b00));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_98_2_sdt_1
      = ~((mantissa[7:6]!=2'b00));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_106_2_sdt_1
      = ~((mantissa[3:2]!=2'b00));
  assign c_h_1_17 = ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_98_2_sdt_1
      & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_98_2_sdt_2;
  assign c_h_1_18 = c_h_1_14 & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_90_5_sdt_5;
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_and_155_ssc
      = (mantissa[1:0]==2'b00) & ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_106_2_sdt_1
      & c_h_1_17 & c_h_1_18;
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_and_nl
      = c_h_1_14 & (~ ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_90_5_sdt_5);
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_or_1_nl
      = (c_h_1_6 & (c_h_1_13 | (~ ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_42_4_sdt_4))
      & (~ c_h_1_18)) | ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_and_155_ssc;
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_and_2_nl
      = c_h_1_2 & (c_h_1_5 | (~ ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_18_3_sdt_3))
      & (~((~(c_h_1_9 & (c_h_1_12 | (~ ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_62_3_sdt_3))))
      & c_h_1_14)) & (c_h_1_17 | (~ c_h_1_18)) & (~ ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_and_155_ssc);
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_nand_nl
      = ~(ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_6_2_sdt_1
      & (ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_14_2_sdt_1
      | (~ ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_6_2_sdt_2))
      & (~((~(ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_26_2_sdt_1
      & (ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_34_2_sdt_1
      | (~ ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_26_2_sdt_2))))
      & c_h_1_6)) & (~((~(ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_50_2_sdt_1
      & (ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_58_2_sdt_1
      | (~ ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_50_2_sdt_2))
      & (~((~(ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_70_2_sdt_1
      & (ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_78_2_sdt_1
      | (~ ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_70_2_sdt_2))))
      & c_h_1_13)))) & c_h_1_14)) & (~((~(ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_98_2_sdt_1
      & (ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_106_2_sdt_1
      | (~ ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_wrs_c_98_2_sdt_2))))
      & c_h_1_18)));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_nand_10_nl
      = ~((~((mantissa[39]) | (~((mantissa[38:37]!=2'b01))))) & (~(((mantissa[35])
      | (~((mantissa[34:33]!=2'b01)))) & c_h_1_2)) & (~((~((~((mantissa[31]) | (~((mantissa[30:29]!=2'b01)))))
      & (~(((mantissa[27]) | (~((mantissa[26:25]!=2'b01)))) & c_h_1_5)))) & c_h_1_6))
      & (~((~((~((mantissa[23]) | (~((mantissa[22:21]!=2'b01))))) & (~(((mantissa[19])
      | (~((mantissa[18:17]!=2'b01)))) & c_h_1_9)) & (~((~((~((mantissa[15]) | (~((mantissa[14:13]!=2'b01)))))
      & (~(((mantissa[11]) | (~((mantissa[10:9]!=2'b01)))) & c_h_1_12)))) & c_h_1_13))))
      & c_h_1_14)) & (~((~((~((mantissa[7]) | (~((mantissa[6:5]!=2'b01))))) & (~(((mantissa[3])
      | (~((mantissa[2:1]!=2'b01)))) & c_h_1_17)))) & c_h_1_18)));
  assign ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leadi000000
      = ~(MUX_v_2_2_2(({ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_nand_nl
      , ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_nand_10_nl}),
      2'b11, ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_and_155_ssc));
  assign rtn = {c_h_1_18 , ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_and_nl
      , ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_or_1_nl
      , ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_and_2_nl
      , ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leading_sign_40_0_rtn_ac_math_ac_normalize_40_16_false_AC_TRN_AC_WRAP_leading_1_leadi000000};

  function automatic [1:0] MUX_v_2_2_2;
    input [1:0] input_0;
    input [1:0] input_1;
    input  sel;
    reg [1:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = input_0;
      end
      default : begin
        result = input_1;
      end
    endcase
    MUX_v_2_2_2 = result;
  end
  endfunction

endmodule



