directive set /NMP/NMP:NMPRun/NMPRun/NMP::ComputeRMSNormalize:for:asn#16.itm.8 REGISTER_NAME NMP::ComputeRMSNormalize:for:asn#16.itm.8
directive set /NMP/NMP:NMPRun/NMPRun/ac_math::ac_normalize<40,16,false,AC_TRN,AC_WRAP>#2:leading_1(5:0).sva.1 REGISTER_NAME NMP::ComputeRMSNormalize:for:asn#16.itm.8
directive set /NMP/NMP:NMPRun/NMPRun/ac_math::ac_sqrt_pwl<AC_TRN,40,16,AC_TRN,AC_WRAP,40,16,AC_TRN,AC_WRAP>:_qr.sva.1(38:0) REGISTER_NAME ac_math::ac_sqrt_pwl<AC_TRN,40,16,AC_TRN,AC_WRAP,40,16,AC_TRN,AC_WRAP>:_qr.sva.1(38:0)
directive set /NMP/NMP:NMPRun/NMPRun/NMP::ComputeSoftmaxNormalize:for:asn#17.itm.2 REGISTER_NAME ac_math::ac_sqrt_pwl<AC_TRN,40,16,AC_TRN,AC_WRAP,40,16,AC_TRN,AC_WRAP>:_qr.sva.1(38:0)
directive set /NMP/NMP:NMPRun/NMPRun/ac_math::ac_sqrt_pwl<AC_TRN,40,16,AC_TRN,AC_WRAP,40,16,AC_TRN,AC_WRAP>:normalized_output(24:12).sva.1 REGISTER_NAME ac_math::ac_sqrt_pwl<AC_TRN,40,16,AC_TRN,AC_WRAP,40,16,AC_TRN,AC_WRAP>:normalized_output(24:12).sva.1
directive set /NMP/NMP:NMPRun/NMPRun/NMP::ComputeRMSNormalize:for:asn#16.itm.6 REGISTER_NAME ac_math::ac_sqrt_pwl<AC_TRN,40,16,AC_TRN,AC_WRAP,40,16,AC_TRN,AC_WRAP>:normalized_output(24:12).sva.1
directive set /NMP/NMP:NMPRun/NMPRun/ac_math::ac_normalize<40,16,false,AC_TRN,AC_WRAP>:normalized_fixed_temp:slc(ac_math::ac_normalize<40,16,false,AC_TRN,AC_WRAP>:normalized_fixed_temp(38:25))(11-0).itm.1 REGISTER_NAME ac_math::ac_normalize<40,16,false,AC_TRN,AC_WRAP>:normalized_fixed_temp:slc(ac_math::ac_normalize<40,16,false,AC_TRN,AC_WRAP>:normalized_fixed_temp(38:25))(11-0).itm.1
directive set /NMP/NMP:NMPRun/NMPRun/NMP::ComputeRMSNormalize:for:asn#16.itm.4 REGISTER_NAME ac_math::ac_normalize<40,16,false,AC_TRN,AC_WRAP>:normalized_fixed_temp:slc(ac_math::ac_normalize<40,16,false,AC_TRN,AC_WRAP>:normalized_fixed_temp(38:25))(11-0).itm.1
directive set /NMP/NMP:NMPRun/NMPRun/ac_math::ac_sqrt_pwl<AC_TRN,40,16,AC_TRN,AC_WRAP,40,16,AC_TRN,AC_WRAP>:normalized_output:mux#1.itm.1 REGISTER_NAME ac_math::ac_sqrt_pwl<AC_TRN,40,16,AC_TRN,AC_WRAP,40,16,AC_TRN,AC_WRAP>:normalized_output:mux#1.itm.1
directive set /NMP/NMP:NMPRun/NMPRun/NMP::ComputeRMSNormalize:for:asn#18.itm.4 REGISTER_NAME ac_math::ac_sqrt_pwl<AC_TRN,40,16,AC_TRN,AC_WRAP,40,16,AC_TRN,AC_WRAP>:normalized_output:mux#1.itm.1
directive set /NMP/NMP:NMPRun/NMPRun/NMP::ComputeRMSNormalize:for:asn#20.itm.4 REGISTER_NAME NMP::ComputeRMSNormalize:for:asn#20.itm.4
directive set /NMP/NMP:NMPRun/NMPRun/ac_math::ac_sqrt_pwl<AC_TRN,40,16,AC_TRN,AC_WRAP,40,16,AC_TRN,AC_WRAP>:normalized_output:mux.itm.1 REGISTER_NAME NMP::ComputeRMSNormalize:for:asn#20.itm.4
directive set /NMP/NMP:NMPRun/NMPRun/NMP::ComputeRMSNormalize:for:asn#16.itm.3 REGISTER_NAME NMP::ComputeRMSNormalize:for:asn#16.itm.3
directive set /NMP/NMP:NMPRun/NMPRun/ac_math::ac_normalize<40,16,false,AC_TRN,AC_WRAP>:leading_1(5:0).sva.1 REGISTER_NAME NMP::ComputeRMSNormalize:for:asn#16.itm.3
directive set /NMP/NMP:NMPRun/NMPRun/NMP::PrepareReadReq:slc(nmp_config.memory_index_1)(1-0).itm.1 REGISTER_NAME NMP::PrepareReadReq:slc(nmp_config.memory_index_1)(1-0).itm.1
directive set /NMP/NMP:NMPRun/NMPRun/NMP::PrepareWriteReq:slc(nmp_config.memory_index_1)(1-0).itm.1 REGISTER_NAME NMP::PrepareReadReq:slc(nmp_config.memory_index_1)(1-0).itm.1
directive set /NMP/NMP:NMPRun/NMPRun/rva_out_reg.data(0).sva REGISTER_NAME rva_out_reg.data(0).sva
directive set /NMP/NMP:NMPRun/NMPRun/rva_out_reg.data(0).sva.dfm#3.1 REGISTER_NAME rva_out_reg.data(0).sva
directive set /NMP/NMP:NMPRun/NMPRun/rva_out_reg.data(79:64).sva REGISTER_NAME rva_out_reg.data(79:64).sva
directive set /NMP/NMP:NMPRun/NMPRun/rva_out_reg.data(79:64).sva.dfm#3.1 REGISTER_NAME rva_out_reg.data(79:64).sva
directive set /NMP/NMP:NMPRun/NMPRun/rva_out_reg.data(10:8).sva REGISTER_NAME rva_out_reg.data(10:8).sva
directive set /NMP/NMP:NMPRun/NMPRun/rva_out_reg.data(10:8).sva.dfm#3.1 REGISTER_NAME rva_out_reg.data(10:8).sva
directive set /NMP/NMP:NMPRun/NMPRun/rva_out_reg.data(55:48).sva REGISTER_NAME rva_out_reg.data(55:48).sva
directive set /NMP/NMP:NMPRun/NMPRun/rva_out_reg.data(55:48).sva.dfm#3.1 REGISTER_NAME rva_out_reg.data(55:48).sva
directive set /NMP/NMP:NMPRun/NMPRun/rva_out_reg.data(34:32).sva REGISTER_NAME rva_out_reg.data(34:32).sva
directive set /NMP/NMP:NMPRun/NMPRun/rva_out_reg.data(34:32).sva.dfm#3.1 REGISTER_NAME rva_out_reg.data(34:32).sva
