// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2_1/1143609 Production Release
//  HLS Date:       Wed Nov 13 18:57:31 PST 2024
//
//  Generated by:   code@iron-06
//  Generated date: Sun Feb 22 19:14:27 2026
// ----------------------------------------------------------------------

//
// ------------------------------------------------------------------
//  Design Unit:    Connections_InBlockingless_AxiSubordinateToReadyValidless_spec_Axi_axiCfgcomma_spec_Axi_rvaCfggreater_Readcomma_Connections_SYN_PORTgreater_PopNB_Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_R000000
// ------------------------------------------------------------------


module GBPartition_Connections_InBlockingless_AxiSubordinateToReadyValidless_spec_Axi_axiCfgcomma_spec_Axi_rvaCfggreater_Readcomma_Connections_SYN_PORTgreater_PopNB_Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_000000
    (
  this_vld, this_rdy, this_dat, data_data_rsc_z, return_rsc_z, ccs_ccore_start_rsc_dat,
      ccs_MIO_clk, ccs_MIO_arst
);
  input this_vld;
  output this_rdy;
  reg this_rdy;
  input [127:0] this_dat;
  output [127:0] data_data_rsc_z;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;


  // Interconnect Declarations
  wire ccs_ccore_start_rsci_idat;
  reg asn_itm_1;


  // Interconnect Declarations for Component Instantiations
  GBPartition_Connections_InBlockingless_AxiSubordinateToReadyValidless_spec_Axi_axiCfgcomma_spec_Axi_rvaCfggreater_Readcomma_Connections_SYN_PORTgreater_PopNB_mgc_out_dreg_v2
      #(.rscid(32'sd192),
  .width(32'sd128)) data_data_rsci (
      .d(this_dat),
      .z(data_data_rsc_z)
    );
  GBPartition_Connections_InBlockingless_AxiSubordinateToReadyValidless_spec_Axi_axiCfgcomma_spec_Axi_rvaCfggreater_Readcomma_Connections_SYN_PORTgreater_PopNB_mgc_out_dreg_v2
      #(.rscid(32'sd194),
  .width(32'sd1)) return_rsci (
      .d(this_vld),
      .z(return_rsc_z)
    );
  GBPartition_Connections_InBlockingless_AxiSubordinateToReadyValidless_spec_Axi_axiCfgcomma_spec_Axi_rvaCfggreater_Readcomma_Connections_SYN_PORTgreater_PopNB_ccs_in_v1
      #(.rscid(32'sd221),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      this_rdy <= 1'b0;
    end
    else if ( ccs_ccore_start_rsci_idat | asn_itm_1 ) begin
      this_rdy <= ccs_ccore_start_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      asn_itm_1 <= 1'b0;
    end
    else begin
      asn_itm_1 <= ccs_ccore_start_rsci_idat;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Read_Connections_SYN_PORT_PopNB
// ------------------------------------------------------------------


module GBPartition_Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Read_Connections_SYN_PORT_PopNB
    (
  this_vld, this_rdy, this_dat, data_data_rsc_z, return_rsc_z, ccs_ccore_start_rsc_dat,
      ccs_MIO_clk, ccs_MIO_arst
);
  input this_vld;
  output this_rdy;
  input [127:0] this_dat;
  output [127:0] data_data_rsc_z;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;



  // Interconnect Declarations for Component Instantiations
  GBPartition_Connections_InBlockingless_AxiSubordinateToReadyValidless_spec_Axi_axiCfgcomma_spec_Axi_rvaCfggreater_Readcomma_Connections_SYN_PORTgreater_PopNB_Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_000000
      Connections_InBlocking_AxiSubordinateToReadyValid_spec_Axi_axiCfg_spec_Axi_rvaCfg_Read_Connections_SYN_PORT_PopNB_core_inst
      (
      .this_vld(this_vld),
      .this_rdy(this_rdy),
      .this_dat(this_dat),
      .data_data_rsc_z(data_data_rsc_z),
      .return_rsc_z(return_rsc_z),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_MIO_clk(ccs_MIO_clk),
      .ccs_MIO_arst(ccs_MIO_arst)
    );
endmodule



