// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2_1/1143609 Production Release
//  HLS Date:       Wed Nov 13 18:57:31 PST 2024
//
//  Generated by:   code@iron-06
//  Generated date: Sun Feb 22 19:03:35 2026
// ----------------------------------------------------------------------

//
// ------------------------------------------------------------------
//  Design Unit:    Connections_InBlockingless_spec_GB_Large_DataReqcomma_Connections_SYN_PORTgreater_PopNB_Connections_InBlocking_spec_GB_Large_DataReq_Connections_SYN_PORT_PopNB_core
// ------------------------------------------------------------------


module GBCore_Connections_InBlockingless_spec_GB_Large_DataReqcomma_Connections_SYN_PORTgreater_PopNB_Connections_InBlocking_spec_GB_Large_DataReq_Connections_SYN_PORT_PopNB_core
    (
  this_vld, this_rdy, this_dat, data_is_write_rsc_z, data_memory_index_rsc_z, data_vector_index_rsc_z,
      data_timestep_index_rsc_z, data_write_data_data_rsc_z, return_rsc_z, ccs_ccore_start_rsc_dat,
      ccs_MIO_clk, ccs_MIO_arst
);
  input this_vld;
  output this_rdy;
  reg this_rdy;
  input [154:0] this_dat;
  output data_is_write_rsc_z;
  output [1:0] data_memory_index_rsc_z;
  output [7:0] data_vector_index_rsc_z;
  output [15:0] data_timestep_index_rsc_z;
  output [127:0] data_write_data_data_rsc_z;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;


  // Interconnect Declarations
  wire ccs_ccore_start_rsci_idat;
  reg asn_itm_1;


  // Interconnect Declarations for Component Instantiations
  wire  nl_data_is_write_rsci_d;
  assign nl_data_is_write_rsci_d = this_dat[0];
  wire [1:0] nl_data_memory_index_rsci_d;
  assign nl_data_memory_index_rsci_d = this_dat[2:1];
  wire [7:0] nl_data_vector_index_rsci_d;
  assign nl_data_vector_index_rsci_d = this_dat[26:19];
  wire [15:0] nl_data_timestep_index_rsci_d;
  assign nl_data_timestep_index_rsci_d = this_dat[18:3];
  wire [127:0] nl_data_write_data_data_rsci_d;
  assign nl_data_write_data_data_rsci_d = this_dat[154:27];
  GBCore_Connections_InBlockingless_spec_GB_Large_DataReqcomma_Connections_SYN_PORTgreater_PopNB_mgc_out_dreg_v2
      #(.rscid(32'sd7),
  .width(32'sd1)) data_is_write_rsci (
      .d(nl_data_is_write_rsci_d),
      .z(data_is_write_rsc_z)
    );
  GBCore_Connections_InBlockingless_spec_GB_Large_DataReqcomma_Connections_SYN_PORTgreater_PopNB_mgc_out_dreg_v2
      #(.rscid(32'sd8),
  .width(32'sd2)) data_memory_index_rsci (
      .d(nl_data_memory_index_rsci_d[1:0]),
      .z(data_memory_index_rsc_z)
    );
  GBCore_Connections_InBlockingless_spec_GB_Large_DataReqcomma_Connections_SYN_PORTgreater_PopNB_mgc_out_dreg_v2
      #(.rscid(32'sd9),
  .width(32'sd8)) data_vector_index_rsci (
      .d(nl_data_vector_index_rsci_d[7:0]),
      .z(data_vector_index_rsc_z)
    );
  GBCore_Connections_InBlockingless_spec_GB_Large_DataReqcomma_Connections_SYN_PORTgreater_PopNB_mgc_out_dreg_v2
      #(.rscid(32'sd10),
  .width(32'sd16)) data_timestep_index_rsci (
      .d(nl_data_timestep_index_rsci_d[15:0]),
      .z(data_timestep_index_rsc_z)
    );
  GBCore_Connections_InBlockingless_spec_GB_Large_DataReqcomma_Connections_SYN_PORTgreater_PopNB_mgc_out_dreg_v2
      #(.rscid(32'sd11),
  .width(32'sd128)) data_write_data_data_rsci (
      .d(nl_data_write_data_data_rsci_d[127:0]),
      .z(data_write_data_data_rsc_z)
    );
  GBCore_Connections_InBlockingless_spec_GB_Large_DataReqcomma_Connections_SYN_PORTgreater_PopNB_mgc_out_dreg_v2
      #(.rscid(32'sd13),
  .width(32'sd1)) return_rsci (
      .d(this_vld),
      .z(return_rsc_z)
    );
  GBCore_Connections_InBlockingless_spec_GB_Large_DataReqcomma_Connections_SYN_PORTgreater_PopNB_ccs_in_v1
      #(.rscid(32'sd99),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      this_rdy <= 1'b0;
    end
    else if ( ccs_ccore_start_rsci_idat | asn_itm_1 ) begin
      this_rdy <= ccs_ccore_start_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      asn_itm_1 <= 1'b0;
    end
    else begin
      asn_itm_1 <= ccs_ccore_start_rsci_idat;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    Connections_InBlocking_spec_GB_Large_DataReq_Connections_SYN_PORT_PopNB
// ------------------------------------------------------------------


module GBCore_Connections_InBlocking_spec_GB_Large_DataReq_Connections_SYN_PORT_PopNB (
  this_vld, this_rdy, this_dat, data_is_write_rsc_z, data_memory_index_rsc_z, data_vector_index_rsc_z,
      data_timestep_index_rsc_z, data_write_data_data_rsc_z, return_rsc_z, ccs_ccore_start_rsc_dat,
      ccs_MIO_clk, ccs_MIO_arst
);
  input this_vld;
  output this_rdy;
  input [154:0] this_dat;
  output data_is_write_rsc_z;
  output [1:0] data_memory_index_rsc_z;
  output [7:0] data_vector_index_rsc_z;
  output [15:0] data_timestep_index_rsc_z;
  output [127:0] data_write_data_data_rsc_z;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;



  // Interconnect Declarations for Component Instantiations
  GBCore_Connections_InBlockingless_spec_GB_Large_DataReqcomma_Connections_SYN_PORTgreater_PopNB_Connections_InBlocking_spec_GB_Large_DataReq_Connections_SYN_PORT_PopNB_core
      Connections_InBlocking_spec_GB_Large_DataReq_Connections_SYN_PORT_PopNB_core_inst
      (
      .this_vld(this_vld),
      .this_rdy(this_rdy),
      .this_dat(this_dat),
      .data_is_write_rsc_z(data_is_write_rsc_z),
      .data_memory_index_rsc_z(data_memory_index_rsc_z),
      .data_vector_index_rsc_z(data_vector_index_rsc_z),
      .data_timestep_index_rsc_z(data_timestep_index_rsc_z),
      .data_write_data_data_rsc_z(data_write_data_data_rsc_z),
      .return_rsc_z(return_rsc_z),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_MIO_clk(ccs_MIO_clk),
      .ccs_MIO_arst(ccs_MIO_arst)
    );
endmodule



