directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.5(31:16) REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.5(31:16)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(31:0).sva.dfm#3(31:16) REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.5(31:16)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.5(7:0) REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.5(7:0)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(31:0).sva.dfm#3(15:8) REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.5(7:0)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::SetLargeBuffer<1U>#1:base_addr:mux#1.itm.1 REGISTER_NAME GBCore::SetLargeBuffer<1U>#1:base_addr:mux#1.itm.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::SetLargeBuffer<1U>:base_addr:mux#1.itm.2 REGISTER_NAME GBCore::SetLargeBuffer<1U>#1:base_addr:mux#1.itm.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.2(7:0) REGISTER_NAME GBCore::SetLargeBuffer<1U>#1:base_addr:mux#1.itm.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(55:48).sva.dfm#1.4 REGISTER_NAME rva_out_reg.data#1(55:48).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(55:48).sva.dfm#4 REGISTER_NAME rva_out_reg.data#1(55:48).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(63:56).sva.dfm#1.4 REGISTER_NAME rva_out_reg.data#1(63:56).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(63:56).sva.dfm#4 REGISTER_NAME rva_out_reg.data#1(63:56).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(87:80).sva.dfm#1.4 REGISTER_NAME rva_out_reg.data#1(87:80).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(87:80).sva.dfm#4 REGISTER_NAME rva_out_reg.data#1(87:80).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(95:88).sva.dfm#1.4 REGISTER_NAME rva_out_reg.data#1(95:88).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(95:88).sva.dfm#4 REGISTER_NAME rva_out_reg.data#1(95:88).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(119:112).sva.dfm#1.4 REGISTER_NAME rva_out_reg.data#1(119:112).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(119:112).sva.dfm#4 REGISTER_NAME rva_out_reg.data#1(119:112).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(127:120).sva.dfm#1.4 REGISTER_NAME rva_out_reg.data#1(127:120).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(127:120).sva.dfm#4 REGISTER_NAME rva_out_reg.data#1(127:120).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(39:32).sva.dfm#1.4 REGISTER_NAME rva_out_reg.data#1(39:32).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(39:32).sva.dfm#4 REGISTER_NAME rva_out_reg.data#1(39:32).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(71:64).sva.dfm#1.4 REGISTER_NAME rva_out_reg.data#1(71:64).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(71:64).sva.dfm#4 REGISTER_NAME rva_out_reg.data#1(71:64).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(103:96).sva.dfm#1.4 REGISTER_NAME rva_out_reg.data#1(103:96).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(103:96).sva.dfm#4 REGISTER_NAME rva_out_reg.data#1(103:96).sva.dfm#1.4
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::SetLargeBuffer<1U>#1:base_addr:mux.itm.1 REGISTER_NAME GBCore::SetLargeBuffer<1U>#1:base_addr:mux.itm.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::SetLargeBuffer<1U>:base_addr:mux.itm.2 REGISTER_NAME GBCore::SetLargeBuffer<1U>#1:base_addr:mux.itm.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.2(31:16) REGISTER_NAME GBCore::SetLargeBuffer<1U>#1:base_addr:mux.itm.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_req_reg.vector_index#1.sva.1 REGISTER_NAME large_req_reg.vector_index#1.sva.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/num_vector_large(1).sva REGISTER_NAME large_req_reg.vector_index#1.sva.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/base_large(1).sva REGISTER_NAME base_large(1).sva
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_req_reg.timestep_index#1.sva.1 REGISTER_NAME base_large(1).sva
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/base_large(2).sva REGISTER_NAME base_large(2).sva
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/while:if:while:if:and#1.itm.2 REGISTER_NAME base_large(2).sva
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/base_large(3).sva REGISTER_NAME base_large(3).sva
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/while:if:while:if:and#3.itm.2 REGISTER_NAME base_large(3).sva
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(15).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(15).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(87:80).sva.dfm#1.1 REGISTER_NAME large_write_data.data(0)(15).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(14).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(14).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(71:64).sva.dfm#1.1 REGISTER_NAME large_write_data.data(0)(14).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(13).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(13).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(63:56).sva.dfm#1.1 REGISTER_NAME large_write_data.data(0)(13).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(12).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(12).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(55:48).sva.dfm#1.1 REGISTER_NAME large_write_data.data(0)(12).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(11).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(11).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(39:32).sva.dfm#1.1 REGISTER_NAME large_write_data.data(0)(11).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(10).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(10).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(127:120).sva.dfm#1.1 REGISTER_NAME large_write_data.data(0)(10).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(9).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(9).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/while:if:while:if:and#16.itm.2 REGISTER_NAME large_write_data.data(0)(9).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(8).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(8).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/while:if:while:if:and#15.itm.2 REGISTER_NAME large_write_data.data(0)(8).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(7).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(7).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/while:if:while:if:and#14.itm.2 REGISTER_NAME large_write_data.data(0)(7).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(6).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(6).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/while:if:while:if:and#13.itm.2 REGISTER_NAME large_write_data.data(0)(6).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(5).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(5).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/while:if:while:if:and#12.itm.2 REGISTER_NAME large_write_data.data(0)(5).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(4).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(4).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/while:if:while:if:and#11.itm.2 REGISTER_NAME large_write_data.data(0)(4).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(3).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(3).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/while:if:while:if:and#10.itm.2 REGISTER_NAME large_write_data.data(0)(3).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(2).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(2).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(95:88).sva.dfm#1.1 REGISTER_NAME large_write_data.data(0)(2).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(1).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(1).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(119:112).sva.dfm#1.1 REGISTER_NAME large_write_data.data(0)(1).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/large_write_data.data(0)(0).lpi#1.dfm#2.1 REGISTER_NAME large_write_data.data(0)(0).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_out_reg.data#1(103:96).sva.dfm#1.1 REGISTER_NAME large_write_data.data(0)(0).lpi#1.dfm#2.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/base_large(3).sva.dfm#3.1 REGISTER_NAME base_large(3).sva.dfm#3.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_in_reg.data.sva.1(127:112) REGISTER_NAME base_large(3).sva.dfm#3.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_in_reg.data.sva.1(103:80) REGISTER_NAME rva_in_reg.data.sva.1(103:80)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/base_large(0).sva.dfm#3.1 REGISTER_NAME rva_in_reg.data.sva.1(103:80)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_in_reg.data.sva.1(71:48) REGISTER_NAME rva_in_reg.data.sva.1(71:48)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/base_large(2).sva.dfm#3.1 REGISTER_NAME rva_in_reg.data.sva.1(71:48)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/rva_in_reg.data.sva.1(39:16) REGISTER_NAME rva_in_reg.data.sva.1(39:16)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/base_large(1).sva.dfm#3.1 REGISTER_NAME rva_in_reg.data.sva.1(39:16)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::DecodeAxiRead:switch-lp:nor#13.itm.1 REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:nor#13.itm.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::PollNMPPort:Connections::InBlocking<spec::GB::Large::DataReq,Connections::SYN_PORT>::PopNB(return).sva.st.2 REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:nor#13.itm.1
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.1(31:16) REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.1(31:16)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::SetLargeBuffer<1U>:base_addr:mux.itm.1 REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.1(31:16)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/base_large(0).sva REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.1(31:16)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.1(7:0) REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.1(7:0)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/GBCore::SetLargeBuffer<1U>:base_addr:mux#1.itm.1 REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.1(7:0)
directive set /GBCore/GBCore:GBCoreRun/GBCoreRun/num_vector_large(0).sva REGISTER_NAME GBCore::DecodeAxiRead:switch-lp:GBCore::DecodeAxiRead:switch-lp:and#10.itm.1(7:0)
