// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2_1/1143609 Production Release
//  HLS Date:       Wed Nov 13 18:57:31 PST 2024
// 
//  Generated by:   code@iron-05
//  Generated date: Wed Mar 18 19:32:15 2026
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    Connections_InBlockingless_axi_axi4less_spec_Axi_axiCfggreater_WRespPayloadcomma_Connections_SYN_PORTgreater_PopNB_Connections_InBlocking_axi_axi4_spec_Axi_axiCfg_WRespPayload_Connections_SYN_PORT_PopNB_core
// ------------------------------------------------------------------


module Connections_InBlockingless_axi_axi4less_spec_Axi_axiCfggreater_WRespPayloadcomma_Connections_SYN_PORTgreater_PopNB_Connections_InBlocking_axi_axi4_spec_Axi_axiCfg_WRespPayload_Connections_SYN_PORT_PopNB_core
    (
  this_vld, this_rdy, this_dat, data_id_rsc_z, data_resp_rsc_z, return_rsc_z, ccs_ccore_start_rsc_dat,
      ccs_MIO_clk, ccs_MIO_arst
);
  input this_vld;
  output this_rdy;
  reg this_rdy;
  input [11:0] this_dat;
  output [9:0] data_id_rsc_z;
  output [1:0] data_resp_rsc_z;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;


  // Interconnect Declarations
  wire ccs_ccore_start_rsci_idat;
  reg asn_itm_1;


  // Interconnect Declarations for Component Instantiations 
  wire [9:0] nl_data_id_rsci_d;
  assign nl_data_id_rsci_d = this_dat[9:0];
  wire [1:0] nl_data_resp_rsci_d;
  assign nl_data_resp_rsci_d = this_dat[11:10];
  Connections_InBlockingless_axi_axi4less_spec_Axi_axiCfggreater_WRespPayloadcomma_Connections_SYN_PORTgreater_PopNB_mgc_out_dreg_v2
      #(.rscid(32'sd227),
  .width(32'sd10)) data_id_rsci (
      .d(nl_data_id_rsci_d[9:0]),
      .z(data_id_rsc_z)
    );
  Connections_InBlockingless_axi_axi4less_spec_Axi_axiCfggreater_WRespPayloadcomma_Connections_SYN_PORTgreater_PopNB_mgc_out_dreg_v2
      #(.rscid(32'sd228),
  .width(32'sd2)) data_resp_rsci (
      .d(nl_data_resp_rsci_d[1:0]),
      .z(data_resp_rsc_z)
    );
  Connections_InBlockingless_axi_axi4less_spec_Axi_axiCfggreater_WRespPayloadcomma_Connections_SYN_PORTgreater_PopNB_mgc_out_dreg_v2
      #(.rscid(32'sd230),
  .width(32'sd1)) return_rsci (
      .d(this_vld),
      .z(return_rsc_z)
    );
  Connections_InBlockingless_axi_axi4less_spec_Axi_axiCfggreater_WRespPayloadcomma_Connections_SYN_PORTgreater_PopNB_ccs_in_v1
      #(.rscid(32'sd504),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      this_rdy <= 1'b0;
    end
    else if ( ccs_ccore_start_rsci_idat | asn_itm_1 ) begin
      this_rdy <= ccs_ccore_start_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      asn_itm_1 <= 1'b0;
    end
    else begin
      asn_itm_1 <= ccs_ccore_start_rsci_idat;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    Connections_InBlocking_axi_axi4_spec_Axi_axiCfg_WRespPayload_Connections_SYN_PORT_PopNB
// ------------------------------------------------------------------


module Connections_InBlocking_axi_axi4_spec_Axi_axiCfg_WRespPayload_Connections_SYN_PORT_PopNB
    (
  this_vld, this_rdy, this_dat, data_id_rsc_z, data_resp_rsc_z, return_rsc_z, ccs_ccore_start_rsc_dat,
      ccs_MIO_clk, ccs_MIO_arst
);
  input this_vld;
  output this_rdy;
  input [11:0] this_dat;
  output [9:0] data_id_rsc_z;
  output [1:0] data_resp_rsc_z;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;



  // Interconnect Declarations for Component Instantiations 
  Connections_InBlockingless_axi_axi4less_spec_Axi_axiCfggreater_WRespPayloadcomma_Connections_SYN_PORTgreater_PopNB_Connections_InBlocking_axi_axi4_spec_Axi_axiCfg_WRespPayload_Connections_SYN_PORT_PopNB_core
      Connections_InBlocking_axi_axi4_spec_Axi_axiCfg_WRespPayload_Connections_SYN_PORT_PopNB_core_inst
      (
      .this_vld(this_vld),
      .this_rdy(this_rdy),
      .this_dat(this_dat),
      .data_id_rsc_z(data_id_rsc_z),
      .data_resp_rsc_z(data_resp_rsc_z),
      .return_rsc_z(return_rsc_z),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_MIO_clk(ccs_MIO_clk),
      .ccs_MIO_arst(ccs_MIO_arst)
    );
endmodule



