directive set /PECore/PECore:PECoreRun/PECoreRun/pe_manager.base_weight.sva REGISTER_NAME pe_manager.base_weight.sva
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(47:40).sva.dfm#1.3 REGISTER_NAME pe_manager.base_weight.sva
directive set /PECore/PECore:PECoreRun/PECoreRun/pe_config.manager_counter.sva REGISTER_NAME pe_config.manager_counter.sva
directive set /PECore/PECore:PECoreRun/PECoreRun/pe_config.manager_counter.sva.dfm.1 REGISTER_NAME pe_config.manager_counter.sva
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_port_read_out.data(0)(1).sva.dfm#1.1 REGISTER_NAME weight_port_read_out.data(0)(1).sva.dfm#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_port_read_out.data(0)(1).sva.dfm.1 REGISTER_NAME weight_port_read_out.data(0)(1).sva.dfm#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_port_read_out.data(0)(0).sva.dfm#1.1 REGISTER_NAME weight_port_read_out.data(0)(0).sva.dfm#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_port_read_out.data(0)(0).sva.dfm.1 REGISTER_NAME weight_port_read_out.data(0)(0).sva.dfm#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/crossbar<spec::PE::Weight::WordType,16U,16U>#1:for-1:data_in_tmp.operator=#2:for-16:slc(data_in_tmp.operator=#2:for:slc(weight_mem.run#3:bank_read_out.data,*128)(127-0),data_in_tmp.operator=#2:for:slc(data_in_tmp.operator=#2:for:i)(3-0)*8)(7-0).sdt(119:112).lpi#1.dfm.1 REGISTER_NAME crossbar<spec::PE::Weight::WordType,16U,16U>#1:for-1:data_in_tmp.operator=#2:for-16:slc(data_in_tmp.operator=#2:for:slc(weight_mem.run#3:bank_read_out.data,*128)(127-0),data_in_tmp.operator=#2:for:slc(data_in_tmp.operator=#2:for:i)(3-0)*8)(7-0).sdt(119:112).lpi#1.dfm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/crossbar<spec::PE::Weight::WordType,16U,16U>:for-1:data_in_tmp.operator=:for-16:slc(data_in_tmp.operator=:for:slc(weight_mem.run#1:bank_read_out.data,*128)(127-0),data_in_tmp.operator=:for:slc(data_in_tmp.operator=:for:i)(3-0)*8)(7-0).sdt(119:112).sva.1 REGISTER_NAME crossbar<spec::PE::Weight::WordType,16U,16U>#1:for-1:data_in_tmp.operator=#2:for-16:slc(data_in_tmp.operator=#2:for:slc(weight_mem.run#3:bank_read_out.data,*128)(127-0),data_in_tmp.operator=#2:for:slc(data_in_tmp.operator=#2:for:i)(3-0)*8)(7-0).sdt(119:112).lpi#1.dfm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_port_read_out.data(0)(11).sva.dfm#1.1 REGISTER_NAME weight_port_read_out.data(0)(11).sva.dfm#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_port_read_out.data(0)(3).sva.dfm.1 REGISTER_NAME weight_port_read_out.data(0)(11).sva.dfm#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_port_read_out.data(0)(10).sva.dfm#1.1 REGISTER_NAME weight_port_read_out.data(0)(10).sva.dfm#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_port_read_out.data(0)(2).sva.dfm.1 REGISTER_NAME weight_port_read_out.data(0)(10).sva.dfm#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/Arbiter<16U,Roundrobin>::pick#1:and#1.psp REGISTER_NAME Arbiter<16U,Roundrobin>::pick#1:and#1.psp
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunFSM:switch-lp:equal.tmp#1.2 REGISTER_NAME Arbiter<16U,Roundrobin>::pick#1:and#1.psp
directive set /PECore/PECore:PECoreRun/PECoreRun/operator+<17,false>:slc(PEManager<17U>::GetWeightAddr:else:acc#2.psp)(12).itm.1 REGISTER_NAME operator+<17,false>:slc(PEManager<17U>::GetWeightAddr:else:acc#2.psp)(12).itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_in_reg.rw.sva.st#1.3 REGISTER_NAME operator+<17,false>:slc(PEManager<17U>::GetWeightAddr:else:acc#2.psp)(12).itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_read_addrs(0)(15:4).lpi#1.dfm#1.3 REGISTER_NAME weight_read_addrs(0)(15:4).lpi#1.dfm#1.3
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_read_addrs(0)(15:4).lpi#1.dfm#2.1 REGISTER_NAME weight_read_addrs(0)(15:4).lpi#1.dfm#1.3
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read:read_data:slc(input_mem.banks.read:read_data)(39-36).itm.1 REGISTER_NAME input_mem.banks.read:read_data:slc(input_mem.banks.read:read_data)(39-36).itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_port_read_out.data:slc(weight_port_read_out.data(0)(4))(7-4).itm.1 REGISTER_NAME input_mem.banks.read:read_data:slc(input_mem.banks.read:read_data)(39-36).itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read:read_data:slc(input_mem.banks.read:read_data)(35-33).itm.1 REGISTER_NAME input_mem.banks.read:read_data:slc(input_mem.banks.read:read_data)(35-33).itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_port_read_out.data:slc(weight_port_read_out.data(0)(4))(3-1).itm.1 REGISTER_NAME input_mem.banks.read:read_data:slc(input_mem.banks.read:read_data)(35-33).itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read:read_data:slc(input_mem.banks.read:read_data)(15-9).itm.1 REGISTER_NAME input_mem.banks.read:read_data:slc(input_mem.banks.read:read_data)(15-9).itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_port_read_out.data:slc(weight_port_read_out.data(0)(6))(7-1).itm.1 REGISTER_NAME input_mem.banks.read:read_data:slc(input_mem.banks.read:read_data)(15-9).itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(15:9).sva.dfm.6 REGISTER_NAME rva_out_reg.data(15:9).sva.dfm.6
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(71:65).sva.dfm#2.1 REGISTER_NAME rva_out_reg.data(15:9).sva.dfm.6
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(127:120).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(127:120).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_mem.run#3:for#5:mux#103.itm.1 REGISTER_NAME rva_out_reg.data(127:120).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(119:112).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(119:112).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_mem.run#3:for#5:mux#102.itm.1 REGISTER_NAME rva_out_reg.data(119:112).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(111:104).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(111:104).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_mem.run#3:for#5:mux#101.itm.1 REGISTER_NAME rva_out_reg.data(111:104).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(103:96).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(103:96).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_mem.run#3:for#5:mux#100.itm.1 REGISTER_NAME rva_out_reg.data(103:96).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(95:88).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(95:88).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_mem.run#3:for#5:mux#106.itm.1 REGISTER_NAME rva_out_reg.data(95:88).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(87:80).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(87:80).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_mem.run#3:for#5:mux#105.itm.1 REGISTER_NAME rva_out_reg.data(87:80).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(79:72).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(79:72).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_mem.run#3:for#5:mux#104.itm.1 REGISTER_NAME rva_out_reg.data(79:72).sva.dfm#4.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(64).sva.dfm#2.1 REGISTER_NAME rva_out_reg.data(64).sva.dfm#2.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(64).sva.dfm#6 REGISTER_NAME rva_out_reg.data(64).sva.dfm#2.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(48).sva.dfm#2.1 REGISTER_NAME rva_out_reg.data(48).sva.dfm#2.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(48).sva.dfm#6 REGISTER_NAME rva_out_reg.data(48).sva.dfm#2.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(32).sva.dfm#2.1 REGISTER_NAME rva_out_reg.data(32).sva.dfm#2.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(32).sva.dfm#6 REGISTER_NAME rva_out_reg.data(32).sva.dfm#2.1
directive set /PECore/PECore:PECoreRun/PECoreRun/crossbar<spec::PE::Weight::WordType,16U,16U>:source_tmp#1.lpi#1.dfm.2 REGISTER_NAME crossbar<spec::PE::Weight::WordType,16U,16U>:source_tmp#1.lpi#1.dfm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/pe_manager.base_weight:slc(pe_manager.base_weight)(3-0)#13.itm.1 REGISTER_NAME crossbar<spec::PE::Weight::WordType,16U,16U>:source_tmp#1.lpi#1.dfm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read#1:read_data.lpi#1.dfm#1.2 REGISTER_NAME input_mem.banks.read#1:read_data.lpi#1.dfm#1.2
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read:read_data.lpi#1.dfm#1.2 REGISTER_NAME input_mem.banks.read#1:read_data.lpi#1.dfm#1.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#18.itm.2 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#18.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunScale:PECore::RunScale:if:and#1.svs.st.3 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#18.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#10.itm.3 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#10.itm.3
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::PushOutput:PECore::PushOutput:if:and.svs.st.3 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#10.itm.3
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#15.itm.2 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#15.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunScale:PECore::RunScale:if:and#1.svs.3 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#15.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.2 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:PECore::RunMac:if:and.svs.st.3 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#5.itm.3 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#5.itm.3
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:PECore::RunMac:if:and.svs.3 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#5.itm.3
directive set /PECore/PECore:PECoreRun/PECoreRun/crossbar<spec::PE::Weight::WordType,16U,16U>:source_tmp#1.lpi#1.dfm.1 REGISTER_NAME crossbar<spec::PE::Weight::WordType,16U,16U>:source_tmp#1.lpi#1.dfm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(39:36).sva.dfm#1.3 REGISTER_NAME crossbar<spec::PE::Weight::WordType,16U,16U>:source_tmp#1.lpi#1.dfm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:equal.tmp#2.3 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#2.3
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::UpdateFSM:switch-lp:equal.tmp#2.3 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#2.3
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.1 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::PushOutput:PECore::PushOutput:if:and.svs.st.2 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#18.itm.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#18.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:PECore::RunMac:if:and.svs.st.2 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#18.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#15.itm.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#15.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:PECore::RunMac:if:and.svs.2 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:PECore::DecodeAxiRead:switch-lp:and#15.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:equal.tmp#1.2 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:equal.tmp#1.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunFSM:switch-lp:equal.tmp#1.1 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:equal.tmp#1.2
