// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2_1/1143609 Production Release
//  HLS Date:       Wed Nov 13 18:57:31 PST 2024
// 
//  Generated by:   code@iron-05
//  Generated date: Wed Mar 18 19:33:00 2026
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    Connections_OutBlockingless_boolcomma_Connections_SYN_PORTgreater_PushNB_Connections_OutBlocking_bool_Connections_SYN_PORT_PushNB_core
// ------------------------------------------------------------------


module Connections_OutBlockingless_boolcomma_Connections_SYN_PORTgreater_PushNB_Connections_OutBlocking_bool_Connections_SYN_PORT_PushNB_core
    (
  this_vld, this_rdy, return_rsc_z, ccs_ccore_start_rsc_dat, ccs_MIO_clk, ccs_MIO_arst
);
  output this_vld;
  input this_rdy;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;


  // Interconnect Declarations
  wire ccs_ccore_start_rsci_idat;
  reg reg_this_dat_cse;
  reg asn_itm_1;


  // Interconnect Declarations for Component Instantiations 
  Connections_OutBlockingless_boolcomma_Connections_SYN_PORTgreater_PushNB_mgc_out_dreg_v2
      #(.rscid(32'sd248),
  .width(32'sd1)) return_rsci (
      .d(this_rdy),
      .z(return_rsc_z)
    );
  Connections_OutBlockingless_boolcomma_Connections_SYN_PORTgreater_PushNB_ccs_in_v1
      #(.rscid(32'sd503),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  assign this_vld = reg_this_dat_cse;
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      reg_this_dat_cse <= 1'b0;
    end
    else if ( ccs_ccore_start_rsci_idat | asn_itm_1 ) begin
      reg_this_dat_cse <= ccs_ccore_start_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      asn_itm_1 <= 1'b0;
    end
    else begin
      asn_itm_1 <= ccs_ccore_start_rsci_idat;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    Connections_OutBlocking_bool_Connections_SYN_PORT_PushNB
// ------------------------------------------------------------------


module Connections_OutBlocking_bool_Connections_SYN_PORT_PushNB (
  this_vld, this_rdy, this_dat, return_rsc_z, ccs_ccore_start_rsc_dat, ccs_MIO_clk,
      ccs_MIO_arst
);
  output this_vld;
  input this_rdy;
  output this_dat;
  output return_rsc_z;
  input ccs_ccore_start_rsc_dat;
  input ccs_MIO_clk;
  input ccs_MIO_arst;



  // Interconnect Declarations for Component Instantiations 
  Connections_OutBlockingless_boolcomma_Connections_SYN_PORTgreater_PushNB_Connections_OutBlocking_bool_Connections_SYN_PORT_PushNB_core
      Connections_OutBlocking_bool_Connections_SYN_PORT_PushNB_core_inst (
      .this_vld(this_vld),
      .this_rdy(this_rdy),
      .return_rsc_z(return_rsc_z),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_MIO_clk(ccs_MIO_clk),
      .ccs_MIO_arst(ccs_MIO_arst)
    );
  assign this_dat = this_vld;
endmodule



