// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2_1/1143609 Production Release
//  HLS Date:       Wed Nov 13 18:57:31 PST 2024
//
//  Generated by:   code@iron-06
//  Generated date: Sun Feb 22 19:09:49 2026
// ----------------------------------------------------------------------

//
// ------------------------------------------------------------------
//  Design Unit:    Connections_Combinationalless_RVSinkless_spec_Axi_rvaCfggreater_Writecomma_Connections_SYN_PORTgreater_Push_Connections_Combinational_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_Push_core
// ------------------------------------------------------------------


module GBModule_Connections_Combinationalless_RVSinkless_spec_Axi_rvaCfggreater_Writecomma_Connections_SYN_PORTgreater_Push_Connections_Combinational_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_Push_core
    (
  this_vld, this_rdy, this_dat, m_data_rsc_dat, m_addr_rsc_dat, m_wstrb_rsc_dat,
      m_rw_rsc_dat, ccs_ccore_start_rsc_dat, ccs_ccore_done_sync_vld, ccs_MIO_clk,
      ccs_MIO_arst
);
  output this_vld;
  reg this_vld;
  input this_rdy;
  output [168:0] this_dat;
  input [127:0] m_data_rsc_dat;
  input [23:0] m_addr_rsc_dat;
  input [15:0] m_wstrb_rsc_dat;
  input m_rw_rsc_dat;
  input ccs_ccore_start_rsc_dat;
  output ccs_ccore_done_sync_vld;
  input ccs_MIO_clk;
  input ccs_MIO_arst;


  // Interconnect Declarations
  wire [127:0] m_data_rsci_idat;
  wire [23:0] m_addr_rsci_idat;
  wire [15:0] m_wstrb_rsci_idat;
  wire m_rw_rsci_idat;
  wire ccs_ccore_start_rsci_idat;
  reg m_rw_buf_lpi_1_dfm;
  reg [15:0] m_wstrb_buf_lpi_1_dfm;
  reg [23:0] m_addr_buf_lpi_1_dfm;
  reg [127:0] m_data_buf_lpi_1_dfm;
  wire and_dcpl;
  wire or_dcpl_2;
  reg io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1;
  wire or_4_cse;
  wire this_vld_mx0c1;


  // Interconnect Declarations for Component Instantiations
  wire  nl_ccs_ccore_done_synci_ivld;
  assign nl_ccs_ccore_done_synci_ivld = io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1
      & this_rdy;
  GBModule_Connections_Combinationalless_RVSinkless_spec_Axi_rvaCfggreater_Writecomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd158),
  .width(32'sd128)) m_data_rsci (
      .dat(m_data_rsc_dat),
      .idat(m_data_rsci_idat)
    );
  GBModule_Connections_Combinationalless_RVSinkless_spec_Axi_rvaCfggreater_Writecomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd159),
  .width(32'sd24)) m_addr_rsci (
      .dat(m_addr_rsc_dat),
      .idat(m_addr_rsci_idat)
    );
  GBModule_Connections_Combinationalless_RVSinkless_spec_Axi_rvaCfggreater_Writecomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd160),
  .width(32'sd16)) m_wstrb_rsci (
      .dat(m_wstrb_rsc_dat),
      .idat(m_wstrb_rsci_idat)
    );
  GBModule_Connections_Combinationalless_RVSinkless_spec_Axi_rvaCfggreater_Writecomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd161),
  .width(32'sd1)) m_rw_rsci (
      .dat(m_rw_rsc_dat),
      .idat(m_rw_rsci_idat)
    );
  GBModule_Connections_Combinationalless_RVSinkless_spec_Axi_rvaCfggreater_Writecomma_Connections_SYN_PORTgreater_Push_ccs_in_v1
      #(.rscid(32'sd188),
  .width(32'sd1)) ccs_ccore_start_rsci (
      .dat(ccs_ccore_start_rsc_dat),
      .idat(ccs_ccore_start_rsci_idat)
    );
  GBModule_Connections_Combinationalless_RVSinkless_spec_Axi_rvaCfggreater_Writecomma_Connections_SYN_PORTgreater_Push_ccs_sync_out_vld_v1
      #(.rscid(32'sd193)) ccs_ccore_done_synci (
      .vld(ccs_ccore_done_sync_vld),
      .ivld(nl_ccs_ccore_done_synci_ivld)
    );
  assign this_dat = {m_rw_buf_lpi_1_dfm , m_wstrb_buf_lpi_1_dfm , m_addr_buf_lpi_1_dfm
      , m_data_buf_lpi_1_dfm};
  assign or_4_cse = ccs_ccore_start_rsci_idat | and_dcpl;
  assign and_dcpl = io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 & (~ this_rdy);
  assign or_dcpl_2 = and_dcpl | (~ ccs_ccore_start_rsci_idat);
  assign this_vld_mx0c1 = io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 & this_rdy
      & (~ ccs_ccore_start_rsci_idat);
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      this_vld <= 1'b0;
    end
    else if ( or_4_cse | this_vld_mx0c1 ) begin
      this_vld <= ~ this_vld_mx0c1;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      m_rw_buf_lpi_1_dfm <= 1'b0;
    end
    else if ( ~ or_dcpl_2 ) begin
      m_rw_buf_lpi_1_dfm <= m_rw_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      m_wstrb_buf_lpi_1_dfm <= 16'b0000000000000000;
    end
    else if ( ~ or_dcpl_2 ) begin
      m_wstrb_buf_lpi_1_dfm <= m_wstrb_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      m_addr_buf_lpi_1_dfm <= 24'b000000000000000000000000;
    end
    else if ( ~ or_dcpl_2 ) begin
      m_addr_buf_lpi_1_dfm <= m_addr_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      m_data_buf_lpi_1_dfm <= 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    end
    else if ( ~ or_dcpl_2 ) begin
      m_data_buf_lpi_1_dfm <= m_data_rsci_idat;
    end
  end
  always @(posedge ccs_MIO_clk or negedge ccs_MIO_arst) begin
    if ( ~ ccs_MIO_arst ) begin
      io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 <= 1'b0;
    end
    else begin
      io_read_ccs_ccore_start_rsc_sft_lpi_1_dfm_1 <= or_4_cse;
    end
  end
endmodule

// ------------------------------------------------------------------
//  Design Unit:    Connections_Combinational_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_Push
// ------------------------------------------------------------------


module GBModule_Connections_Combinational_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_Push
    (
  this_vld, this_rdy, this_dat, m_data_rsc_dat, m_addr_rsc_dat, m_wstrb_rsc_dat,
      m_rw_rsc_dat, ccs_ccore_start_rsc_dat, ccs_ccore_done_sync_vld, ccs_MIO_clk,
      ccs_MIO_arst
);
  output this_vld;
  input this_rdy;
  output [168:0] this_dat;
  input [127:0] m_data_rsc_dat;
  input [23:0] m_addr_rsc_dat;
  input [15:0] m_wstrb_rsc_dat;
  input m_rw_rsc_dat;
  input ccs_ccore_start_rsc_dat;
  output ccs_ccore_done_sync_vld;
  input ccs_MIO_clk;
  input ccs_MIO_arst;



  // Interconnect Declarations for Component Instantiations
  GBModule_Connections_Combinationalless_RVSinkless_spec_Axi_rvaCfggreater_Writecomma_Connections_SYN_PORTgreater_Push_Connections_Combinational_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_Push_core
      Connections_Combinational_RVSink_spec_Axi_rvaCfg_Write_Connections_SYN_PORT_Push_core_inst
      (
      .this_vld(this_vld),
      .this_rdy(this_rdy),
      .this_dat(this_dat),
      .m_data_rsc_dat(m_data_rsc_dat),
      .m_addr_rsc_dat(m_addr_rsc_dat),
      .m_wstrb_rsc_dat(m_wstrb_rsc_dat),
      .m_rw_rsc_dat(m_rw_rsc_dat),
      .ccs_ccore_start_rsc_dat(ccs_ccore_start_rsc_dat),
      .ccs_ccore_done_sync_vld(ccs_ccore_done_sync_vld),
      .ccs_MIO_clk(ccs_MIO_clk),
      .ccs_MIO_arst(ccs_MIO_arst)
    );
endmodule



