// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2024.2_1/1143609 Production Release
//       HLS date: Wed Nov 13 18:57:31 PST 2024
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: code@iron-05
// Generated date: Wed Mar 18 19:39:17 PDT 2026
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model Top
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Constructor: sysc_sim_wrapper

CCS_RTL::sysc_sim_wrapper::sysc_sim_wrapper(
   const sc_module_name& nm
)
   : ccs_rtl(
      "ccs_rtl",
      "ccs_wrapper"
   )
   , clk("clk")
   , rst("rst")
   , interrupt("interrupt")
   , if_axi_rd("if_axi_rd")
   , if_axi_wr("if_axi_wr")
   , ccs_rtl_SIG_clk("ccs_rtl_SIG_clk")
   , ccs_rtl_SIG_rst("ccs_rtl_SIG_rst")
   , ccs_rtl_SIG_interrupt("ccs_rtl_SIG_interrupt")
   , ccs_rtl_SIG_if_axi_rd_ar_vld("ccs_rtl_SIG_if_axi_rd_ar_vld")
   , ccs_rtl_SIG_if_axi_rd_ar_rdy("ccs_rtl_SIG_if_axi_rd_ar_rdy")
   , ccs_rtl_SIG_if_axi_rd_ar_dat("ccs_rtl_SIG_if_axi_rd_ar_dat")
   , ccs_rtl_SIG_if_axi_rd_r_vld("ccs_rtl_SIG_if_axi_rd_r_vld")
   , ccs_rtl_SIG_if_axi_rd_r_rdy("ccs_rtl_SIG_if_axi_rd_r_rdy")
   , ccs_rtl_SIG_if_axi_rd_r_dat("ccs_rtl_SIG_if_axi_rd_r_dat")
   , ccs_rtl_SIG_if_axi_wr_aw_vld("ccs_rtl_SIG_if_axi_wr_aw_vld")
   , ccs_rtl_SIG_if_axi_wr_aw_rdy("ccs_rtl_SIG_if_axi_wr_aw_rdy")
   , ccs_rtl_SIG_if_axi_wr_aw_dat("ccs_rtl_SIG_if_axi_wr_aw_dat")
   , ccs_rtl_SIG_if_axi_wr_w_vld("ccs_rtl_SIG_if_axi_wr_w_vld")
   , ccs_rtl_SIG_if_axi_wr_w_rdy("ccs_rtl_SIG_if_axi_wr_w_rdy")
   , ccs_rtl_SIG_if_axi_wr_w_dat("ccs_rtl_SIG_if_axi_wr_w_dat")
   , ccs_rtl_SIG_if_axi_wr_b_vld("ccs_rtl_SIG_if_axi_wr_b_vld")
   , ccs_rtl_SIG_if_axi_wr_b_rdy("ccs_rtl_SIG_if_axi_wr_b_rdy")
   , ccs_rtl_SIG_if_axi_wr_b_dat("ccs_rtl_SIG_if_axi_wr_b_dat")
   , SIG_SC_LOGIC_0("SIG_SC_LOGIC_0")
   , SIG_SC_LOGIC_1("SIG_SC_LOGIC_1")
{
   // Instantiate other modules
   ccs_rtl.clk(ccs_rtl_SIG_clk);
   ccs_rtl.rst(ccs_rtl_SIG_rst);
   ccs_rtl.interrupt(ccs_rtl_SIG_interrupt);
   ccs_rtl.if_axi_rd_ar_vld(ccs_rtl_SIG_if_axi_rd_ar_vld);
   ccs_rtl.if_axi_rd_ar_rdy(ccs_rtl_SIG_if_axi_rd_ar_rdy);
   ccs_rtl.if_axi_rd_ar_dat(ccs_rtl_SIG_if_axi_rd_ar_dat);
   ccs_rtl.if_axi_rd_r_vld(ccs_rtl_SIG_if_axi_rd_r_vld);
   ccs_rtl.if_axi_rd_r_rdy(ccs_rtl_SIG_if_axi_rd_r_rdy);
   ccs_rtl.if_axi_rd_r_dat(ccs_rtl_SIG_if_axi_rd_r_dat);
   ccs_rtl.if_axi_wr_aw_vld(ccs_rtl_SIG_if_axi_wr_aw_vld);
   ccs_rtl.if_axi_wr_aw_rdy(ccs_rtl_SIG_if_axi_wr_aw_rdy);
   ccs_rtl.if_axi_wr_aw_dat(ccs_rtl_SIG_if_axi_wr_aw_dat);
   ccs_rtl.if_axi_wr_w_vld(ccs_rtl_SIG_if_axi_wr_w_vld);
   ccs_rtl.if_axi_wr_w_rdy(ccs_rtl_SIG_if_axi_wr_w_rdy);
   ccs_rtl.if_axi_wr_w_dat(ccs_rtl_SIG_if_axi_wr_w_dat);
   ccs_rtl.if_axi_wr_b_vld(ccs_rtl_SIG_if_axi_wr_b_vld);
   ccs_rtl.if_axi_wr_b_rdy(ccs_rtl_SIG_if_axi_wr_b_rdy);
   ccs_rtl.if_axi_wr_b_dat(ccs_rtl_SIG_if_axi_wr_b_dat);
   
   // Register processes
   SC_METHOD(update_proc);
   sensitive  << clk << rst << ccs_rtl_SIG_interrupt << if_axi_rd.axi::axi4<spec::Axi::axiCfg >::read::subordinate<Connections::SYN_PORT >::ar.Connections::InBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::AddrPayload >::vld << ccs_rtl_SIG_if_axi_rd_ar_rdy << if_axi_rd.axi::axi4<spec::Axi::axiCfg >::read::subordinate<Connections::SYN_PORT >::ar.Connections::InBlocking<axi::axi4<spec::Axi::axiCfg >::AddrPayload, Connections::SYN_PORT >::dat << ccs_rtl_SIG_if_axi_rd_r_vld << if_axi_rd.axi::axi4<spec::Axi::axiCfg >::read::subordinate<Connections::SYN_PORT >::r.Connections::OutBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::ReadPayload >::rdy << ccs_rtl_SIG_if_axi_rd_r_dat << if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::aw.Connections::InBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::AddrPayload >::vld << ccs_rtl_SIG_if_axi_wr_aw_rdy << if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::aw.Connections::InBlocking<axi::axi4<spec::Axi::axiCfg >::AddrPayload, Connections::SYN_PORT >::dat << if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::w.Connections::InBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::WritePayload >::vld << ccs_rtl_SIG_if_axi_wr_w_rdy << if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::w.Connections::InBlocking<axi::axi4<spec::Axi::axiCfg >::WritePayload, Connections::SYN_PORT >::dat << ccs_rtl_SIG_if_axi_wr_b_vld << if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::b.Connections::OutBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::WRespPayload >::rdy << ccs_rtl_SIG_if_axi_wr_b_dat;
   // Other constructor statements
   SIG_SC_LOGIC_0.write(SC_LOGIC_0);
   SIG_SC_LOGIC_1.write(SC_LOGIC_1);
}

// ---------------------------------------------------------------
// Process: SC_METHOD update_proc

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   
   // none.sc_in field_key=clk:c20db7e3-040a-4f95-9692-b107f5932668-4269:clk:c20db7e3-040a-4f95-9692-b107f5932668-4269
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4269; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:c20db7e3-040a-4f95-9692-b107f5932668-4270:rst:c20db7e3-040a-4f95-9692-b107f5932668-4270
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4270; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_c20db7e3_040a_4f95_9692_b107f5932668_4270); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_c20db7e3_040a_4f95_9692_b107f5932668_4270); // then write to RTL port
   
   // none.sc_out field_key=interrupt:c20db7e3-040a-4f95-9692-b107f5932668-4271:interrupt:c20db7e3-040a-4f95-9692-b107f5932668-4271
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4271;
   bool d_c20db7e3_040a_4f95_9692_b107f5932668_4271;
   t_c20db7e3_040a_4f95_9692_b107f5932668_4271 = ccs_rtl_SIG_interrupt.read();
   vector_to_type(t_c20db7e3_040a_4f95_9692_b107f5932668_4271, 1, &d_c20db7e3_040a_4f95_9692_b107f5932668_4271);
   interrupt.write(d_c20db7e3_040a_4f95_9692_b107f5932668_4271);
   
   // none.sc_in field_key=if_axi_rd:c20db7e3-040a-4f95-9692-b107f5932668-4272:vld:c20db7e3-040a-4f95-9692-b107f5932668-4290
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4290; // NPS - LV to hold field
   type_to_vector(if_axi_rd.axi::axi4<spec::Axi::axiCfg >::read::subordinate<Connections::SYN_PORT >::ar.Connections::InBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::AddrPayload >::vld.read(),1,t_c20db7e3_040a_4f95_9692_b107f5932668_4290); // read orig port and type convert
   ccs_rtl_SIG_if_axi_rd_ar_vld.write(t_c20db7e3_040a_4f95_9692_b107f5932668_4290); // then write to RTL port
   
   // none.sc_out field_key=if_axi_rd:c20db7e3-040a-4f95-9692-b107f5932668-4272:rdy:c20db7e3-040a-4f95-9692-b107f5932668-4291
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4291;
   bool d_c20db7e3_040a_4f95_9692_b107f5932668_4291;
   t_c20db7e3_040a_4f95_9692_b107f5932668_4291 = ccs_rtl_SIG_if_axi_rd_ar_rdy.read();
   vector_to_type(t_c20db7e3_040a_4f95_9692_b107f5932668_4291, 1, &d_c20db7e3_040a_4f95_9692_b107f5932668_4291);
   if_axi_rd.axi::axi4<spec::Axi::axiCfg >::read::subordinate<Connections::SYN_PORT >::ar.Connections::InBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::AddrPayload >::rdy.write(d_c20db7e3_040a_4f95_9692_b107f5932668_4291);
   
   // none.sc_in field_key=if_axi_rd:c20db7e3-040a-4f95-9692-b107f5932668-4272:dat:c20db7e3-040a-4f95-9692-b107f5932668-4292
   sc_lv< 50 > t_c20db7e3_040a_4f95_9692_b107f5932668_4292; // NPS - LV to hold field
   type_to_vector(if_axi_rd.axi::axi4<spec::Axi::axiCfg >::read::subordinate<Connections::SYN_PORT >::ar.Connections::InBlocking<axi::axi4<spec::Axi::axiCfg >::AddrPayload, Connections::SYN_PORT >::dat.read(),50,t_c20db7e3_040a_4f95_9692_b107f5932668_4292); // read orig port and type convert
   ccs_rtl_SIG_if_axi_rd_ar_dat.write(t_c20db7e3_040a_4f95_9692_b107f5932668_4292); // then write to RTL port
   
   // none.sc_out field_key=if_axi_rd:c20db7e3-040a-4f95-9692-b107f5932668-4272:vld:c20db7e3-040a-4f95-9692-b107f5932668-4302
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4302;
   bool d_c20db7e3_040a_4f95_9692_b107f5932668_4302;
   t_c20db7e3_040a_4f95_9692_b107f5932668_4302 = ccs_rtl_SIG_if_axi_rd_r_vld.read();
   vector_to_type(t_c20db7e3_040a_4f95_9692_b107f5932668_4302, 1, &d_c20db7e3_040a_4f95_9692_b107f5932668_4302);
   if_axi_rd.axi::axi4<spec::Axi::axiCfg >::read::subordinate<Connections::SYN_PORT >::r.Connections::OutBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::ReadPayload >::vld.write(d_c20db7e3_040a_4f95_9692_b107f5932668_4302);
   
   // none.sc_in field_key=if_axi_rd:c20db7e3-040a-4f95-9692-b107f5932668-4272:rdy:c20db7e3-040a-4f95-9692-b107f5932668-4303
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4303; // NPS - LV to hold field
   type_to_vector(if_axi_rd.axi::axi4<spec::Axi::axiCfg >::read::subordinate<Connections::SYN_PORT >::r.Connections::OutBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::ReadPayload >::rdy.read(),1,t_c20db7e3_040a_4f95_9692_b107f5932668_4303); // read orig port and type convert
   ccs_rtl_SIG_if_axi_rd_r_rdy.write(t_c20db7e3_040a_4f95_9692_b107f5932668_4303); // then write to RTL port
   
   // none.sc_out field_key=if_axi_rd:c20db7e3-040a-4f95-9692-b107f5932668-4272:dat:c20db7e3-040a-4f95-9692-b107f5932668-4304
   sc_lv< 141 > t_c20db7e3_040a_4f95_9692_b107f5932668_4304;
   sc_dt::sc_lv<141 > d_c20db7e3_040a_4f95_9692_b107f5932668_4304;
   t_c20db7e3_040a_4f95_9692_b107f5932668_4304 = ccs_rtl_SIG_if_axi_rd_r_dat.read();
   vector_to_type(t_c20db7e3_040a_4f95_9692_b107f5932668_4304, 141, &d_c20db7e3_040a_4f95_9692_b107f5932668_4304);
   if_axi_rd.axi::axi4<spec::Axi::axiCfg >::read::subordinate<Connections::SYN_PORT >::r.Connections::OutBlocking<axi::axi4<spec::Axi::axiCfg >::ReadPayload, Connections::SYN_PORT >::dat.write(d_c20db7e3_040a_4f95_9692_b107f5932668_4304);
   
   // none.sc_in field_key=if_axi_wr:c20db7e3-040a-4f95-9692-b107f5932668-4305:vld:c20db7e3-040a-4f95-9692-b107f5932668-4318
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4318; // NPS - LV to hold field
   type_to_vector(if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::aw.Connections::InBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::AddrPayload >::vld.read(),1,t_c20db7e3_040a_4f95_9692_b107f5932668_4318); // read orig port and type convert
   ccs_rtl_SIG_if_axi_wr_aw_vld.write(t_c20db7e3_040a_4f95_9692_b107f5932668_4318); // then write to RTL port
   
   // none.sc_out field_key=if_axi_wr:c20db7e3-040a-4f95-9692-b107f5932668-4305:rdy:c20db7e3-040a-4f95-9692-b107f5932668-4319
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4319;
   bool d_c20db7e3_040a_4f95_9692_b107f5932668_4319;
   t_c20db7e3_040a_4f95_9692_b107f5932668_4319 = ccs_rtl_SIG_if_axi_wr_aw_rdy.read();
   vector_to_type(t_c20db7e3_040a_4f95_9692_b107f5932668_4319, 1, &d_c20db7e3_040a_4f95_9692_b107f5932668_4319);
   if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::aw.Connections::InBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::AddrPayload >::rdy.write(d_c20db7e3_040a_4f95_9692_b107f5932668_4319);
   
   // none.sc_in field_key=if_axi_wr:c20db7e3-040a-4f95-9692-b107f5932668-4305:dat:c20db7e3-040a-4f95-9692-b107f5932668-4320
   sc_lv< 50 > t_c20db7e3_040a_4f95_9692_b107f5932668_4320; // NPS - LV to hold field
   type_to_vector(if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::aw.Connections::InBlocking<axi::axi4<spec::Axi::axiCfg >::AddrPayload, Connections::SYN_PORT >::dat.read(),50,t_c20db7e3_040a_4f95_9692_b107f5932668_4320); // read orig port and type convert
   ccs_rtl_SIG_if_axi_wr_aw_dat.write(t_c20db7e3_040a_4f95_9692_b107f5932668_4320); // then write to RTL port
   
   // none.sc_in field_key=if_axi_wr:c20db7e3-040a-4f95-9692-b107f5932668-4305:vld:c20db7e3-040a-4f95-9692-b107f5932668-4330
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4330; // NPS - LV to hold field
   type_to_vector(if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::w.Connections::InBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::WritePayload >::vld.read(),1,t_c20db7e3_040a_4f95_9692_b107f5932668_4330); // read orig port and type convert
   ccs_rtl_SIG_if_axi_wr_w_vld.write(t_c20db7e3_040a_4f95_9692_b107f5932668_4330); // then write to RTL port
   
   // none.sc_out field_key=if_axi_wr:c20db7e3-040a-4f95-9692-b107f5932668-4305:rdy:c20db7e3-040a-4f95-9692-b107f5932668-4331
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4331;
   bool d_c20db7e3_040a_4f95_9692_b107f5932668_4331;
   t_c20db7e3_040a_4f95_9692_b107f5932668_4331 = ccs_rtl_SIG_if_axi_wr_w_rdy.read();
   vector_to_type(t_c20db7e3_040a_4f95_9692_b107f5932668_4331, 1, &d_c20db7e3_040a_4f95_9692_b107f5932668_4331);
   if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::w.Connections::InBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::WritePayload >::rdy.write(d_c20db7e3_040a_4f95_9692_b107f5932668_4331);
   
   // none.sc_in field_key=if_axi_wr:c20db7e3-040a-4f95-9692-b107f5932668-4305:dat:c20db7e3-040a-4f95-9692-b107f5932668-4332
   sc_lv< 145 > t_c20db7e3_040a_4f95_9692_b107f5932668_4332; // NPS - LV to hold field
   type_to_vector(if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::w.Connections::InBlocking<axi::axi4<spec::Axi::axiCfg >::WritePayload, Connections::SYN_PORT >::dat.read(),145,t_c20db7e3_040a_4f95_9692_b107f5932668_4332); // read orig port and type convert
   ccs_rtl_SIG_if_axi_wr_w_dat.write(t_c20db7e3_040a_4f95_9692_b107f5932668_4332); // then write to RTL port
   
   // none.sc_out field_key=if_axi_wr:c20db7e3-040a-4f95-9692-b107f5932668-4305:vld:c20db7e3-040a-4f95-9692-b107f5932668-4342
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4342;
   bool d_c20db7e3_040a_4f95_9692_b107f5932668_4342;
   t_c20db7e3_040a_4f95_9692_b107f5932668_4342 = ccs_rtl_SIG_if_axi_wr_b_vld.read();
   vector_to_type(t_c20db7e3_040a_4f95_9692_b107f5932668_4342, 1, &d_c20db7e3_040a_4f95_9692_b107f5932668_4342);
   if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::b.Connections::OutBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::WRespPayload >::vld.write(d_c20db7e3_040a_4f95_9692_b107f5932668_4342);
   
   // none.sc_in field_key=if_axi_wr:c20db7e3-040a-4f95-9692-b107f5932668-4305:rdy:c20db7e3-040a-4f95-9692-b107f5932668-4343
   sc_logic t_c20db7e3_040a_4f95_9692_b107f5932668_4343; // NPS - LV to hold field
   type_to_vector(if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::b.Connections::OutBlocking_Ports_abs<axi::axi4<spec::Axi::axiCfg >::WRespPayload >::rdy.read(),1,t_c20db7e3_040a_4f95_9692_b107f5932668_4343); // read orig port and type convert
   ccs_rtl_SIG_if_axi_wr_b_rdy.write(t_c20db7e3_040a_4f95_9692_b107f5932668_4343); // then write to RTL port
   
   // none.sc_out field_key=if_axi_wr:c20db7e3-040a-4f95-9692-b107f5932668-4305:dat:c20db7e3-040a-4f95-9692-b107f5932668-4344
   sc_lv< 12 > t_c20db7e3_040a_4f95_9692_b107f5932668_4344;
   sc_dt::sc_lv<12 > d_c20db7e3_040a_4f95_9692_b107f5932668_4344;
   t_c20db7e3_040a_4f95_9692_b107f5932668_4344 = ccs_rtl_SIG_if_axi_wr_b_dat.read();
   vector_to_type(t_c20db7e3_040a_4f95_9692_b107f5932668_4344, 12, &d_c20db7e3_040a_4f95_9692_b107f5932668_4344);
   if_axi_wr.axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT >::b.Connections::OutBlocking<axi::axi4<spec::Axi::axiCfg >::WRespPayload, Connections::SYN_PORT >::dat.write(d_c20db7e3_040a_4f95_9692_b107f5932668_4344);
}
