// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.h
//
//    HLS version: 2024.2_1/1143609 Production Release
//       HLS date: Wed Nov 13 18:57:31 PST 2024
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: code@iron-05
// Generated date: Wed Mar 18 19:39:17 PDT 2026
//
// ----------------------------------------------------------------------------
#ifndef INCLUDED_SYSC_SIM_WRAPPER_H
#define INCLUDED_SYSC_SIM_WRAPPER_H
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model Top
// -------------------------------------
// 

#ifndef TO_QUOTED_STRING
#define TO_QUOTED_STRING(x) TO_QUOTED_STRING1(x)
#define TO_QUOTED_STRING1(x) #x
#endif
extern double __scv_hold_time;


#ifndef SC_USE_STD_STRING
#define SC_USE_STD_STRING
#endif

#include "../../../../src/Top/Top.h"
#include <systemc.h>
#include <mc_stall_ctrl.h>
#include <mc_scv_trans.h>
#include "mc_dut_wrapper.h"


namespace CCS_RTL {
   class sysc_sim_wrapper : public sc_module
   {
   public:
      // Module instance pointers
      HDL::ccs_DUT_wrapper ccs_rtl;
      
      // Interface Ports
      sc_core::sc_in<bool > clk;
      sc_core::sc_in<bool > rst;
      sc_core::sc_out<bool > interrupt;
      axi::axi4<spec::Axi::axiCfg >::read::subordinate<Connections::SYN_PORT > if_axi_rd;
      axi::axi4<spec::Axi::axiCfg >::write::subordinate<Connections::SYN_PORT > if_axi_wr;
      
      // Named Objects
      
      // Data objects
      sc_signal< bool >                          ccs_rtl_SIG_clk;
      sc_signal< sc_logic >                      ccs_rtl_SIG_rst;
      sc_signal< sc_logic >                      ccs_rtl_SIG_interrupt;
      sc_signal< sc_logic >                      ccs_rtl_SIG_if_axi_rd_ar_vld;
      sc_signal< sc_logic >                      ccs_rtl_SIG_if_axi_rd_ar_rdy;
      sc_signal< sc_lv<50> >                     ccs_rtl_SIG_if_axi_rd_ar_dat;
      sc_signal< sc_logic >                      ccs_rtl_SIG_if_axi_rd_r_vld;
      sc_signal< sc_logic >                      ccs_rtl_SIG_if_axi_rd_r_rdy;
      sc_signal< sc_lv<141> >                    ccs_rtl_SIG_if_axi_rd_r_dat;
      sc_signal< sc_logic >                      ccs_rtl_SIG_if_axi_wr_aw_vld;
      sc_signal< sc_logic >                      ccs_rtl_SIG_if_axi_wr_aw_rdy;
      sc_signal< sc_lv<50> >                     ccs_rtl_SIG_if_axi_wr_aw_dat;
      sc_signal< sc_logic >                      ccs_rtl_SIG_if_axi_wr_w_vld;
      sc_signal< sc_logic >                      ccs_rtl_SIG_if_axi_wr_w_rdy;
      sc_signal< sc_lv<145> >                    ccs_rtl_SIG_if_axi_wr_w_dat;
      sc_signal< sc_logic >                      ccs_rtl_SIG_if_axi_wr_b_vld;
      sc_signal< sc_logic >                      ccs_rtl_SIG_if_axi_wr_b_rdy;
      sc_signal< sc_lv<12> >                     ccs_rtl_SIG_if_axi_wr_b_dat;
      sc_signal< sc_logic >                      SIG_SC_LOGIC_0;
      sc_signal< sc_logic >                      SIG_SC_LOGIC_1;
      
      // Declare processes (SC_METHOD and SC_THREAD)
      void update_proc();
      
      // Constructor
      SC_HAS_PROCESS(sysc_sim_wrapper);
      sysc_sim_wrapper(
         const sc_module_name& nm
      );
      ~sysc_sim_wrapper()
      {
      }
      
      // C++ class functions
   };
} // end namespace CCS_RTL
#endif //INCLUDED_SYSC_SIM_WRAPPER_H
